Feat/#120 .env 환경 변수 설정 및 MSW 설정
woowacourse-teams/2023-shook pull request #132
Opened 2023-07-26 13:28 UTC by ukkodeveloper

## 📝작업 내용

.env 환경 변수 설정 및 MSW 설정

작업내용
- [x] .env 환경변수 설정
- [x] MSW 설치
- [x] MSW 기본 설정 (개발환경 시 작동)
- [x] 더미데이터 추가
 
## 💬리뷰 참고사항
- mockServiceWorker.js 를 gitignore 해야할까요?
- index.tsx에서 'develop'모드일 때만 MSW 작동하도록 하였어요. 그런데 이 부분 코드가 지저분해졌더라고요. 조금 더 깔끔하게 짤 수 있는 방법 있으면 말씀해주세요!
- .env 환경변수 설정에서 MODE변수를 주어서 'development'와 'production' 모드를 구분하였어요. 이 부분도 검토 해주세요.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #120

2023-07-26 23:44 UTC, cruelladevil requested changes
👍 필요한 부분만 적절하게 잘 구현해주신 것 같아요

### 참고사항에 대한 답변

> mockServiceWorker.js 를 gitignore 해야할까요?

![image](https://github.com/woowacourse-teams/2023-shook/assets/87710730/d58947e5-fc64-43c2-9f91-c8244b9212a8)

https://mswjs.io/docs/getting-started/integrate/browser#where-is-my-public-directory

> index.tsx에서 'develop'모드일 때만 MSW 작동하도록 하였어요. 그런데 이 부분 코드가 지저분해졌더라고요. 조금 더 깔끔하게 짤 수 있는 방법 있으면 말씀해주세요!

💬 cra에서는 env를 어떻게 제공하는지, 어떻게 관리하는지 살펴보면 도움이 될 것 같아요

[cra에서 환경변수 사용 방법](https://junhyunny.github.io/react/react-env-variable-setting/#2-%EC%8B%A4%ED%96%89-%ED%99%98%EA%B2%BD-%EB%B6%84%EB%A6%AC)
[cra 환경변수 설정 소스코드](https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/config/env.js)

> .env 환경변수 설정에서 MODE변수를 주어서 'development'와 'production' 모드를 구분하였어요. 이 부분도 검토 해주세요.

💬 이미 파일로 분리되어서 실행시켜주시는 것 같은데 MODE가 필요한 상황이 어떤 상황인가요?

2023-07-26 23:44 UTC, cruelladevil commented on frontend/src/mocks/browser.ts
> +// src/mocks/browser.js
💬 불필요한 주석인 것 같아요

2023-07-26 23:44 UTC, cruelladevil commented on frontend/src/mocks/browser.ts
> +// This configures a Service Worker with the given request handlers.
💬 불필요한 주석인 것 같아요 2

2023-07-26 23:44 UTC, cruelladevil commented on frontend/src/mocks/handlers.ts
> +export const handlers = [...songsHandlers];
💬 handler들을 모으는 handlers가 없이 바로 setupWorker로 넣는 것은 어떤가요?

```typescript
const worker = setupWorker(...songsHandlers, ...otherHandlers);
```

2023-07-26 23:44 UTC, cruelladevil commented on frontend/src/mocks/mockingData.json
> +[
어느 데이터를 뜻하는 파일인지 파일명을 명시하면 좋을 것 같아요.

💬 또한 목데이터를 모아놓는 폴더로 따로 나뉘면 좋을 것 같네요. (ex - datas or fixtures)

2023-07-26 23:44 UTC, cruelladevil commented on frontend/src/mocks/songsHandlers.ts
> +    }
서버의 응답없이 그냥 return하는 것은 좋지 않을 것 같아요
없는 데이터에 대한 response도 정의하면 좋을 것 같네요

```typescript
if (!song) {
  return res(
    ctx.status(404),
    ctx.json({ message: `id:${songId}에 해당되는 노래가 없습니다.`}),
  );
}
```

2023-07-26 23:44 UTC, cruelladevil commented on frontend/package.json
>    }
💬 어떤 역할을 하는 건지 궁금해요!

2023-07-26 23:44 UTC, cruelladevil commented on frontend/package.json
>    }
![image](https://github.com/woowacourse-teams/2023-shook/assets/87710730/dac32988-0737-432c-831e-337cb13acefc)


(향후 msw 패키지를 업데이트할 때 worker script에 대한 모든 업데이트가 자동으로 적용됩니다.)

msw 패키지가 업데이트 되었을 때에 해당되는 이야기 같네요.

💬 msw를 최신 버전 사용을 의도한다면 아래와 같이 변경해야 될 것 같아요.

```json
  "msw": "latest",
```

https://mswjs.io/docs/getting-started/integrate/browser

2023-07-27 04:19 UTC, ukkodeveloper commented on frontend/package.json
>    }
꼭 msw 패키지 최신 버전을 업데이트하는 용도로만 `"workerDirectory": "public"`를 한다고 저는 생각하지 않아요. `mockServiceWorker.js` 에 있는 주석에 따르면, 'Please do NOT serve this file on production.' 라고 되어 있더라고요. 아무래도, gitignore을 해야할 것 같습니다. 그렇다면, npm ci할 때마다 해당 패키지 버전에 맞는 mockServiceWorker.js를 생성하기 위해 `"workerDirectory": "public"`가 필요하지 않을까요?

2023-07-27 04:19 UTC, ukkodeveloper commented on frontend/src/mocks/handlers.ts
> +export const handlers = [...songsHandlers];
좋습니다.

2023-07-27 04:19 UTC, ukkodeveloper commented on frontend/src/mocks/mockingData.json
> +[
좋아요

2023-07-27 04:28 UTC, Creative-Lee approved these changes
몇가지 질문만 남겨놓았습니다.
설정 고생 많으셨습니다!

2023-07-27 04:28 UTC, Creative-Lee commented on frontend/src/index.tsx
> +const mswWork = async () => {
💬이렇게 환경별로 실행될 함수를 나누는 이유가 있나요?
 환경에 따라 워커를 실행하거나 하지 않거나만 할수는 없나요?

2023-07-27 04:28 UTC, Creative-Lee commented on frontend/src/mocks/handlers.ts
> +export const handlers = [...songsHandlers];
💬 추후 핸들러가 많아지면 handlers 디렉터리를 만들게 될것 같고,
그렇게 되면 모아서 내보내는게 관리가 쉬울 듯 한데 어떻게 생각하세요?

``` ts
// ex
import { cart } from './cart';
import { members } from './members';
import { orders } from './orders';
import { product } from './product';

const handler = [...cart, ...product, ...members, ...orders];

export default handler;
```

2023-07-27 04:28 UTC, cruelladevil commented on frontend/package.json
>    }
👍 해당 내용과 패키지를 설치할 때 자동으로 `mockServiceWorker.js`가 설치되는 점까지 확인하였습니다.
`삭제` 커밋과 `.gitignore` 커밋 추가하는 방향으로 진행해도 괜찮을 것 같아요 :)

2023-07-27 11:33 UTC, ukkodeveloper commented on frontend/src/index.tsx
> +const mswWork = async () => {
해당 사항 반영했습니다. 오늘 이야기한 것처럼 top-level에서 worker을  import할 수도 있지만, 보통 production 환경에서 worker을 로드하지 않기 위해 동적 import를 한다고 합니다.

2023-07-27 11:36 UTC, ukkodeveloper commented on frontend/src/mocks/handlers.ts
> +export const handlers = [...songsHandlers];
handlers 디렉터리를 만들게 될것 같다 하여 handlers 디렉터리를 추가했어요. 그리고 handler를 한 데에 모아서 export하나, browser worker에 인자로 주입하나 조삼모사인것  같습니다.

2023-07-27 11:39 UTC, cruelladevil approved these changes

2023-07-27 11:40 UTC, merged