Feat/#134 파트에 댓글 작성 기능 추가
woowacourse-teams/2023-shook pull request #146
Opened 2023-07-28 03:10 UTC by splitCoding

## 📝작업 내용

파트별 댓글
- [x] 파트에 댓글 생성
- [x] 파트별 댓글 전체 조회
	- [x] 정렬 기준 : 최신순

## 💬리뷰 참고사항

## #️⃣연관된 이슈

close #134

2023-07-28 08:40 UTC, somsom13 requested changes
고생하셨어요 스플릿 짱짱 👍 👍

2023-07-28 08:40 UTC, somsom13 commented on backend/src/main/java/shook/shook/part/application/dto/PartCommentsResponse.java
> +
PartCommentsResponse 는 내부에 List 하나만 가지는 것 같은데, 그러면 json으로 응답을 받았을 때 불필요한 뎁스가 깊어지는 건 아닐까~~ 라는 생각이 들어요!

![image](https://github.com/woowacourse-teams/2023-shook/assets/70891072/4b23dc47-cafa-497e-8563-db02e9ffc578)

++) 프론트엔드 입장에서는 단일 List만 들어온다는걸 API 명세로 알고 있는 경우에는 포장이 없는게 더 편하다고 합니닷

2023-07-28 08:40 UTC, somsom13 commented on backend/src/main/java/shook/shook/part/domain/PartComment.java
> +@Table(name = "part_comment")
💬 `@Table` 을 명시하지 않아도 H2 상에서는 `part_comment` 로 테이블이 생성되는 것 같은데 이름을 명시한 이유가 있는지 궁금해요~!

2023-07-28 08:40 UTC, somsom13 commented on backend/src/main/java/shook/shook/part/ui/PartCommentController.java
> +        return ResponseEntity.ok().body(partReplies);
💬 body 로 따로 response를 담아준 이유가 있는지도 궁금해요~!

2023-07-28 08:40 UTC, somsom13 commented on backend/src/test/java/shook/shook/part/application/PartCommentServiceTest.java
> +        Song SAVED_SONG = songRepository.save(new Song("제목", "비디오URL", "가수", 30));
static 변수가 아니라면 소문자로 변수명을 쓰는건 어떨까용 ㅎ.ㅎ

2023-07-28 08:40 UTC, somsom13 commented on backend/src/test/java/shook/shook/part/domain/PartCommentContentTest.java
> +    @ValueSource(strings = {"", " "})
👍 👍 👍

2023-07-28 08:40 UTC, somsom13 commented on backend/src/test/java/shook/shook/part/domain/PartCommentsTest.java
> +        assertThat(repliesInRecentOrder).usingRecursiveComparison().isEqualTo(List.of(early, late));
이 테스트에서도 최신순 정렬이면 late이 먼저 오는게 맞지 않을까요 ?.?

2023-07-28 08:40 UTC, somsom13 commented on backend/src/test/java/shook/shook/part/domain/repository/PartCommentRepositoryTest.java
> +        assertThat(partComment.getId()).isNotNull();
💬 검증할 내용이 여러개인 경우에 assertAll 을 사용하는건 혹시 어떻게 생각하시나요?

2023-07-28 08:40 UTC, somsom13 commented on backend/src/test/java/shook/shook/part/ui/PartCommentControllerTest.java
> +        assertThat(response.getPartReplies().get(0).getContent()).isEqualTo("댓글 내용");
💬 요런 리스트를 검증하는 테스트에서 `usingRecursiveComparison` 을 사용하지 않고 따로 검증한 이유가 궁금해요!

2023-07-28 08:40 UTC, somsom13 commented on backend/src/main/java/shook/shook/part/application/PartCommentService.java
> +            .orElseThrow(PartNotExistException::new);
`PartException.PartNotExistException` (상위예외.하위예외) 로 통일해야 할 것 같아요!

2023-07-29 07:02 UTC, splitCoding commented on backend/src/main/java/shook/shook/part/ui/PartCommentController.java
> +        return ResponseEntity.ok().body(partReplies);
메서드 체인닝에는 가독성 향상에 있어서 큰 장점 가진다고 생각합니다! 😊
`ok(response)` 보다는 `ok().body(response)` 가 가독성이 훨씬 좋다고 생각하여 택하였습니다!

2023-07-29 07:03 UTC, splitCoding commented on backend/src/main/java/shook/shook/part/domain/PartComments.java
> +            .sorted(Comparator.comparing((PartComment::getCreatedAt)))
괄호 두번은 전혀 의도되지 않았습니다ㅎㅎ 💩

2023-07-29 07:05 UTC, splitCoding commented on backend/src/main/java/shook/shook/part/domain/PartComment.java
> +@Table(name = "part_comment")
다른 Entity 에도 모두 @Table로 명시해주기로 했던 것으로 저는 기억하고 있습니다! 
현재 존재하는 다른 Entity에도 모두 @Table 이 있는 것으로 확인 됩니다~ 

한번 더 다 같이 논의해보면 좋을 것 같아요~😄

2023-07-29 07:15 UTC, splitCoding commented on backend/src/test/java/shook/shook/part/ui/PartCommentControllerTest.java
> +        assertThat(response.getPartReplies().get(0).getContent()).isEqualTo("댓글 내용");
검증하려는 대상이 @PrePersist 어노테이션에 의존하는 로직이 존재하기에 개발자가 직접 해당 같은 필드를 가진 Response 생성이 불가한 상황이였습니다!

검증하려는 필드가 content 한개인 상황에서 `usingRecursiveComparsion`을 사용하여 아래와 같은 메서드로 검증해도 좋다고 생각합니다~

```java
assertThat(response.getPartReplies())
            .usingRecursiveComparison()
            .ignoringFields("createdAt")
            .isEqualTo(List.of(new PartCommentResponse("댓글 내용", null)));
```

개인마다의 생각이 다를 테지만 저한테 있어서는 기존 코드가 조금 가독성이 좋다고 생각하여 사용하였습니다!!😊

2023-07-29 07:19 UTC, splitCoding commented on backend/src/test/java/shook/shook/part/domain/repository/PartCommentRepositoryTest.java
> +        assertThat(partComment.getId()).isNotNull();
저도 assertThat 문이 많아져 가독성이 떨어지는 경우 assertAll을 쓰는 편입니다!👍

하지만 개인적으로 검증 문이 2개 존재할 때 있어서 assertAll을 사용해서 묶어서 가독성 향상이 느껴지지는 않는 것 같아서 사용하지 않았습니다 😁

2023-07-30 15:27 UTC, seokhwan-an requested changes
전체적으로 코드가 엄청깔끔해서 읽기 쉬웠습니다 👍 👍 또 테스트 역시 꼼꼼하게 작성한 것 역시 좋았습니다
간단한 리뷰 몇가지 남겼습니다.

2023-07-30 15:27 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/part/application/dto/PartCommentResponse.java
> +    }
정적 팩토리 메소드를 이용하는데 @AllArgsConstructor의 접근제어자가 현재 public으로 되어 있습니다. 이 부분 private으로 변경하면 좋을 것 같아요~

2023-07-30 15:27 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/part/ui/PartCommentControllerTest.java
> +            .getList(".", PartCommentResponse.class);
요청결과를 상태코드만 체크하는 것이 아니라 응답내용까지 체크하는 것 최곱니다 👍 👍

2023-07-31 02:41 UTC, splitCoding commented on backend/src/main/java/shook/shook/part/application/dto/PartCommentResponse.java
> +    private final LocalDateTime createdAt;
현재 코드에서 댓글의 수정, 삭제에 대해서 고려를 하지 않아 필요하지 않은 응답이라고 생각해서 추가하지 않았습니다!!

근데 id는 기본 응답에 포함해도 괜찮을 것 같아요!! 추가하겠습니다~ 👍

2023-07-31 04:36 UTC, Cyma-s requested changes
잘 구현해주셔서 코드적인 부분보다는 컨벤션 관련 코멘트가 많네요
수고 많으셨습니다 ~~~~

2023-07-31 04:36 UTC, Cyma-s commented on backend/src/test/java/shook/shook/part/ui/PartCommentControllerTest.java
> +    @DisplayName("파트에 댓글 등록시 상태코드 CREATED 를 반환한다.")
💬저번에 DisplayName은 상태코드 숫자를 썼던 것 같은데, 하나로 통일해보는 건 어떠신가요 ☺️

2023-07-31 07:51 UTC, somsom13 commented on backend/src/main/java/shook/shook/part/ui/PartCommentController.java
> +        return ResponseEntity.ok().body(partReplies);
이건 나중에 같이 이야기해보고 통일하면 좋을 것 같습니당 ㅎ.ㅎ

2023-07-31 07:51 UTC, somsom13 commented on backend/src/main/java/shook/shook/part/domain/PartComment.java
> +@Table(name = "part_comment")
앗 제가 놓쳤나봐요 😅  `@table` 어노테이션 있는거 좋습니다!

2023-08-02 03:17 UTC, splitCoding commented on backend/src/test/java/shook/shook/part/ui/PartCommentControllerTest.java
> +    @DisplayName("파트에 댓글 등록시 상태코드 CREATED 를 반환한다.")
상태코드 숫자로 통일하였습니다!!👍

2023-08-02 03:36 UTC, splitCoding commented on backend/src/main/java/shook/shook/part/ui/PartCommentController.java
> +        return ResponseEntity.ok().body(partReplies);
아니 제가 이전에는 ok(response) 를 사용했더라구요 😅 ㅎㅎㅎ

저도 익숙한게 ok(response) 인 것 같습니다!!

ok(response)로 적용하도록 하겠습니다!!👍

2023-08-02 04:02 UTC, splitCoding commented on backend/src/main/java/shook/shook/part/domain/PartComment.java
> +    }
MILLIS truncate 관련으로 문제가 되었던 부분이 실제 DB 데이터에 시간이

<img width="230" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/75476562/a011110e-9e9d-44d6-a932-5358d5572d46">

와 같이 밀리초에 대한 정보가 없던 것이였습니다!!  🧐

근데 확인해보니 이 과정은 쿼리에 now() 함수를 사용하면서 생긴 문제였고 api를 사용하여 데이터를 생성시에는 

<img width="230" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/75476562/e89e10f6-6d66-408c-81d6-c9d96cd16537">

밀리초까지 잘 나오는 것을 확인했습니다!! 👍

---

이전 createdAt 테스에서 문제가 되었던 부분은 다시 재차 체크해보았는데 성공할 때도 있고 실패할때도 존재했습니다.

<img width="770" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/75476562/b64a4340-960f-4a34-9967-6ec827ed9c3b">

<img width="790" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/75476562/cefbe295-40eb-4b89-b1fa-de982fff964e">

어떨 때는 prev를 저장 후 createdAt 생성까지 밀리초단위에서는 오차가 없는 경우가 있고
어떨 때는 차이가 있는 경우가 있습니다.

제가 파악하기에는 서버 시간 precision 의 차이보다 위에 문제였던 것 같습니다!!

---

이 부분에 대한 테스트에 대한 필요에 대해서는 추후 논의 해보면 좋을 것 같습니다!!👍

2023-08-02 04:36 UTC, somsom13 commented on backend/src/main/java/shook/shook/part/ui/PartCommentController.java
> +        return ResponseEntity.ok().body(partReplies);
네 ㅎㅎ

2023-08-02 04:43 UTC, Cyma-s approved these changes
아프신데도 열심히 해주셨네요
고생하셨습니다~

2023-08-02 04:43 UTC, somsom13 approved these changes
아픈 와중에도 너무 고생하셨어요~~~~ 최고예요!!

2023-08-02 04:44 UTC, seokhwan-an approved these changes
스플릿 사소한 부분까지 체크하는 것에서 좋았습니다.😄 리뷰 반영된 코드에서 수정할 부분이 없는 것 같습니다. 고생하셨습니다.

2023-08-02 04:45 UTC, merged