Feat/#128 노래 제목, 가수 검색 기능 구현
woowacourse-teams/2023-shook pull request #147
Opened 2023-07-28 03:29 UTC by somsom13

## 📝작업 내용

노래 제목, 가수 검색 기능 구현
- [x] 통합 검색 기능 구현
  - [x] 노래 제목 검색 - **정확한 검색**
  - [x] 가수 검색 - **정확한 검색**
  - [x] 가수, 제목 함께 검색 - **정확한 검색**

## 💬리뷰 참고사항

- `SongSearchController`의 하나의 검색 메서드에서 `title`, `singer` param을 모두 받을 수 있습니다.
  - title과 singer 파라미터는 필수가 아니기 때문에 둘 다 비어있는 상태로 요청이 오면 예외가 아닌 빈 결과를 반환하도록 구현했습니다. 예외 발생과 빈 값 반환 중 무엇이 좋을지 얘기해보면 좋을 것 같아요~!
- 아직 검색 API 명세를 결정하지 않아서 임의로 구성했고, `albumImage` 는 아직 DB에 반영되어 있지 않기 때문에 우선 null값으로 넣었습니다.
---
### 어떻게 고도화를 할 수 있을까....? 에 대해 조금 생각해본 내용
1. 통합 검색할 때 가수와 제목 둘 다 검색하는 경우는 둘 중에 우선순위를 두는 방향
- 가수가 우선순위가 높다면?
⇒ 우선 가수를 먼저 검색하고 거기에서 title을 필터링
⇒ 만약 일치하는 title이 없다면? 일치하는 가수의 노래 목록 반환
- 제목이 우선순위가 높다면?
⇒일치하는 제목을 먼저 찾고 거기에서 singer를 필터링
⇒ 만약 일치하는 singer가 없다면? 일치하는 제목의 노래를 모두 반환

2. 제목, 가수 중 정확한 검색 결과가 있는 쪽을 우선으로 반환
    1. 노래, 가수 둘 중에서 정확한 검색 결과가 있는 쪽을 먼저 찾아옴
    2. 정확한 결과가 있는 쪽 (즉 비어있지 않은 쪽) 에서 나머지 결과로 검색
    ex) 가수로 전체 조회 → 데이터가 있다면, 그 내부에서 일치하는 제목 필터링→ 완전히 일치하는 결과가 있다면 그 데이터를 반환, 없다면 가수 전체 조회 데이터를 반환

## #️⃣연관된 이슈

close #128

2023-07-29 09:24 UTC, splitCoding reviewed
바론 너무 고생했어 👍 해애푸움~ 두두두산~

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +                .isEqualTo(Collections.emptyList());
💬 혹시 isEmpty 는 어떠신가요~

```suggestion
            assertThat(responses).isEmpty();
```

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +    @DisplayName("제목이 비어있을 때")
💬 조금 더 자세한 설명이면 개인적으로 좋을 것 같아요!!

```suggestion
    @DisplayName("검색시 가수 이름만 존재하고 노래 제목이 없을 때")
```

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +    @DisplayName("가수가 비어있을 때")
💬
```suggestion
    @DisplayName("검색시 노래 제목만 존재하고 가수이름이 없을 때")
```

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +        @DisplayName("앞뒤 공백제거, 대소문자 상관없이 정확히 일치하는 제목의 모든 노래를 조회한다.")
💬
```suggestion
        @DisplayName("같은 제목의 노래를 모두 조회한다. ( 노래 제목의 앞뒤 공백만 제거하고 대소문자를 무시한다. )")
```

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +                .isEqualTo(Collections.emptyList());
위에 코멘트와 동일합니다!!

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +        @DisplayName("앞뒤 공백 제거, 대소문자 상관없이 제목과 가수가 모두 정확히 일치하는 모든 노래를 조회한다.")
위의 코멘트와 동일합니다!!

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +                .toList();
위의 코멘트와 동일합니다!!

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +                .isEqualTo(Collections.emptyList());
위의 코멘트와 동일합니다!!

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +    class SongSingerAndTitleSearch {
꼼꼼한 테스트 지립니다 👍

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +                .isEqualTo(Collections.emptyList());
위의 코멘트와 동일합니다!!

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +            .isEqualTo(Collections.emptyList());
위의 코멘트와 동일합니다!!

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
조회 결과가 없는 케이스에 대한 테스트도 있으면 좋을 것 같아요 😊

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/ui/SongSearchControllerTest.java
> +        final Song saved1 = songRepository.save(
💬 변수명이 saved1 인 이유가 궁금합니다!!

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/ui/SongSearchControllerTest.java
> +            .getList(".", SearchedSongResponse.class);
와우~~ 배워갑니다!! 👍

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/ui/SongSearchControllerTest.java
> +            .toList();
위의 코멘드와 동일합니다!!

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/ui/SongSearchControllerTest.java
> +        final Song saved2 = songRepository.save(new Song("Super Shy", "비디오URL", "뉴진스", 20));
위의 코멘트와 동일합니다!!

2023-07-29 09:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/ui/SongSearchControllerTest.java
> +            .isEqualTo(Collections.emptyList());
위의 코멘트와 동일합니다!

2023-07-30 06:56 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/SongSearchController.java
> +        @RequestParam(required = false, name = "title") String title
오마이갓,,, 추가할게용 감사합니다

2023-07-30 07:19 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/SongSearchService.java
> +        return toSearchResponse(songs);
> 사실상 쓰이지 않는 로직이 존재하고 처리하려는 목적이 같은 로직이 중복 되어있는 것 같다는 생각이 개인적으로는 들었습니다~

맞아요 ㅋㅋㅋㅋ 스플릿이 아래에 넣어주신 코드의 흐름이 정확합니다 ㅎ.ㅎ 
처음에 `findAllByTitle` 과 `findAllBySinger` 를 public으로 두었다가 나중에 private으로 바꾸면서 아무 생각 없이 작성한 것 같아요 😅 

짱짱 👍 🦖

2023-07-30 07:19 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +    );
휴,, 누가 옆에서 도와줬는지 참~ 💯

2023-07-30 07:20 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +    );
그 와중에 위에 코드들은 namedParameter 적용 안한걸 지금 봤네용 머쓱 ㅎㅎ

2023-07-30 07:31 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +        @ValueSource(strings = {"   redvelvet ", "	Redvelvet\n"})
자화자찬인가용 ?.? 💯 💯 💯

2023-07-30 10:19 UTC, Cyma-s requested changes
스플릿이 다 남겨서 딱히 남길 게 없었네요 ㅋㅋㅋ
수고 많으셨습니다 테스트 완전 꼼꼼하네요 👏👏👏👏

2023-07-30 10:19 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/dto/SearchedSongResponse.java
> +    private String albumImage;
💬 앨범 재킷 이미지 URL 네이밍에 대해 통일하는 과정을 거쳐야 할 것 같아요~! 같이 모여서 정해보죠 ㅎㅎ

2023-07-30 10:19 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/dto/SearchedSongResponse.java
> +    private Integer length;
`SongResponse` 에는 정수 값이 원시 타입으로 선언되어 있는데, 이 필드는 wrapper 타입으로 설정되어 있네요 
특별한 이유가 없다면 한 가지로 통일하는 게 좋지 않을까요?! 😄

2023-07-30 10:19 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +    );
훈훈하네요 👯

2023-07-30 10:19 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/ui/SongSearchControllerTest.java
> +            .getList(".", SearchedSongResponse.class);
JsonPath 활용 굿이네요 👍

2023-07-30 14:54 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +            final Song saved2 = songRepository.save(new Song("아무노래", "비디오URL", "RedVelvet", 180));
원래는 상수로 `SAVED_SONG` 이 있는 상태로 테스트 코드를 작성했어서 두 번째 곡을 의미하는 `saved2` 로 지정했었는데, 지금 보니 `SAVED_SONG`을 삭제했었나봐요 😓 😓 

전반적으로 테스트 코드에서 변수명을 수정해야겠어요 👍

2023-07-30 14:58 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +                .toList();
그렇게 작성할 수 있다는걸 잊고 있었다는게 이유입니다 ㅎ.ㅎ .....

좋은 피드백 감사합니다 😸

2023-07-30 15:11 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/ui/SongSearchControllerTest.java
> +        final Song saved1 = songRepository.save(
변수명에서 의미가 더 잘 드러나게 `song` 과 같은 네이밍으로 변경하고 있습니당 ㅎ.ㅎ

2023-07-30 15:17 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/ui/SongSearchControllerTest.java
> +            .isEqualTo(Collections.emptyList());
모든 부분에 코멘트를 달아주셔서 진심으로 감동했습니다,,, 🥲 🥲 

무지성 테스트 코드에 대해 반성하고 있어요 🙇‍♀️

2023-07-30 15:18 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/dto/SearchedSongResponse.java
> +    private String albumImage;
좋습니다~~~!!!!!!!

2023-07-30 15:18 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/dto/SearchedSongResponse.java
> +    private Integer length;
지난번 코드리뷰 때 제가 primitive를 쓰자는 코멘트를 남겨놓고, 또 제가 wrapper를 사용했네요... 😓 💦  

변경하겠습니다 감사합니다 ㅎ.ㅎ

2023-07-30 15:19 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/ui/SongSearchControllerTest.java
> +            .getList(".", SearchedSongResponse.class);
영광이에요 🙇‍♀️

2023-07-30 15:20 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/application/SongSearchServiceTest.java
> +                .isEqualTo(Collections.emptyList());
너무 좋다고 생각합니다 👍 👍

2023-07-30 15:52 UTC, seokhwan-an reviewed
앞서 스플릿과 베로가 리뷰를 꼼꼼하게 남겨주어서 저는 사소한 리뷰 간단하게 남겼습니다. 코드가 전반적으로 깔끔하고 테스트를 엄청 꼼꼼하게 작성한 점이 최고였습니다. 👍 👍

2023-07-30 15:52 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/dto/SearchedSongResponse.java
> +        );
현재 정적 팩토리 메소드를 활용하고 있는데 `@AllArgsConstructor`가 public으로 열려있는 상태입니다. 이를 private으로 변경해주면 좋을 것 같아요~

2023-07-30 15:52 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/ui/SongSearchController.java
> +        @RequestParam(required = false, name = "title") String title
사소한 거지만 현재 `@RequestParam`의 name과 변수명이 같은데 `@RequestParam`의 name을 생략하는 것은 어떻게 생각하시나요?

2023-07-31 06:23 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/SongSearchController.java
> +        @RequestParam(required = false, name = "title") String title
저도 이 부분을 고민하고 있었어요 ㅎㅎ 좋습니다!

2023-07-31 06:25 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/dto/SearchedSongResponse.java
> +        );
이번에 다같이 이야기해보고 컨벤션으로 정해보면 좋을 것 같은데 어떻게 생각하시나요~?

2023-08-07 11:53 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/dto/SearchedSongResponse.java
> +    private String albumImage;
다른 API 에서 사용하는 네이밍인 `albumCoverUrl` 로 변경하는 건 어떨까요?!

2023-08-07 11:54 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/dto/SearchedSongResponse.java
> +        );
좀 늦었네요 ㅋㅋㅋ ㅜ 내일은 꼭 컨벤션으로 정해봅시다!!!!!

2023-08-07 12:22 UTC, Cyma-s approved these changes
더 이상 수정할 부분은 제 눈에는 안 보이네용 수고하셨씁니다 ~~~!!!!

2023-08-07 12:34 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/SongSearchService.java
> +    }
감사해용 베로짱 👯‍♀️

2023-08-08 14:09 UTC, seokhwan-an approved these changes
저도 코드 리뷰 다시 처음부터 했는데 고칠 부분이 없는 것 같습니다. 코드리뷰 하면서 `@query` 작성하는 것과 `RestAssured` 다루는 법에 대해서 지식을 얻을 수 있었습니다! 😃

2023-08-08 14:09 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/dto/SearchedSongResponse.java
> +        );
이것도 내일 같이 컨벤션으로 정해보죠

2023-10-17 09:10 UTC, closed without merging