Feat/#130 구글 소셜 로그인 구현
woowacourse-teams/2023-shook pull request #157
Opened 2023-07-30 11:12 UTC by seokhwan-an

## 📝작업 내용
구글 oauth를 이용해서 소셜 로그인을 구현했습니다.

## 💬리뷰 참고사항
이번에 코드를 작성하면서 패키지 분리와 역할 책임에 대해서 고민이 많았습니다.

먼저 로그인의 경우 `auth`라는 패키지 내부에 `oauth`와 `jwt`를 나누어서 패키지를 분리 했습니다. 추후에 일반 로그인이 생길 때에도 확장성이 쉽게 이루어 질 수 있다고 생각해서 위와 같이 패키지를 구성했습니다.

현재 TokenProvider에 토큰을 생성하는 것과 검증하는 코드 모두를 가지고 있는데 이는 현재 Token과 관련된 기능이 많지 않아서 현재는 하나의 파일로 관리하고 있는데 Token 검증이 많아지면 그 때 분리하면 될 것 같습니다.

마지막으로 외부 api와 관련된 테스트를 작성하는 것이 어려웠습니다. 이번에 구글로 요청을 보낼 때에는 `restTemplate()`를 이용했고 이를 테스트 하기 위해 `@RestClientTest`를 이용해 보았고 참고 자료는 다음과 같습니다. (참고자료 : https://jojoldu.tistory.com/341) 
외부 api를 이용하는 다른 service의 경우 mock을 이용해 테스트를 진행했습니다. (controller 테스트 역시 WebMvc를 이용해 단위테스트만 진행했습니다.)

테스트와 관련되어서 많은 피드백과 의견을 나주어주시면 감사하겠습니다.

## #️⃣연관된 이슈
close #130

2023-07-31 11:34 UTC, Cyma-s requested changes
남기다보니 엄청 많아졌네요 ㅋㅋㅋ 
어려운 기능 + 처음 해보는 기능 구현하시느라 수고 많으셨습니다 !! 아코짱~

2023-07-31 11:34 UTC, Cyma-s commented on backend/src/test/java/shook/shook/member/domain/NickNameTest.java
> +    @DisplayName("닉네ㅜ의 길이가 100자를 넘을 경우 예외를 던진다.")
💬오타 있어요 ㅋㅋㅋ

2023-07-31 11:34 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/oauth/application/OAuthService.java
> +        return new OAuthResponse(userEmail, null, null);
현재는 member 가 존재할 때만 access token, refresh token 을 생성해주고 있는 것 같네요!
그런데 token이 담긴 response에 null이 들어있는게 저는 좀 어색하게 느껴졌어요. 
로그인 창에서 사용자가 로그인 못하는 건 그럴 수 있다고 이해할 것 같은데, 로그인은 정상적으로 되고 나중에 token 이 필요한 서비스에서 갑자기 진행이 안 되면 안 되는 이유를 이해하지 못할 것 같아서요!

그래서 저는 회원가입 API 로 redirect 를 해주는 방식이 조금 더 나아보입니당 🙂이 부분에 대해서는 다른 팀원들과도 함께 이야기해보죠!

2023-07-31 11:34 UTC, Cyma-s commented on backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
> +        MemberRegisterRequest memberRegisterRequest =
💬사소하긴 한데 ㅋㅋㅋ `final` 이 빠진 것 같아요!

2023-07-31 12:00 UTC, somsom13 commented on backend/src/test/java/shook/shook/auth/oauth/ui/OauthControllerTest.java
> +    @DisplayName("회원이 로그인을 하면 요청결과 200을 반환다.")
💬 200에 반화셨나요 ><

2023-07-31 12:01 UTC, somsom13 commented on backend/src/test/java/shook/shook/auth/oauth/ui/OauthControllerTest.java
> +@WebMvcTest(OauthController.class)
`Service` 의 결과에 따른 상태 코드를 확인하기 위한 `controller` 단위 테스트 좋습니다~~ 👍👍

2023-07-31 12:02 UTC, somsom13 commented on backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
> +    private static Member savedMember;
💬 static한 값은 `SAVED_MEMBER` 로 어떠신가요 ?.? 생각해보니 final이 아니라서 애매한가,, 싶기도 하네요 

아코의 생각이 궁금해요~!

2023-07-31 12:03 UTC, somsom13 commented on backend/src/test/java/shook/shook/member/domain/EmailTest.java
> +    @DisplayName("이메일의 형태가 유효하지 않으면 예외를 던진다.")
👍👍👍👍

2023-07-31 12:04 UTC, somsom13 commented on backend/src/test/resources/application.yml
> +oauth2:
💬 질문입니다 ㅎㅎ

`main/resources/application-test.yml` 에서 테스트 환경에서 사용할 환경을 관리하는 것으로 알고 있는데, oauth와 관련된 설정 정보는 `test` 하의 yml에 기록하신 이유가 있을까요 ?.?

2023-07-31 12:09 UTC, seokhwan-an commented on backend/build.gradle
> +    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
오 글로벌 하게 영어로 가면 좋을 것 같아요!

2023-07-31 12:14 UTC, somsom13 commented on backend/src/main/java/shook/shook/auth/oauth/ui/OauthController.java
> +        }
💬 베로의 코멘트와 비슷한 내용입니다! https://github.com/woowacourse-teams/2023-shook/pull/157#discussion_r1279165599

`accessToken` 과 `refreshToken` 이 null인 경우는 DB에 저장되어 있지 않은 사용자, 즉 새롭게 회원가입이 되어야하는 사용자인 것 같아요!

그래서 `UNAUTHORIZED` response를 보내서 프론트엔드에게 "회원가입이 필요하다~" 를 안내하는 플로우로 생각했는데 맞나요?.?

만약 `UNAUTHORIZED` 를 회원가입이 필요한 상태코드로 사용하려 하신게 맞다면 Service의 `login` 메서드에서 null이 들어간 객체를 반환하는 대신, `회원가입 필요 예외` 를 발생시키고 이를 exception handler에서 처리하는 방식은 어떨까 싶어요! 

그러면 상태 코드를 사용해 상황을 판단하는 지금의 코드 방식을 유지하면서 Response에 null이 들어가지 않도록 구성할 수 있을 것 같아요.

물론 이렇게 되면 회원가입이 필요한 상황이 예외 상황으로 처리되는 것 처럼 보이기 때문에 회원가입으로의 redirect가 가능하다면, 해당 방법이 좋다고 생각합니다 ㅎ.ㅎ

2023-07-31 12:16 UTC, somsom13 commented on backend/src/main/java/shook/shook/auth/oauth/application/OAuthService.java
> +        return new OAuthResponse(userEmail, null, null);
저도 null이 들어있는게 어색하게 느껴진다는 베로의 코멘트에 공감합니다~! 
관련된 코멘트를 `OAuthController` 에 남겨서 같이 보면 좋을 것 같아요!

2023-07-31 12:24 UTC, splitCoding reviewed
코드량..... 진짜 고생많았습니다 아코 👍

2023-07-31 12:24 UTC, splitCoding commented on backend/src/test/java/shook/shook/auth/jwt/application/TokenProviderTest.java
> +    @DisplayName("올바르지 않는 token을 parsing하면 에러를 발생한다.")
올바르지 않은 token의 경우가 두 가지일 것 같아요!! ( 저희가 발급을 하지 않은 token, 만료된 토큰 )

만료된 토큰에 대한 테스트도 있으면 좋을 것 같아요!!😁

2023-08-07 06:20 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +    private Key secretKey;
저도 secretkey가 token을 생성하고 디코딩하는데 중요한 역할을 한다고 생각합니다. 그래서 리뷰와 같이 바뀌면 안되는 것이라 생각을 해서 생성자에서 생성되게 수정하고 재할당 받지 못하게 수정했습니다.

2023-08-07 06:27 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +    private Key secretKey;
저도 secretKey가 변경되지 않게 하기 위해서 secretKey를 생성자에서 생성되게 수정했고 final로 재할당 받지 못하게 수정했습니다.

2023-08-07 06:39 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +    }
저도 스플릿 리뷰처럼 secretKey를 생성자에서 생성되게 구성하고 secretKey를 재할당 받지 못하도록 수정했습니다. 꼼꼼한 리뷰 감사합니다:) 😃

2023-08-07 11:03 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/dto/GoogleAccessTokenResponse.java
> +    private String access_token;
코드 짤때 깜박하고 수행하지 못했네요😅

2023-08-07 11:05 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/GoogleInfoProvider.java
> +    public ResponseEntity<GoogleMemberInfoResponse> getMemberInfo(final String accessToken) {
이 부분 생각하지도 못했던 부분인데 감사합니다:) 이렇게 하면 코드내에서 가독성이 좋아질 것 같습니다!!👍👍

2023-08-07 11:40 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/GoogleInfoProvider.java
> +                GoogleMemberInfoResponse.class);
이 부분에 대해서 너무 쉽게 생각하고 동작되는 것에 집중을 하다보니 그 부분에 대해서 생각하지 못했던 것 같습니다. 스플릿 말처럼 accessToken은 민감한 정보여서 header로 감춰서 보내는 것이 좋을 것 같습니다. 보안적인 리뷰 감사합니다! 👍 👍

2023-08-07 14:31 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +    public String createAccessToken(final Long userId) {
그 생각까지 깊게 해보지 못했던 거 같은데요 바론 말대로 파라미터는 원시타입으로 받는 것이 좋을 것 같아요 👍

2023-08-07 15:31 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/dto/OAuthResponse.java
> +    private String email;
말해주신 것처럼 구글 로그인을 시도하더라도 바로 로그인이 되는 것이 아닌 우리 서비스에 가입이 필요한 경우가 있고 이 때에는 회원 가입이 이루어져야합니다. 회원 가입 시 이메일과 닉네임을 모두 받아야 하는 상황이어서 회원가입 요청과 함께 이메일을 반환하게 했습니다.

2023-08-07 15:32 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/OAuthService.java
> +            .getMemberInfo(Objects.requireNonNull(accessTokenResponse.getBody()).getAccess_token());
이 부분에 저도 동의합니다! 꼼꼼한 리뷰 감사합니다:) 👍👍

2023-08-07 16:29 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/member/application/dto/MemberRegisterRequest.java
> +    private String nickName;
여태까지 두 단어 인줄 알았네요 한 단어로 수정하겠습니다:)

2023-08-07 16:52 UTC, seokhwan-an commented on backend/src/test/resources/application.yml
> +oauth2:
oauth를 mock으로 테스트를 하더라고 환경변수 값이 설정되어 있지 않으면 bean 등록이 되지 않아 `@SpringBootTest`를 하는 곳에서 에러가 발생해 이를 test yml에도 넣어 두었습니다!

2023-08-07 17:00 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/OAuthService.java
> +            final String refreshToken = OAuthService.this.tokenProvider.createRefreshToken(
intellij 자동완성에서 붙은 것 같습니다. 이 부분 수정하겠습니다!

2023-08-07 17:11 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/GoogleInfoProvider.java
> +            throw new OAuthException.InvalidAccessTokenException();
1. 분리를 하게 된 이유는 `access_token`이 잘못된 경우에는 4XX 에러가 발생하는데 `verified_email`이 false인 경우는 예외는 일단` RestTemplate` 요청에 대한 응답이 올바르게 동작한 후에 파악이 가능하여 분리했습니다.
2. `verified_email` 이 false가 나오는 경우는 사용자의 이메일 주소가 구글에 의해 검증되지 않는 경우라고 합니다. 이는 구글 계정의 이메일 주소가 사용자의 실제 소유인지 파악되지 않는 경우나 사용자가 이메일 주소 확인 절차를 완료하지 않는 상황이라고 합니다. 그래서 이 부분은 어떻게 처리해야할지 고민이 되지만 이 부분은 일단 예외처리를 하게 했는데 다시 생각해보면  false로 반환값이 왔다고 해서 우리 서비스에서 처리할 수 있는 방법이 따로 없는 것 같기도 합니다.

2023-08-07 17:13 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/GoogleInfoProvider.java
> +            }
verified_email 이 false가 나오는 경우는 사용자의 이메일 주소가 구글에 의해 검증되지 않는 경우라고 합니다. 이는 구글 계정의 이메일 주소가 사용자의 실제 소유인지 파악되지 않는 경우나 사용자가 이메일 주소 확인 절차를 완료하지 않는 상황이라고 합니다. 그래서 그 당시에 이 부분은 어떻게 처리해야할지 고민이 되었고 일단 예외처리를 했는데 다시 생각해보면 false로 반환값이 왔다고 해서 우리 서비스에서 처리할 수 있는 방법이 따로 없는 것 같기도 합니다.

2023-08-07 17:14 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/GoogleInfoProvider.java
> +            }
이 부분은 팀원들과 상의해서 처리하면 좋을 것 같습니다.

2023-08-07 17:14 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/GoogleInfoProvider.java
> +            throw new OAuthException.InvalidAccessTokenException();
이 부분은 팀원들과 상의해서 처리하면 좋을 것 같습니다.

2023-08-07 17:16 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/member/domain/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long> {
확인했습니다!

2023-08-07 17:17 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +            return claims.getExpiration().after(now);
이 부분 수정과정에서 validateToken으로 처리되면 따로 이용되지 않을 것 같습니다. 그래도 꼼꼼한 리뷰 감사합니다:) 👍👍

2023-08-07 17:27 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +        } catch (ExpiredJwtException e) {
처음에는 토근 기간이 만료되면 refreshToken을 요청하는 응답을 보내는 flag로 이용하기 위해서 boolean 값을 반환하게 하려고 했는데 이를 에외를 발생 시켜서 token 요청 api로 리다이렉트 하는 것이 더 좋은 방안인 것 같습니다:)

2023-08-08 10:39 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +                .getBody();
이 부분은 테스트를 위해서 이용했었는데 위의 토큰 기간을 검증하는 메소드와 하나로 구성할 수 있을 것 같습니다!

2023-08-08 11:44 UTC, hong-sile commented on backend/src/main/java/shook/shook/auth/oauth/application/dto/GoogleAccessTokenResponse.java
> +    private String access_token;
카멜로 해주세요

2023-08-08 12:34 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/member/application/MemberService.java
> +    }
저도 그렇게 생각합니다 굳이 불필요한 변수를 생성할 필요가 없을 것 같아요!

2023-08-08 12:47 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/member/application/MemberService.java
> +}
이 부분을 따로 분리한 이유는 현재 이 부분이 OAuthService에서 이용되고 있어서 입니다. 또한 이 메소드는 일반 로그인이 생기더라도 토큰이 발급될 때 이용될 수 있다고 생각하여 중복되는 코드를 방지하고자 분리하는 것이 좋을 것 같습니다.

2023-08-08 12:50 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/auth/jwt/application/TokenProviderTest.java
> +        tokenProvider.generateSecretKey();
현재 `validateTokenExpiration`와 `parseClaim` 두 메소드에서 공통으로 처리하는 부분이 있는데 이를 하나의 메소드인 `validateToken`으로 수정할 계획입니다. 그 이유는 catch를 여러개 이용해서 잡으면 만료기간 에러와 잘못된 토큰을 모두 파악할 수 있어서 입니다.😃

2023-08-08 12:56 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/auth/oauth/application/OAuthServiceTest.java
> +
저도 리뷰 주신 것이 더 가독성이 좋은 것 같아요!!

2023-08-08 12:56 UTC, seokhwan-an commented on backend/src/main/resources/schema.sql
> +    email     varchar(100) not null,
이 부분은 팀원들과 함께 논의를 해봐야 할 것 같아요!

2023-08-08 12:57 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/OAuthService.java
> +        return new OAuthResponse(userEmail, null, null);
이 부분도 팀원들과 함께 이야기 해보아요😃

2023-08-08 13:01 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/auth/oauth/application/OAuthServiceTest.java
> +        assertThat(result.getRefreshToken()).isNotNull();
저는 개인적으로 3개정도는 각각 비교하는 것을 선호하고 5개 이상으로 넘어가는 경우에는 `usingRecursive`를 선호하는 편인데 바론은 대부분 `assertAll`을 이용하는 편이신가요?? ☺️

2023-08-08 13:06 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/ui/OauthController.java
> +        }
저도 그 방안이 더 깔끔한 것 같은데 팀원들과 한번 이야기 하고 이 부분은 수정하겠습니다!

2023-08-08 13:09 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +        } catch (ExpiredJwtException e) {
다시 보니 그 부분은 동작하지 않는 코드네요 이 부분은 밑의 `parseClaim`과 중복되는 코드가 많아서 이 두 메소드를 `validateToken`이라는 하나의 메소드로 관리하려고 합니다. 꼼꼼한 리뷰 감사합니다☺️

2023-08-08 13:10 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +                .parseClaimsJws(token)
위의 내용과 같이 하나의 메소드에서 스플릿이 말해준 예외를 처리하도록 수정하겠습니다:)

2023-08-08 13:16 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +@Service
처음에 하나의 파일에서 Oauth를 작성하고 이를 책임 분배를 하면서 파일을 분리했었습니다. 그래서 저는 토큰을 생성하는 것도 Oauth에서 핵심기능이라고 생각을 했어서 `@Service`를 붙였는데 모든 팀원들의 리뷰에 `@Component`를 더 선호하는 것 같습니다. `@Component`로 수정하겠습니다!

2023-08-08 13:18 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/GoogleInfoProvider.java
> +        }
처음에 이부분을 4XX에러와 5XX 에러를 분리하지 못한다고 생각해서 구글 서비스는 해피케이스로 에러가 발생하지 않는다고 생각하고 RestClientException이 발생하면 잘못된 accessToken 이라고 예외를 처리할려고 했었습니다. 근데 이 부분은 제가 예외처리에 대해 잘못 생각한 부분이라고 생각하고 이를 분리해서 예외를 처리하도록 수정했습니다!

2023-08-08 13:19 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/GoogleInfoProvider.java
> +@Service
여기도 위의 응답과 마찬가지로 핵심기능이라고 생각해서 `@Service`를 붙였는데 이 부분은 `@Component`로 수정하겠습니다.

2023-08-08 13:21 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/auth/jwt/application/TokenProviderTest.java
> +    @DisplayName("올바르지 않는 token을 parsing하면 에러를 발생한다.")
이 부분 테스트 추가하겠습니다.

2023-08-08 13:33 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +            return claims.getExpiration().after(now);
스플릿 말대로 비교하는 순간에 시점을 파악하는 것이 더 좋을 것 같습니다.

2023-08-08 13:34 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
> +            return claims.getExpiration().after(now);
이 부분 하나의 메소드로 합쳐지면서 불필요하게 되었습니다.

2023-08-08 13:36 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
> +    private static Member savedMember;
사실 크게 고민을 하지 않은 부분이었는데 저도 애매하네요.. 일단은 다른 팀원들은 어떻게 생각하는지 들어보고 처리하겠습니다:) 꼼꼼한 리뷰 감사합니다!☺️

2023-08-09 05:21 UTC, somsom13 approved these changes
소소한 부분 2개에만 코멘트 남겼습니다~ 나중에 반영해주셔도 될 것 같아요! 고생하셨습니다 👍

2023-08-09 05:21 UTC, somsom13 commented on backend/src/main/java/shook/shook/auth/oauth/application/OAuthService.java
> +        final Long memberId = member.getId();
primitive로 통일하기로 했던 것 같아요! (nullable하지 않은 경우에!)

2023-08-09 05:22 UTC, splitCoding approved these changes
수고가 많아요~ 소소한 부분 0개에 코멘트 남겼습니다~ 나중에 반영해주셔도 될 것 같아요! 고생하셨습니다! 1뿌직 드려요

2023-08-09 05:30 UTC, Cyma-s approved these changes
어려운 소셜 로그인 수고 많으셨습니다!!!!
빠른 머지 가죠 ㅎㅎ

2023-08-09 05:30 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/oauth/application/OAuthService.java
> +            .orElseGet(() -> memberService.register(userEmail));
깔쌈하네요잉  👍👍👍👍👍

2023-08-09 05:30 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/oauth/ui/OauthController.java
> +    @GetMapping("login/google")
이거 작동하는지 아닌지 궁금하네용
```suggestion
    @GetMapping("/login/google")
```

2023-08-09 05:30 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/oauth/ui/OauthController.java
> +    @GetMapping("login/google")
된다고 합니다 😊

2023-08-09 05:30 UTC, Cyma-s commented on backend/src/main/java/shook/shook/member/application/dto/MemberRegisterRequest.java
> +    private String nickname;
nickname 굿

2023-08-09 05:30 UTC, Cyma-s commented on backend/src/main/java/shook/shook/member/domain/Nickname.java
> +    private String value;
`NICKNAME_MAXIMUM_LENGTH`, 나 `NICKNAME_MAXIMUM_LENGTH` 로 바꾸는 건 어떨까용 ~ 😁

2023-08-09 05:34 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/GoogleInfoProvider.java
> +                GRANT_TYPE);
그렇네요 하나씩 하는게 좋을 것 같아요

2023-08-09 05:35 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/oauth/application/OAuthService.java
> +        final Long memberId = member.getId();
맞네요.. 자동 완성으로 만들다 보니 그렇게 된 거 같아요

2023-08-09 05:37 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/member/domain/Nickname.java
> +    private String value;
아 그렇네요 제가 수정할 때 놓쳤네요

2023-08-09 05:57 UTC, merged