feat: 총 득표수가 높은 상위 40개 노래 목록 조회 기능 구현
woowacourse-teams/2023-shook pull request #159
Opened 2023-07-30 17:01 UTC by splitCoding

## 📝작업 내용

득표수가 높은 상위 40개의 노래 목록을 조회한다.
- 득표 수가 같을 경우 최신 등록 노래 순으로 정렬한다.

## 💬리뷰 참고사항

Controller 테스트의 격리를 위해서 @Sql 을 사용하여 진행했습니다.

각 노래과 총 득표 수만 조회하기 위해 JPQL 을 사용하였습니다

## #️⃣연관된 이슈

close #144

2023-07-31 04:55 UTC, Cyma-s requested changes
이번 스프린트에서 중요한 기능인데 빠르게 구현해주셨네용 수고 많으셨어요~~
스플릿 zzang zzang

2023-07-31 04:55 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +            .sorted((o1, o2) -> {
o1, o2보다는 firstSong, secondSong 같이 명확하게 표현해주면 좋지 않을까요?! 😆

2023-07-31 04:55 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +    List<SongTotalVoteCountDto> findSongWithTotalVoteCount();
오 Query 직접 짜셨군요 ㄷㄷ 👍

2023-07-31 04:55 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/SongTotalVoteCountDto.java
> +public class SongTotalVoteCountDto {
오 dto projection 적용해주셨군요 👍
보통 dto projection은 인터페이스로 구현한다고 알고 있었는데, 혹시 class projection을 사용하신 이유가 있으실까요?!

2023-07-31 04:55 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/HighVotedSongController.java
> +@RestController
💬가장 관련있는 어노테이션이 하단으로 가는 건 어떨까용 😄

2023-07-31 04:55 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/HighVotedSongController.java
> +        final List<HighVotedSongResponse> response = songService.findHighVotedSongs();
💬사소하지만 `showHighVotedSongs` 라는 이름은 어떨까용 service의 메서드 이름이 `findHighVotedSongs` 라서 제안드립니당 ☺️

2023-07-31 06:19 UTC, somsom13 requested changes
코드랑 구현 속도 둘 다 대박이네용 👍 🦖 🌮 🎉 
100점 드리고 갑니다~!

2023-07-31 06:19 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/application/SongServiceTest.java
> +            })
💬 높은 득표수 & 동일 득표수인 경우 최신순으로 정렬이 잘 되는지를 확인하는 테스트인 것 같아요!

현재 파트와 투표가 등록된 노래는 두 개 인 것 같은데, 직접 순서대로 만들어서 (ex. `List.of(노래들)`) 로 만들지 않고 여기에서도 stream을 통한 계산 로직을 사용한 이유가 있는지 궁금해요! 😸

2023-07-31 06:19 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
> +        assertThat(totalVotes).usingRecursiveComparison().isEqualTo(expectedTotalVotes);
다른 테스트 코드처럼 한 줄에 하나의 . 이 찍히게 통일하는건 어떨까용 ㅎ.ㅎ

```suggestion
        assertThat(songs).usingRecursiveComparison()
          .isEqualTo(expectedSongs);
        assertThat(totalVotes).usingRecursiveComparison()
          .isEqualTo(expectedTotalVotes);
```

2023-07-31 06:19 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/ui/HighVotedSongControllerTest.java
> +@Sql("classpath:/test.sql")
데이터 삽입 전에 drop 좋네용 👍 

저도 sql 어노테이션 사용해야겠어요 ㅎ.ㅎ

2023-07-31 06:19 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/ui/HighVotedSongControllerTest.java
> +    private SongService songService;
💬  이전에 controller단의 통합테스트 시, service를 사용하지 않고 repository를 사용했던 걸로 기억해요!

이번 테스트에서는 service를 주입받아서 사용한 이유가 궁금해요~!

2023-07-31 06:19 UTC, seokhwan-an requested changes
많은 고민을 하면서 코드를 작성한 것이 느껴져서 좋았습니다. 리뷰 남겼는데 확인 부탁드립니다.

2023-07-31 06:19 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
> +        assertThat(totalVotes).usingRecursiveComparison().isEqualTo(expectedTotalVotes);
여기도 위와 같은 리뷰 입니다!

2023-07-31 06:19 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +            .toList();
현재 노래의 목록을 나타내는 부분이 등록된 파트가 많은 순으로 노래를 보여주는 것 밖에는 없지만 추후에 노래의 장르별로 보여주는 것이나 혹은 또다른 기준으로 노래목록을 보여주는 것에서도 이 기능이 이용될 수 있을 것 같은데 이 부분을 따로 메소드로 분리를 해보는 것 어떤가요?

2023-07-31 09:13 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/SongTotalVoteCountDto.java
> +public class SongTotalVoteCountDto {
제가 사용한게 dto projection 이였군요..??

JPQL 을 처음 써봐서 학습과 검색을 통해 나온 결과였습니다..ㅎㅎ

찾아보니 interface로도 사용할 수 있더군요! 

궁금해서 찍어보니 아니나 다를까 이 놈 프록시 였군요

<img width="927" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/75476562/a912edf2-3811-4814-b7f3-40e151ee54af">

근데 혹시 interface projection 을 사용해야 하는 이유가 있는지 궁급합니다~ 😄

2023-07-31 09:18 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/ui/HighVotedSongController.java
> +        final List<HighVotedSongResponse> response = songService.findHighVotedSongs();
저도 두 메서드의 이름이 같은 것에서 가독성 상의 매우 좋은 장점을 가진다고 생각합니다!! 👍

제가 저렇게 네이밍했던 이유는 presentation 레이어에서는 사용자와의 interaction을 생각해서 show 라는 단어를 application 레이어인 service 에서는 순수 기능을 생각한 find 라는 단어를 이용했습니다!! 😊

2023-07-31 09:26 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/ui/HighVotedSongControllerTest.java
> +    private SongService songService;
SongControllerTest 에서는 검증을 위해 호출되는 sevice 메서드가 단순 싱크홀 패턴의 메서드라서 repository를 사용했었습니다!!

하지만 이번에 검증을 위해서 호출되어야하는 비즈니스 로직들이 많아서 작성 편의성을 위해서 service 레이어의 메서드를 직접 사용했습니다!!

---

테스트 코드 자체의 독립성을 위해 Repository를 사용하는 방식으로 리팩토링 하면 좋을 것 같습니다!! 😊 ( 추후 리팩토링 예정 )

2023-07-31 09:32 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/application/dto/HighVotedSongResponse.java
> +    }
우선 정팩메로 생성한 이유는 여러개의 노래를 맵핑하기 위해서 사용되는 코드의 중복을 해결하고자 하는 게 제일 컸습니다!!

그리고 개인적으로 비즈니스 로직이 없는 단순 맵핑을 위한 책임을 serive 레이어보다는 사용되는 맵핑 로직을 가지고 있는 HighVotedSongResponse 에 있는 것이 더 좋다고 생각했습니다!! 😄

---

저도 네이밍 부분에서 똑같은 고민을 했는데 완전 만족할 만한 네이밍이 떠오르지 않아😭 우선은 제일 직관적인 네이밍을 사용했습니다. 😄

2023-07-31 09:36 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongServiceTest.java
> +            })
지금 더미 데이터가 40개 있는 상황에서 이루어진 테스트여서 반환되는 모든 40개의 순서를 비교하기 위해서 해당 로직을 사용했습니다!! 😄

DisplayName에 더미 데이터 40개에 대한 언급을 추가하도록 하겠습니다!👍

2023-07-31 09:37 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/application/SongService.java
네

2023-07-31 09:38 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/application/dto/HighVotedSongResponse.java
> +    }
알겠습니다

2023-07-31 09:39 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +    @Query("SELECT NEW shook.shook.song.domain.SongTotalVoteCountDto(s, COUNT(v)) FROM Song s LEFT JOIN s.parts.parts p LEFT JOIN p.votes v GROUP BY s.id")
class projection 사용시 앞에 패키지 경로를 빼면 작동을 하지 않습니다

2023-07-31 09:43 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +            .toList();
개인적으로 나중에 다른 기준으로 노래목록을 보여주는 기능에서는 비교 대상에 따라 compareTo 에서 사용될 타입이 달라짐에 따라 재사용은 힘들 것 같습니다!! 🧐

그저 메서드의 흐름이 길어서 해당 부분을 분리하는 것에는 동의합니다!! 😁

2023-07-31 09:50 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/SongServiceTest.java
> +            .isEqualTo(expectedResponses.subList(0, 40));
아코 말대로 given 절에 위치함으로 얻을 수 있는 장점도 있다고 생각합니다!! 😄

개인적으로 기대결과 값을 생성할 경우에는 then 아래에 두는 것을 선호합니다!!

현재 코드가 포함된 테스트 메서드의 경우 코드가 꽤 여러 줄 존재하는 메서드입니다. 

개인적으로 예상 검증 값이 given 절에 있을 경우 메서드의 처음으로 다시 올라가서 봐야한다는 점이 개인적으로 불편하더라구요~ 😊

그래서 저는 한번에 파악할 수 있도록 예측 검증 값을 가진 변수와 검증 로직이 같이 then 절에 있는 것을 선호합니다!!

2023-07-31 10:10 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/SongTotalVoteCountDto.java
> 💬 이 DTO가 Repository에서 조회해올 때 쓰이는 객체라 domain 패키지 내에 들어있다고 생각했는데, 그 이유가 맞을까요?.?

넵 맞습니다!!

> 그렇다면 혹시 repository 패키지 내에 넣지 않고, domain 하위에 두신 이유가 궁금해요!
 
 SongRepository 가 반환한 SongTotalVoteCountDto 또한 그저 값을 전달하기 보다는 내부적으로 노래와 총 득표 수를 계산해야하는 작은 도메인을 위한 도메인 객체라고 생각하여 domain 하위에 두었습니다!!
 
Dto라는 네이밍을 포함하여 생각하면 저도 domain 하위에 있는 것이 잘 이해가 되지 않는 것 같습니다..😭

또한 상위에 있는 리뷰

https://github.com/woowacourse-teams/2023-shook/pull/159#discussion_r1278789782 

를 통해서 interface 로 선언하고 getter만 열어놨으니 오히려 순수 dto의 성향이 더욱 짖어 진 것 같네요 😊

repository 하위 dto 패키지로 이동하는 것이 더 합리적으로 보입니다!!👍

2023-07-31 10:45 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +    @Query("SELECT NEW shook.shook.song.domain.SongTotalVoteCountDto(s, COUNT(v)) FROM Song s LEFT JOIN s.parts.parts p LEFT JOIN p.votes v GROUP BY s.id")
처음 알았습니다 class projection에 대해 잘 알지 못해서 잘못된 리뷰를 남겼네요..

2023-07-31 11:27 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/ui/HighVotedSongControllerTest.java
> +    private SongService songService;
🆒

2023-07-31 11:37 UTC, somsom13 approved these changes
최최최고네요

진짜 간단한 개행 관련 코멘트만 하나 있고, 나머지는 다 멋지다는 내용입니다 ^.^

고생하셨어요~~~~~ 🦖 🌮 🎉 👍

2023-07-31 11:37 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/Song.java
> +        final String singer, final int length) {
멋지군요.. 고생하셨습니다.... 엄청 간단한 리뷰가 하나 있는데, 

![image](https://github.com/woowacourse-teams/2023-shook/assets/70891072/62485ae1-d1f5-411f-9436-d7ad630d1d4b)

[백엔드 코드 컨벤션](https://github.com/woowacourse-teams/2023-shook/wiki/%EB%B0%B1%EC%97%94%EB%93%9C-%EC%BD%94%EB%93%9C-%EC%BB%A8%EB%B2%A4%EC%85%98#entity) 에서 "엔티티의 생성자 매개변수가 한 줄이 넘어가면, 모든 변수에 개행을 적용한다" 라고 정했더라구요!

이것만 반영해주시면 정말 최고일 것 같습니다 🦖

2023-07-31 11:37 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +    @Query("SELECT s AS song, COUNT(v) AS totalVoteCount FROM Song s LEFT JOIN s.parts.parts p LEFT JOIN p.votes v GROUP BY s.id")
COOL... 🆒

2023-07-31 11:37 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/repository/dto/SongTotalVoteCountDto.java
> +
Awsome... 😎  이렇게도 되는군요 배워갑니닷

2023-07-31 11:37 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/application/SongServiceTest.java
> +    @DisplayName("총 득표수가 높은 순서로 노래 목록을 반환한다. ( 최대 40개를 반환, 같은 득표시 최신등록 순으로 정렬, 노래 40개 존재 )")
👍 👍

2023-07-31 12:24 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/SongTotalVoteCountDto.java
> +public class SongTotalVoteCountDto {
꼭 Interface projection 을 사용해야 하는 것은 아닙니다! class projection, interface projection 모두 동일한 기능을 수행하며, 성능 차이도 크게 없는 것으로 압니다.

interface projection 은 다음과 같은 부분에서 이점을 갖습니다. 보통 가독성 측면의 장점이 많은 것 같아요.

- 단순합니다. (개인적으로 가장 장점이라 생각합니다) 원하는 필드에 해당하는 getter 메서드로 인터페이스를 선언하기만 하면 Spring Data 가 알아서 처리해줍니다.
- 생성자가 필요없습니다. 그렇지만 이 부분은 lombok 을 쓰면 되니 class projection 에 비해 큰 장점이라고 하기는 어렵겠네요.
- 현재 dto projection으로 가져오는 데이터가 단순한 평면 구조의 데이터이고, 클래스 내부에서 추가 가공이 이루어지지 않기 때문에 굳이 class projection 을 사용하지 않아도 될 듯 합니다.
    - 중첩된 DTO가 있는 복잡한 데이터 구조가 필요하거나, DTO 생성자에서 계산을 수행하는 경우에는 class projection이 좋은 선택이 될 수도 있다고 하네요 ˙ᵕ˙ 

이런 점들로 미루어보아, interface projection을 사용하는 것이 지금 상황에서는 좋아보입니다 😄

2023-07-31 12:27 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/HighVotedSongController.java
> +        final List<HighVotedSongResponse> response = songService.findHighVotedSongs();
앗 뭔가 잘못 전달된 것 같네요 ㅋㅋㅋ service 의 메서드 이름도 복수로 써주면 좋을 것 같다는 의견이었습니다 😁

2023-07-31 12:33 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +    @Query("SELECT NEW shook.shook.song.domain.SongTotalVoteCountDto(s, COUNT(v)) FROM Song s LEFT JOIN s.parts.parts p LEFT JOIN p.votes v GROUP BY s.id")
이 부분도 class projection의 단점이 될 수 있겠네요 
interface 는 경로를 안 적어줘도 돼서 좋아요

2023-07-31 12:48 UTC, Cyma-s approved these changes
수정할 부분은 더 이상 없는 것 같네요!
image url 고치느라 수고 많으셨습니다 😂👍

2023-07-31 12:48 UTC, Cyma-s commented on backend/src/main/resources/data.sql
> +INSERT INTO song (title, singer, length, video_url, image_url, created_at)
고생하셨네요 진짜... ㅋㅋㅋㅋㅋㅋㅋ

2023-07-31 16:29 UTC, seokhwan-an approved these changes
제 리뷰에 대한 스플릿의 의견과 추가된 수정사항을 다 확인해 보았는데 더 이상 수정할 부분이 없는 것 같습니다. 몸상태도 좋지 않은 상태에서도 리뷰를 빠르게 반영해 주셨네요 고생 많으셨습니다.🙇‍🙇‍

2023-07-31 16:29 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +    @Query("SELECT s AS song, COUNT(v) AS totalVoteCount FROM Song s LEFT JOIN s.parts.parts p LEFT JOIN p.votes v GROUP BY s.id")
이 부분을 새롭게 배워갑니다 👍👍

2023-08-01 01:28 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/SongTotalVoteCountDto.java
> +public class SongTotalVoteCountDto {
interface projection 바로 도입했습니다~ 😊

2023-08-01 01:29 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/ui/HighVotedSongController.java
> +        final List<HighVotedSongResponse> response = songService.findHighVotedSongs();
아!! 😱 바로 적용하겠습니다!!😁

2023-08-01 01:52 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/HighVotedSongController.java
> +        final List<HighVotedSongResponse> response = songService.findHighVotedSongs();
예예 맞습니다~ 😆

2023-08-01 06:12 UTC, merged