Feat/#166 메인페이지에서 킬링파트 등록 인기순 음악을 보여준다
woowacourse-teams/2023-shook pull request #175
Opened 2023-08-01 10:56 UTC by cruelladevil

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명(이미지 첨부 가능)

- 메인페이지에서 킬링파트 등록 인기순 노래를 보여줍니다.
  - SongPopularPage
  - SongRankCard - 등록 인기순 목록에서 하나의 음악 컴포넌트입니다.
  - Thumbnail - 이미지를 불러오기 전, 크기를 강제하기 위해 div로 한 번 감쌌습니다.

## 💬리뷰 참고사항

> 원활한 리뷰를 위해 전달하고 싶은 맥락(특정 파일, 디렉터리 등등)  
> 리뷰어가 특별히 봐주었으면 하는 부분

- [웹 접근성] : SongRankCard 탭하면 -> `방문함, 링크, 킬링파트 인기순 {n}등 {가수} {제목}`
- **[백엔드 미구현]** - figma 시안상으로 votes 정보가 있어 컴포넌트를 구현해놓았지만 API 명세에 없기 때문에 현재 주석처리

1. 웹 접근성이 충분한지 검토해주세요.
2. SongRankCard를 일단 이름을 깊이 고민하지 않고 지었기 때문에 이 부분을 한 번 검토해주세요.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #166

2023-08-01 19:01 UTC, Creative-Lee requested changes
고생 많으셨습니다!
코멘트 확인하고 답변 부탁드릴게요~
내용이 얼마 없어서 대면으로 바로 하셔도 좋습니다!

2023-08-02 07:27 UTC, cruelladevil commented on frontend/src/pages/SongPopularPage/SongPopularPage.style.ts
> +  font-weight: 800;
https://developer.mozilla.org/ko/docs/Web/CSS/font-weight

bold의 기본이 700이군요!
폰트와 관련해서 이야기 나눠보면 좋을 것 같습니다.

2023-08-02 07:55 UTC, cruelladevil commented on frontend/src/pages/SongPopularPage/SongPopularPage.style.ts
> +  font-weight: 800;
일단 700으로 수정해놓겠습니다

✍️ 수정 커밋 - 1b5a397

2023-08-02 08:08 UTC, ukkodeveloper approved these changes
고생하셨어요. 컴포넌트가 간단해서 별로 말씀드릴게 없네요. SongRankCard 누를 때 background 분홍생 뜨는 부분 외에는 사소한 커멘트라 바로 approve할게요.

2023-08-02 08:09 UTC, cruelladevil commented on frontend/src/components/SongRankCard/Thumbnail.tsx
> +        style={{ borderRadius: '8px' }}
Wrapper에만 boder-radius를 주려고 했었는데 적용이 제대로 안되어서 테스트하다가 정리가 다 안된 부분이네요!
Wrapper의 overflow에 `hidden`이 아닌 문자열 `'hidden'`으로 들어가 있었던 것이 문제였습니다.
Wrapper에만 적용하고 img에서는 제거하였습니다.

✍️ 수정 커밋 - 1e1950adb17f89d3be7857841362f469db86d9cf

2023-08-02 08:10 UTC, cruelladevil commented on frontend/src/components/SongRankCard/Thumbnail.style.ts
> +  border-radius: 10px;
https://github.com/woowacourse-teams/2023-shook/pull/175#discussion_r1281551581

위와 함께 수정하였습니다.

2023-08-02 08:18 UTC, cruelladevil commented on frontend/src/pages/SongPopularPage/SongPopularPage.style.ts
> +  }
active pseudo class는 `마우스 버튼을 누르는 순간부터 떼는 시점`까지를 나타냅니다.
https://developer.mozilla.org/ko/docs/Web/CSS/:active

> 불필요하고 정신 없게 느껴집니다.. 

라고 느껴진다면 삭제하는 것이 좋을 것 같네요!

✍️ 수정 커밋 - cf679c24e45be1b84bb30dede08d52bf14b00131

2023-08-02 08:19 UTC, cruelladevil commented on frontend/src/components/SongRankCard/SongRankCard.style.ts
> +  display: grid;
grid와 flex는 개인 기호라고 생각하지만 여기서 grid를 적용하면,
template을 통해 어떤 요소가 어떤 위치인지 보기 쉬울 것 같아 적용하였습니다. 😊

2023-08-02 08:25 UTC, cruelladevil commented on frontend/src/components/SongRankCard/Thumbnail.tsx
> +const Thumbnail = ({ ...props }: ThumbnailProps) => {
`const Thumbnail = ({ newProp, anyOtherProp, ...props }: ThumbnailProps) => {`
위처럼 prop이 추가될 상황을 고려하고 작성하였습니다.
`props`와 `{ ...props}`의 차이중 특별히 고려할 사항이 없으면 수정하지 않고 넘어가겠습니다 😊

2023-08-02 08:35 UTC, cruelladevil commented on frontend/src/components/SongRankCard/SongRankCard.style.ts
> +export const Grid = styled.p`
✍️ 수정 커밋 - 2cc5ef8c770f1def73a511eae93ffceddc033ec3

2023-08-02 08:36 UTC, cruelladevil commented on frontend/src/pages/SongPopularPage/SongPopularPage.style.ts
> +export const PopularSongList = styled.section`
목록이라는 점을 고려하지 못하였네요 😨

✍️ 수정 커밋 - 2cc5ef8c770f1def73a511eae93ffceddc033ec3

2023-08-02 08:41 UTC, cruelladevil commented on frontend/src/pages/SongPopularPage/SongPopularPage.tsx
> +    fetcher('/songs/recommended', 'GET')
관리 측면에서 추상화 레이어를 하나 추가하여 api 폴더에 쿼리 함수가 있어야 된다는 의미인건가요?
우리 팀의 query 로직이 부족한 부분이 많아서 이에 대해 정리하는 시간을 한 번 가지면 좋을 것 같아요.

> 관리 측면에서 추상화 레이어를 하나 추가하여 api 폴더에 쿼리 함수가 있어야 된다는 의미인건가요?

이 의도라면 이번 PR에서는 이대로 통과시켜도 될까요?

2023-08-02 11:55 UTC, Creative-Lee commented on frontend/src/pages/SongPopularPage/SongPopularPage.tsx
> +    fetcher('/songs/recommended', 'GET')
넵 맞습니다~ 
도메인이 들어간 실제 통신 로직은 함수로 한번 감싸지고,
그것을 hook에 넣어서 사용하는게 좋겠다고 생각했어요! 

코난 말대로 당장 api 로직이 먼저 수정되어야 할 것 같네요 ㅋㅋ 넘어가시죠!

2023-08-03 03:03 UTC, merged