Fix/#208 댓글 입력시 양쪽 공백 제거
woowacourse-teams/2023-shook pull request #223
Opened 2023-08-08 10:59 UTC by cruelladevil

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명(이미지 첨부 가능)

댓글 입력시 양쪽 공백 제거
ROUTE_PATH 미변경사항 수정

## 💬리뷰 참고사항

> 원활한 리뷰를 위해 전달하고 싶은 맥락(특정 파일, 디렉터리 등등)  
> 리뷰어가 특별히 봐주었으면 하는 부분

#161 - ROUTE_PATH 미변경된 부분이 하나 있어서 수정했습니다. 

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #208 
close #211

2023-08-08 16:36 UTC, Creative-Lee requested changes
바뀐 코드가 거의 없네요!!?!? 혹시 코드가 누락된 부분이 있을까요?

1. 💬 PR 본문 내용에는 uncontrolled 방식으로 변경했다고 하셨는데, 아직 controlled 방식인것 같아요! 

2. 제가 확인해 봤을때는 댓글 post 이후에 input이 초기화 되지 않고있어요!
확인 부탁드립니다~

### 영상

![코난 수정](https://github.com/woowacourse-teams/2023-shook/assets/77152650/82a6f268-96b3-4dad-b4d3-d5afa4110e52)


3. 💬 적어주신 이슈번호를 따라가보면 공백외에도 토스트 UI와 일치하지 않는 부분이 주를 이루는 피드백인것 같아요. 이슈가 따로 생성되어야 할 것 같습니당

2023-08-08 16:36 UTC, Creative-Lee commented on frontend/src/pages/MainPage.tsx
> +              to={`${ROUTE_PATH.SONG_DETAIL}/${id}`}
저도 바로 에러나더군요 ㅋㅋㅋ

2023-08-09 02:12 UTC, cruelladevil commented
@Creative-Lee

**[1번]** 부모로부터 value를 prop으로 받는 Input이 아니기 때문에 uncontrolled입니다.
 
https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components

**[2번]** Input을 초기화하는 문제를 수정하면서 상태를 없애고 ref로 하려했는데,
제출 버튼을 활성화하려면 상태가 꼭 필요하더라구요. 그래서 다시 controlled로 변경하였습니다.
결과물은 기존 코드에서 제출할 때와 제출 버튼의 활성화 여부를 `trim()`으로 평가하도록 하였습니다.

**[3번]** 다른 이슈로 생성해서 해결하는 것에 공감합니다.

2023-08-09 02:38 UTC, ukkodeveloper approved these changes
잘 작동하는 것 확인했습니다. 바로 approve할게요.

2023-08-09 02:39 UTC, Creative-Lee commented
오케이 확인했습니다~ 어프루부용

2023-08-09 02:39 UTC, Creative-Lee approved these changes

2023-08-09 02:40 UTC, merged