Refactor: KillingPart 도메인, 서비스 생성
woowacourse-teams/2023-shook pull request #239
Opened 2023-08-10 09:19 UTC by somsom13

## 📝작업 내용

KillingPart 도메인을 새롭게 생성하고, 이와 연관된 도메인, repository, service, test를 생성했습니다.

작업내용

## 💬리뷰 참고사항

- `KillingPart` 관련 도메인들을 `song > domain > killingpart > repository, domain들` 로 분리했는데 오히려 패키지 구조를 파악하는게 더 어려워진 것 같습니다. 지금 구조가 계층형 패키지 설계와 어떤 차이가 있는지 저는 잘 모르겠어서 다른 분들의 의견이 필요합니다.
- 우선은 기존의 코드들에 변경사항이 없도록 하기 위해서 `Song` 도메인에 연관관계 매핑만 추가했습니다.  `songs/{song_id}` 로 조회하는 부분까지 수정하려면 SongService 등 너무 많은 부분이 수정되어야 해서 이 부분은 변경하지 않았습니다. ++) api가 변경된 상태로 main에 merge되면, 기존의 기능들이 돌아가지 않을 것 같다는 이유도 있습니다 ^__^
- 나름 꼼꼼하게 분리했는데, 놓친 부분이 있을 수 있어서 꼼꼼한 리뷰 부탁드립니다.. ❤️‍🔥 
- **서버 DB에는 아직 `killing_part` 와 `killing_part_comment` 테이블이 없다는 점 유의 부탁드립니다~!** 

## #️⃣연관된 이슈
#237

2023-08-10 13:49 UTC, splitCoding requested changes
바론 고생많았어요!! 👍 

그 때 바론이 말했던 getList() 정펙메의 거슬림을 저도 똑같이 느꼈습니다!! 같이 바꿔요ㅎㅎ

2023-08-10 13:49 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/KillingParts.java
> +        this.killingParts.addAll(new ArrayList<>(killingParts));
validate에서는 참조값을 그대로 사용하고 addAll 에서는 방어적 복사를 사용한 이유가 궁금해요~😊

2023-08-10 13:49 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/KillingParts.java
> +    private final List<KillingPart> killingParts = new ArrayList<>();
KillingParts 객체를 생성한뒤에 list에 killingPart 를 추가하는 로직이 존재하지 않는상황에서 List<KillingParts>가 비어있는 상태에서 KillingParts 가 생성되어야 하는 경우가 언제인지 궁금해요~~ 😊

2023-08-10 13:49 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/KillingParts.java
> +    public KillingParts(final List<KillingPart> killingParts) {
> KillingParts 객체를 생성한뒤에 list에 killingPart 를 추가하는 로직이 존재하지 않는상황에서 List가 비어있는 상태에서 KillingParts 가 생성되어야 하는 경우가 언제인지 궁금해요~~ 😊

위에 리뷰와 연결되는 질문입니다!! 생성자에서 List<KillingPart> 를 받아서 초기화하지않고 addAll하는 이유가 궁금해요 😊

2023-08-10 13:49 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/KillingParts.java
> +    private void validate(final List<KillingPart> killingParts) {
킬링파트가 3개보다 적은 경우에 대한 검증은 존재하지 않는데 킬링파트가 3개보다 적어도 되는 상황이 언제인지 궁금해요~😊

2023-08-10 13:49 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/Song.java
> +
killingParts 에 있는 `@NoArgsConstructor(access = AccessLevel.PROTECTED)` 의 경우 JPA에 때문에 사용했다고 생각했는데 생성자로도 사용하고 계시군요!!

> KillingParts 객체를 생성한뒤에 list에 killingPart 를 추가하는 로직이 존재하지 않는상황에서 List가 비어있는 상태에서 KillingParts 가 생성되어야 하는 경우가 언제인지 궁금해요~~ 😊

위에 리뷰와 동일한 내용입니다!!

2023-08-10 13:49 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
> +    @JoinColumn(name = "song_id", foreignKey = @ForeignKey(name = "none"), updatable = false)
여기도 우리 nullable=false 해주면 좋을거 같아요!!😊

2023-08-10 13:49 UTC, splitCoding commented on backend/src/main/resources/schema.sql
> +create table killing_part
컬럼 순서 한번 야무지게 정리해주세요오~👍

2023-08-10 13:49 UTC, splitCoding commented on backend/src/main/resources/schema.sql
> +    song_id      bigint,
not null 이 필요할 것 같아요!!😁

2023-08-10 13:49 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/application/killingpart/KillingPartCommentService.java
> +        final KillingPart killingPart = killingPartRepository.findById(partId)
이부분에 테스트가 없는 것 같아요!!😊

2023-08-10 13:49 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/application/killingpart/KillingPartCommentService.java
> +        final KillingPart killingPart = killingPartRepository.findById(partId)
이부분에 대한 테스트가 없는 것 같아요!!😊

2023-08-11 05:26 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/KillingParts.java
> +    private final List<KillingPart> killingParts = new ArrayList<>();
Song에 KillingParts가 항상 있다는 걸 보장할 수 있을지 의문이 들어서, 우선은 NPE를 막기 위해 빈 ArrayList를 넣었습니다!
물론 코드 상에서 Song을 만들 때 생성자에서 KillingParts를 3개 가지도록 강제한다면 이런 상황이 안생기겠지만, DB에서 직접 주입하는 상황이 생길 수도 있을 것 같아서요 ㅎㅎ

팀원들이랑 다 같이 이야기해봐야 할 것 같아요!

2023-08-11 05:28 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/KillingParts.java
> +    private void validate(final List<KillingPart> killingParts) {
저의 실수입니다 😓 😓  
꼼꼼한 리뷰 감사합니다 🙇

2023-08-11 05:28 UTC, seokhwan-an reviewed
바론 코드 잘 확인했습니다~ 빠른시간안에 빠르게 구현해주셨네요~~👍👍
생각을 물어보는 질문 남겼습니다 확인해주세요!

2023-08-11 05:30 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartCommentRepositoryTest.java
> +        Song savedSong = songRepository.save(new Song("제목", "비디오URL", "이미지URL", "가수", 30));
감사합니다 😱

2023-08-11 05:55 UTC, Cyma-s approved these changes
크게 고칠 부분은 없네요 ~ approve 갑니다

2023-08-11 05:55 UTC, Cyma-s commented on backend/src/main/resources/schema.sql
> +    id           bigint generated by default as identity,
MySQL 문법에 맞춰 id bigint auto_increment가 되어야 할 것 같아요 😄

2023-08-11 05:55 UTC, Cyma-s commented on backend/src/main/resources/schema.sql
> +    killing_part_id bigint       not null,
이 부분도 동일합니다 :)

2023-08-11 05:55 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/application/killingpart/KillingPartCommentServiceTest.java
> +    @DisplayName("파트의 댓글을 등록한다.")
킬링파트라고 명시해주는 건 어떨까요?! 사실 사소한 거라 무시하셔도 됩니다

2023-08-11 06:28 UTC, splitCoding approved these changes
바론 고생 많이 했어요 👍 happy day

2023-08-11 06:28 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/KillingParts.java
> +        this.killingParts.addAll(new ArrayList<>(killingParts));
죄송해요.... ㅠㅠ 제가 잘못 알고 있었어요 😿 😿 

addAll 을 하면 참조값은 다르고, 값은 같은 새로운 요소가 추가된다 하더라구요! 좋은 코멘트 감사합니다 😄

2023-08-11 06:30 UTC, Cyma-s approved these changes
파펙트하네요~~

2023-08-11 06:30 UTC, seokhwan-an approved these changes
리뷰 내용 확인했습니다 고생하셨습니다.

2023-08-11 06:33 UTC, merged