Feat/#233 킬링파트 트랙 컴포넌트 구현
woowacourse-teams/2023-shook pull request #242
Opened 2023-08-10 09:52 UTC by Creative-Lee

## 📝작업 내용

- [x] 킬링파트 트랙 컴포넌트 구현
- [x] 킬링파트 트랙 리스트 컴포넌트 구현
- [x] svg 아이콘 형식 통일 및 화질 개선
  - 새로 올라간 파일은 새로 변환했거나 추가한 겁니다

## 💬리뷰 참고사항

- 킬링파트 트랙 컴포넌트
![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/89b1c5f3-4602-4f2d-afaf-15025b1c9e10)
재생, 좋아요, 공유 기능담당
관련 코드가 다음 PR에 추가될 예정입니다.

- 킬링파트 트랙 리스트 컴포넌트
![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/a5ebbe15-b036-49ab-95f3-9ef0061f0293)
각 트랙 컴포넌트 토글 관련 기능 담당 
관련 코드가 다음 PR에 추가될 예정입니다.

기능은 최대한 제외한 뷰와 관련된 작업만 모았습니다.

- 트랙 컴포넌트 클릭 시 play할 예정이고, input radio이기 때문에 하나의 트랙만 활성화(재생) 됩니다.
- 하단에 progress bar 디테일을 추가해서 디테일을 좀 살렸습니다.
활성화 중인 트랙에만 progress bar가 등장합니다.(현재는 그냥 흰색 배경 bar만 보이는게 맞습니다.)

### 접근성 관련 이슈
radio 버튼은 탭키가 아닌 방향키로 동작하도록 되어있다 하더라고요.
일단 동작하게 할 수는 있는데, 완벽하지 않아서 다음 페이지 개선 PR 까지 진행하고 합쳐본 후 테스트 해볼게요~!

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #233

2023-08-10 13:22 UTC, cruelladevil requested changes
고생하셨습니당~👍👍
코멘트가 많아서 finish comment는 짧게 쓸게요

1. 하트가 깨져요

<img width="160" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/63d9f894-aa7b-44f9-a9ab-683c4952ad3e">

2. 💬 기존 [ToggleGroup](https://github.com/woowacourse-teams/2023-shook/blob/main/frontend/src/shared/components/ToggleGroup/ToggleGroup.tsx)을 활용하지 않은 이유가 궁금하네용

2023-08-10 13:22 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +`;
보이지도 않는 input에 background가 있네용😭

2023-08-10 13:22 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  width: 120px;
💬 span은 inline요소라서 width가 없는데, styled-component가 block으로 바꿔주나보네요

2023-08-10 13:22 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +export const PartLength = styled.span`
안쓰이는 것 같네요 😯

2023-08-10 13:22 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +export const LikeCount = styled.span`
안쓰이는 것 같네요2 😯

2023-08-10 13:22 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  justify-content: flex-end;
💬 이 속성은 불필요해보이는데 어떤 이유인가요?

2023-08-10 13:22 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +`;
💬 LikeButton과 동일한데 따로 만든 이유가 궁금해요!

2023-08-10 13:28 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrackList.tsx
> +    <TrackList>
여기에도 `role="radiogroup"`이 추가되면 웹 접근성 좋겠네용 (2/3 읽어줍니다)
(2등 킬링파트 재생하기, 라디오버튼, 그룹 `2/3`)

2023-08-10 13:46 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrackList.tsx
> +    const newTrack = Number(currentTarget.value);
해당 핸들러가 적용되는 input은 radio type이여서 valueAsNumber 적용이 불가능했습니다~!
적용하면 NaN이 나올거에요!

2023-08-10 13:56 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrackList.tsx
> +  const [nowPlayingTrack, setNowPlayingTrack] = useState(-1);
좋은 의견입니다!
바로 분리할게요~

2023-08-10 14:00 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrackList.tsx
> +    const newTrack = Number(currentTarget.value);
오호 text input에만 valueAsNumber가 가능한가보네요~
타입 추론이 되어서 가능한 프로퍼티인줄 알았어요

2023-08-10 14:26 UTC, Creative-Lee commented on frontend/src/shared/types/killingPart.ts
> +export type PartVideoUrl = `https://youtu.be/${string}?start=${number}&end=${number}`;
이 부분은 서버 응답으로 내려오는 값을 확인하고 아래와 같아서 변경해두었어요. 
![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/a4cf88d1-800b-4e36-a5ce-bd049c5c990c)

실제로도 위 url로 공유한 뒤 들어가집니당

2023-08-10 14:29 UTC, cruelladevil commented on frontend/src/shared/types/killingPart.ts
> +export type PartVideoUrl = `https://youtu.be/${string}?start=${number}&end=${number}`;
백엔드와 협의해야되는 부분이네요!

2023-08-10 14:33 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  const partLength = end - start;
이 부분은 저도 고민하다가 api 스팩에서 다루는 네이밍으로 맞췄어요.(킬링파트 post 요청=== length로 보냄)
 
프로젝트 전반적으로 interval 이라는 말이 크게 
1. 킬링파트 구간 길이 ( 5 10 15)
2. 구간 자체를 나타내는 말 (intervalInput 컴포넌트 같은 경우)
 와 같이 쓰이고 있는데요! 
input 컴포넌트가 삭제될 예정이니, api와 함께 하나로 통일하면 좋겠네요!

2023-08-10 14:36 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  font-style: normal;
피그마 복붙의 폐해라고 할 수 있네요 ...ㅎ 삭제하겠습니다~

2023-08-10 14:45 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +    <Container htmlFor={`play-${rank}`} tabIndex={0} aria-label={`${rank}등 킬링파트 재생하기`}>
좋은 의견 감사합니다~
해당 부분은 PR 본문에 말씀드린대로 DetailPage 리팩터링 작업에서 보이스 오버 실행해 보면서 추가해 놓을게요!

2023-08-10 14:49 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  gap: 12px;
space-between을 나중에 적용하면서 남겨두었네요 수정 했습니다~

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 노래 태그하면서 피식했을 모습이 상상되네요^^

2023-08-10 14:50 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  }
💬 내장된 checked 속성으로 해결한 위의 방식과 비교했을때 어떤 장점이 있을까요?

2023-08-10 14:51 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +`;
그레잇!
이것도 실패한 무수한 실험코드중에 하나입니다 ㅋㅋㅋ
삭제하겠습니다! 놓친게 많네요~ ㅠ

2023-08-10 15:10 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  width: 120px;
💬 flex 하위 요소의 경우 레이아웃에 대한 설정이 가능해진다고 합니다~
저도 덕분에 공부했습니다~ 감사합니다~

2023-08-10 15:11 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +export const PartLength = styled.span`
흐흐 삭제했습니다~

2023-08-10 15:12 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +export const LikeCount = styled.span`
삭제 했습니다 (bot 이 알림)

2023-08-10 15:27 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  justify-content: flex-end;
높이 지정해두고 레이아웃 맞춰보고 하다가 제거를 안했네요 ㅎ..
삭제했습니다~

2023-08-10 15:34 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +`;
💬 네이밍을 따로 가져가고 싶어서 2개 다 만들게 되었어요.

이와 별개로 css 함수를 사용해서 동일 속성을 묶어두려고 했는데, 깜박했네요
적용해 두었습니다~

2023-08-10 15:35 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrackList.tsx
> +    <TrackList>
요것도 다음 PR에 같이 적용해볼게요~ 감사합니다요~

2023-08-10 15:38 UTC, Creative-Lee commented
@cruelladevil  야무진 리뷰 감사합니다~😀
반영 및 코멘트 답변 남겼어요~ 확인부탁드립니다~

2023-08-10 20:43 UTC, ukkodeveloper commented on frontend/src/shared/utils/formatOrdinals.ts
> +const enOrdinalRules = new Intl.PluralRules('en-US', { type: 'ordinal' });
Intl 객체 신기하네요!

2023-08-10 20:54 UTC, ukkodeveloper commented on frontend/src/features/songs/components/KillingPartTrackList.tsx
> +  killingParts: SongDetail['killingParts'];
💬 KillingParts 타입을 import해서 사용하는 것과, SongDetail 타입에서 특정 프로퍼티의 타입을 추출해서 사용하는 것의 차이에는 어떤 것이 있나요?

2023-08-10 21:07 UTC, ukkodeveloper commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  }
💬 has 의사 클래스를 사용하신 이유가 있을까요?

2023-08-10 21:28 UTC, ukkodeveloper reviewed
도밥 고생 많으셨어요. 컴포넌트 단순 구현뿐만 아니라, svg파일 웹접근성등 많은 부분을 신경쓴 게 보이네요! progressbar도 나중에 어떻게 보여지게 될 지 기대됩니다. 몇가지 코멘트 남긴 거 확인 부탁드릴게요

2023-08-10 21:28 UTC, ukkodeveloper commented on frontend/src/features/songs/types/KillingPartRank.type.ts
> +export type KillingPartRank = (typeof KILLING_PART_RANK)[keyof typeof KILLING_PART_RANK];
💬 상수화된 객체를 통해 타입을 추출하는 코드의 위치에 대해 저희 팀원끼리 함께 논의해봤으면 좋겠어요. 한 데 뭉쳐있으면 더 좋을 것 같다는 생각이 듭니다.

2023-08-10 21:28 UTC, ukkodeveloper commented on frontend/src/features/songs/components/KillingPartTrackList.stories.tsx
> +  likeCount: 12,
<img width="153" alt="스크린샷 2023-08-11 오전 5 58 12" src="https://github.com/woowacourse-teams/2023-shook/assets/109048739/00dcb0ac-f379-42d0-a2ed-8d6927bc0bce">
제 화면에서는 12 LIKES가 2줄이 되는데 의도하신건가요?

2023-08-10 21:28 UTC, ukkodeveloper commented on frontend/src/features/songs/components/KillingPartTrackList.tsx
> +          nowPlayingTrack={nowPlayingTrack}
💬 `KillingPartTrack` 컴포넌트가 현재 재생중인 트랙 정보(number)를 알 필요가 있을까요? 현재 자신이 재생중(boolean)인지만 알면 될 것 같아서요. 도밥의 생각이 궁금해요

2023-08-11 01:31 UTC, Creative-Lee commented on frontend/src/shared/utils/formatOrdinals.ts
> +const enOrdinalRules = new Intl.PluralRules('en-US', { type: 'ordinal' });
별 신기한게 엄청 많드라고옄ㅋㅋ

2023-08-11 01:37 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  width: 120px;
덕분에 하나 알아갑니다👍👍

2023-08-11 01:37 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrackList.tsx
> +  killingParts: SongDetail['killingParts'];
저는 이런 상황에 상위인 타입중 하나 라고 명시해주는 편이에요.
SongDetail이 api 응답 중 하나이니깐 응답객체의 특정 키값이라고 말해주는거죠!

2023-08-11 01:39 UTC, Creative-Lee commented on frontend/src/features/songs/types/KillingPartRank.type.ts
> +export type KillingPartRank = (typeof KILLING_PART_RANK)[keyof typeof KILLING_PART_RANK];
저도 항상 그생각을 하게되요 ㅋㅋㅋ 
타입 1개  상수1개 있는걸 따로 파일로 분리하는 게 다소 비효율적이라고 생각합니다.
개인적으로는 컴포넌트에 같이 두는것을 선호해요!

2023-08-11 01:39 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrackList.stories.tsx
> +  likeCount: 12,
이거는 확인해볼게요!

2023-08-11 01:54 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrackList.tsx
> +          nowPlayingTrack={nowPlayingTrack}
너무 좋은 생각입니다
트랙 한개가 다른 트랙이 재생중인지 알필요는 없다고 생각하네요

2023-08-11 02:08 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  }
Container가  check된 input을 **가지고** 있으면 을 강조하고 싶었습니다~

2023-08-11 03:02 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +        <ButtonIcon src={playIcon} alt="" />
별다른 이유는 없습니다 ㅋㅋ둘중 하나를 잘 명시해주면 되지 않을까 해요

2023-08-11 03:02 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +  }
근데 이부분은 브라우저 지원 문제로 인해서 코드 수정하도록 하겠습니다~

2023-08-11 05:16 UTC, cruelladevil approved these changes

2023-08-11 06:27 UTC, merged