Refactor/#236 VoteInterfaceContext의 partStartTime을 seconds로 관리한다
woowacourse-teams/2023-shook pull request #246
Opened 2023-08-10 14:16 UTC by cruelladevil

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명(이미지 첨부 가능)

VoteInterfaceContext의 partStartTime을 seconds로 관리하려고 합니다.
기존에 partStartTime을 TimeMinSec으로 관리하고 있었기 때문에 변환과정이 너무 많기 때문입니다.

또한 util 함수들이 튜플로 받고 있는 것을 seconds 또는 TimeMinSec으로 바꾸어,
시간에 대한 타입이 다양한 점을 줄여서 개발 피로도를 줄이려고 합니다.

## 💬리뷰 참고사항

> 원활한 리뷰를 위해 전달하고 싶은 맥락(특정 파일, 디렉터리 등등)  
> 리뷰어가 특별히 봐주었으면 하는 부분

변환하는 함수 네이밍을 `to` prefix로 정하였습니다.
`format`도 괜찮은 것 같은데 의견을 남겨주세요.

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #236

2023-08-10 16:32 UTC, Creative-Lee reviewed
시간단위 통일하려면 전체 코드 싹 읽어야 했을텐데 정말 고생많으셨습니다!

개인적으로 저번 페이지 단위 리팩토링 진행하면서 이 시간단위 변환이 마구잡이로 이뤄지는게
코드를 복잡하게 하는 제일 큰 요소라고 생각했어요.
시원하게 해결해 주셔서 정말 감사합니다. 😀
이 부분 코난이 진행할 줄 알았으면 미리 전체적인 문제점 정리해서 드렸으면 코난이 쫌 덜 고생했겠네요. 정말 고생많으셨습니다! 

코멘트 확인해주시고 재요청 주세요!

2023-08-10 16:32 UTC, Creative-Lee commented on frontend/src/features/songs/components/VoteInterfaceProvider.tsx
> +  // NOTE: Why both setState and eventHandler have same naming convention?
오 이부분은 하나로 통일해서 핸들러가 컴포넌트쪽으로 이동하든 하면 좋겠네요!

2023-08-10 16:32 UTC, Creative-Lee commented on frontend/src/features/songs/components/VoteInterfaceProvider.tsx
> +  const [partStartTime, setPartStartTime] = useState(0);
굿

2023-08-10 16:32 UTC, Creative-Lee commented on frontend/src/features/songs/components/VoteInterfaceProvider.tsx
> +      setPartStartTime(partStartTime - overflowedSeconds);
너무 편안하네요

2023-08-10 16:32 UTC, Creative-Lee commented on frontend/src/features/songs/components/VoteInterfaceProvider.tsx
> +        return minute + second;
💬 return 문 전에 개행은 어떠신가요?

2023-08-10 16:32 UTC, Creative-Lee commented on frontend/src/features/songs/components/VoteInterfaceProvider.tsx
>    const updatePartStartTime = (timeUnit: string, value: number) => {
이 함수를 사용하는 컴포넌트는 2개인데요!
IntervalInput 컴포넌트는 이제 삭제될 것이고,
VideoSlider 컴포넌트는 내부적으로 초단위로 관리되고 있어요!

때문에 더 이상 unit 인자를 받지 않아도 될것 같네요.
**unit별 분기들과** **VideoSlider 컴포넌트의 핸들러 함수** 내부 로직도 정리될 수 있을 것 같습니다!

```ts
//  VideoSlider.tsx
const changeTime: ChangeEventHandler<HTMLInputElement> = ({
    currentTarget: { valueAsNumber: currentSelectedTime },
  }) => {
    const { minute, second } = secondsToMinSec(currentSelectedTime);

    // TODO: 시간 단위 통일
    updatePartStartTime('minute', minute);
    updatePartStartTime('second', second);

    videoPlayer?.seekTo(currentSelectedTime, false);
  };

```

2023-08-10 16:32 UTC, Creative-Lee commented on frontend/src/features/songs/components/VoteInterfaceProvider.tsx
> +      videoPlayer?.seekTo(partStartTime, true);
묶은 변이 내려가는 기분이네요

2023-08-10 16:32 UTC, Creative-Lee commented on frontend/src/features/youtube/components/VideoSlider.tsx
>      updatePartStartTime('second', second);
위에서 말한 부분이 여기입니다!
정리 가능할 것 같네요~!

2023-08-10 16:32 UTC, Creative-Lee commented on frontend/src/features/youtube/components/VideoSlider.tsx
> +
💬 오.. 이거 멈추고 탐색할 필요가 없던건가요?

2023-08-10 16:32 UTC, Creative-Lee commented on frontend/src/shared/utils/convertTime.ts
> +export const minSecToSeconds = ({ minute, second }: TimeMinSec) => {
💬 이제 min, sec 단위로 관리되는 컴포넌트가 없는 것 같아서, 이 함수도 사라질수 있을 듯 합니다ㅎㅎ

2023-08-10 16:32 UTC, Creative-Lee commented on frontend/src/shared/utils/convertTime.ts
> -export const isValidTimeFormatLength = (value: string | number) => {
시원하군요 부채 해결!

2023-08-10 16:35 UTC, Creative-Lee requested changes
😅

2023-08-10 21:46 UTC, ukkodeveloper reviewed
제가 만든 부채 해결해주셔서 감사합니다. to prefix 좋아보여요. 더 간결해진 것 같아요!

2023-08-10 21:46 UTC, ukkodeveloper commented on frontend/src/shared/utils/convertTime.ts
> +export const secondsToMinSec = (seconds: number): TimeMinSec => {
👍

2023-08-10 21:46 UTC, ukkodeveloper commented on frontend/src/shared/utils/convertTime.ts
> +export const toMinSecText = (seconds: number) => {
number 타입만 받도록하니까 사용에 있어서도 복잡도가 많이 줄어들었네요

2023-08-10 21:46 UTC, ukkodeveloper commented on frontend/src/features/songs/components/IntervalInput.tsx
> +  const partEndTime = partStartTime + interval;
곧 없어질 컴포넌트이긴하네요!

2023-08-10 21:46 UTC, ukkodeveloper commented on frontend/src/features/songs/components/VoteInterfaceProvider.tsx
>    const updatePartStartTime = (timeUnit: string, value: number) => {
그렇네요! 굳!

2023-08-10 21:46 UTC, ukkodeveloper commented on frontend/src/shared/utils/validateTime.ts
> +export const isValidTimeFormatLength = (value: string | number) => {
이거 어디에 사용하는 친구인가요?

2023-08-11 01:41 UTC, cruelladevil commented on frontend/src/features/songs/components/VoteInterfaceProvider.tsx
>    const updatePartStartTime = (timeUnit: string, value: number) => {
네 맞습니다. updatePartStartTime이 초로 받도록 수정 가능합니다.
일단 IntervalInput 컴포넌트가 사용되지 않더라도 조금 더 지켜보면서 지속시키고,
후에 변경해도 괜찮다고 생각이 들어 해당 부분 그대로 남겨두었습니다.

2023-08-11 01:45 UTC, cruelladevil commented on frontend/src/shared/utils/validateTime.ts
> +export const isValidTimeFormatLength = (value: string | number) => {
@Creative-Lee 
도밥이 작업한 결과물입니다. 시간 포맷(분 or 초)가 2글자인 것을 검증하는 함수라고 합니다.

2023-08-11 01:46 UTC, cruelladevil commented on frontend/src/shared/utils/convertTime.ts
> +export const minSecToSeconds = ({ minute, second }: TimeMinSec) => {
이 함수도 당장에는 사용되는 곳이 없지만, 충분히 반대로도 변환할 상황이 있다고 생각해요.

2023-08-11 01:48 UTC, cruelladevil commented on frontend/src/features/youtube/components/VideoSlider.tsx
> +
<img width="900" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/2b86f954-4eb5-4a07-8ab4-448341800b9f">

2023-08-11 01:53 UTC, cruelladevil commented on frontend/src/features/songs/components/VoteInterfaceProvider.tsx
> +        return minute + second;
반영 완료 👍

✍️ 수정 커밋 - 56d614b888cad687a50eb22be7ac952a2b02026d

2023-08-11 01:54 UTC, cruelladevil commented on frontend/src/features/songs/components/VoteInterfaceProvider.tsx
> +  // NOTE: Why both setState and eventHandler have same naming convention?
엇 주석을 삭제 안했네요~
setState와 eventHandler가 똑같은 prefix 네이밍을 가지고 있어서 고민해봐야 될 것 같은 문제였습니당

2023-08-11 08:10 UTC, ukkodeveloper approved these changes

2023-08-11 09:05 UTC, Creative-Lee approved these changes
코멘트 답변 다 확인했습니다!
고생하셨습니다!

2023-08-11 09:22 UTC, merged