Feat/#235 킬링파트 수집 케러셀 컴포넌트 구현
woowacourse-teams/2023-shook pull request #248
Opened 2023-08-10 20:36 UTC by ukkodeveloper

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명(이미지 첨부 가능)

![Aug-11-2023 05-30-10](https://github.com/woowacourse-teams/2023-shook/assets/109048739/e2128645-a77c-4b0c-b4a3-c561006239ca)

## 💬리뷰 참고사항
#235 
변경사항: youtube music 에서 아이템을 좌우로 넘기는 ui를 만드려고 했지만, 이벤트성을 나타내는 것에서 부족하다고 생각하여 변경했습니다. 

- [ ] 자동으로 캐러셀이 넘어가져야 하는 지 생각해주세요. 저의 경우 모바일에서 화면에 오래 머물 일이 없기 때문에 굳이 화면을 넘기는 일이 필요 없다고 생각했습니다.
- [ ] 현재 캐러셀 내 아이템 width가 100%로 강제되어 있어요. 이유는 width를 기준으로 indicator표시하는 과정에서 100%가 아니면 계산하기가 쉽지가 않더라고요. 좋은 방법이 있으면 말씀해주세요.'
- [ ] 전반적으로 잘 만든 컴포넌트인지 확신이 안듭니다. 코드 보시고 고칠 점이나 생각할 점 있으면 과감없이 남겨주세요.

참고사항

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #235

2023-08-11 07:00 UTC, Creative-Lee requested changes
고생 많으셨습니다~!
코멘트 남겨놓은 부분 답변을 따로 대화 나눠보면 좋겠습니다 ㅎㅎ
다시 요청 주세요!

2023-08-13 16:13 UTC, cruelladevil requested changes
> 자동으로 넘어가져야 하는지?

기획 의도가 이벤트성이니 자동으로 넘어가지면 좋을 것 같네요!
필수 기능은 아니니 천천히 시도해보시면 좋을 것 같아요~

> width 100% 강제

다음 글이 도움이 되었으면 하네요
https://web.dev/i18n/ko/carousel-best-practices/
https://css-tricks.com/css-only-carousel/

> 고칠 점이나 생각할 점

**[고칠 점]**
코멘트로 남겨두었어요!

**[생각할 점]**
위 아티클을 보면 css로 충분히 가능한 것 같더라구요.
현재 우코 컴포넌트에서 가능할지는 확인 안해봤어요 😭 (충분히 가능할 것 같기는 해요)
그렇다면 index가 필요없을 것 같아요.

고생했어요~ 화이팅 💪💪

2023-08-13 16:13 UTC, cruelladevil commented on frontend/src/features/songs/components/CollectionCarousel.tsx
> +  will-change: transform;
💬 `will-change`까지 필요한가요??
will-change 속성을 잘 몰라서 이 속성이 필요한 최적화인가 궁금해요.

2023-08-13 16:13 UTC, cruelladevil commented on frontend/src/features/songs/components/CollectionCarousel.tsx
> +  & > * {
💬 ul 하위이니 li를 받도록 하면 어떨까요?

2023-08-14 09:01 UTC, ukkodeveloper commented on frontend/src/features/songs/components/CollectionCarousel.tsx
> +};
도밥이 말씀해주신 것 처럼 children자체가 배열이기 때문에 `Children.count()` 를 사용하도록 했습니다.

2023-08-14 09:39 UTC, ukkodeveloper commented on frontend/src/features/songs/components/CollectionCarousel.tsx
> +        <IndicatorWrapper aria-hidden>
고민을 해봤는데, 내부 내용 변경에 변경되어야 하는 코드가 많아질 것 같아요. 제가 width만 해결했어도 important 안써도 되었을텐데 ... 😢

2023-08-14 09:41 UTC, ukkodeveloper commented on frontend/src/features/songs/components/CollectionCarousel.tsx
> +  & > * {
혹시나 사용처에서 li를 사용하지 않았을 경우에도 스타일 적용이 되도록하기 위해서 다음과 같이 * 로 표기했었어요. 혹시 모르니 li와 div만 열어둘게요.

2023-08-14 09:42 UTC, ukkodeveloper commented on frontend/src/features/songs/components/CollectionCarousel.tsx
> +    list-style-type: none;
main pull 받았고 해당 속성 지웠어요

2023-08-14 10:42 UTC, ukkodeveloper commented on frontend/src/features/songs/components/CollectionCarousel.tsx
> +  will-change: transform;
이것저것 해보다가 지우지 않은 것 같아요. transform 자체가 필요없어서 지워놓겠습니다.

2023-08-14 10:42 UTC, ukkodeveloper commented on frontend/src/features/songs/components/CollectionCarousel.tsx
> +  & > * {
혹시나 사용처에서 li를 사용하지 않았을 경우에도 스타일 적용이 되도록하기 위해서 다음과 같이 * 로 표기했었어요. 혹시 모르니 li와 div만 열어둘게요.

2023-08-14 10:59 UTC, ukkodeveloper commented
![회전목마](https://github.com/woowacourse-teams/2023-shook/assets/109048739/5153db68-ff82-4386-b89e-bd10e3fb8196)

주신 피드백에서 반영한 사항은 해당 커멘트 댓글로 남겼습니다.

그 외의 부분에 대해서 말씀드리겠습니다.
1. "자동으로 캐러셀 넘어가도록 하기" 는 해결했습니다.
2. "width 100% 강제하지 않도록 하기". 이 부분에 대해서는 제 생각은 적어도 한 아이템다 width가 67% 초과되어야 할 것 같습니다. 애초에 indicator로 표기해주겠다는 뜻이 한 페이지에 아이템을 하나만 보여줘야하는 ui 인 것 같습니다. 따라서 width: 100% 를 풀고, min-width: 67%를 주었습니다.
3. css만으로 현재 아이템 index를 관리하는 게 힘들어 보이는데, 혹시 방법 아시면 내일 이야기 부탁드립니다... @cruelladevil

2023-08-16 01:25 UTC, Creative-Lee approved these changes

2023-08-16 01:26 UTC, cruelladevil approved these changes
고생하셨습니다👍👍

2023-08-16 01:26 UTC, cruelladevil commented on frontend/src/features/songs/components/CollectionCarousel.tsx
> +  children: ReactElement | ReactElement[];
👍 ReactElement로 한정하는거군요

2023-08-16 01:26 UTC, cruelladevil commented on frontend/src/features/songs/components/CollectionCarousel.tsx
> +  const handleScroll: React.UIEventHandler<HTMLUListElement> = ({ currentTarget }) => {
👍 currentTarget으로 변경 좋습니다

2023-08-16 02:17 UTC, merged