Feat/#230 토큰을 재발급 해주는 기능 추가
woowacourse-teams/2023-shook pull request #255
Opened 2023-08-12 05:14 UTC by seokhwan-an

## 📝작업 내용

accessToken이 만료되면 refreshToken으로 재발급해주는 기능 추가했습니다.

## 💬리뷰 참고사항
1. refresh 토큰을 이용해 access 토큰을 재발급하는 api url을 `/token`으로 했는데 `/login`처럼 `/reissue`와 같이 자원이 아닌 행위로 url을 구성하는 것에 어떻게 생각하시는지 궁금합니다.
2. 현재 cookie의 기간을 refresh 토큰 기간과 같게 했는데 그 이유는 refresh 토큰이 만료가 되면 그 cookie 역시 불필요한 것이라고 판단을 해서 그렇게 했는데 cookie의 기간 설정에 대한 의견을 듣고 싶습니다.
3. 마지막으로 `auth`패키지 내 기존 패키지인 `jwt`와 `oauth`를 삭제하고 `auth`로만 관리하는 방식으로 수정했는데 그 이유는 내부에서 패키지를 분리하다 보니 기능에 대한 응집성이 떨어진다고 생각했기 때문입니다. (변경한 패키지 구조에 대해서 의견을 듣고 싶습니다.)
   - 토큰을 재발급해주는 api는 jwt 패키지 내부에 있고 oauth 로그인을 하는 api는 oauth 패키지 내부에 있다보니 auth와 관련된 기능들이 흩어져있다고 생각했습니다.

## #️⃣연관된 이슈

 - close #230

2023-08-14 06:09 UTC, somsom13 approved these changes
고생하셨씁니다 아코~~~~

변경 사항 요청한 부분이 많지 않고, 질문이 대부분이라 approve 누르고 갑니당~~~~~~~

2023-08-14 06:09 UTC, somsom13 commented on backend/src/test/java/shook/shook/auth/application/AuthServiceTest.java
> +class AuthServiceTest {
mock 환경에서의 SpringBootTest 좋네용 👍 👍

2023-08-14 06:36 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/CookieProvider.java
> +        final Cookie cookie = new Cookie("refreshToken", refreshToken);
<img width="220" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/70303795/a6df3b4e-0121-4eaa-ad42-09044553ac0d">
chatgpt에서도 토큰 이름에 어떤 정보인지 나타내주는 명칭을 이용한 것을 보면 큰 문제는 없는 것 같습니다.

2023-08-14 07:27 UTC, Cyma-s requested changes
꼼꼼한 테스트 굿입니다~
같이 이야기해볼 부분 리뷰 남겼습니당 :)

2023-08-14 07:27 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/application/AuthService.java
> +            .orElseThrow(NotExistMemberException::new);
`MemberException.NotExistMemberException` 으로 변경 부탁드립니다~~👍

2023-08-14 07:27 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/ui/argumentresolver/AuthArgumentResolver.java
> +    private final AuthContext authContext;
깔끔하네용 🏆🏆🏆

2023-08-14 07:27 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/ui/AuthContext.java
> +public class AuthContext {
음 저도 이부분 궁금하네요 좀 더 유추해보자면 추후 값이 추가되었을 때를 대비해서 MemberInfo로 감싸서 보내는 것 같기도 한데 맞나요??

2023-08-14 07:27 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/ui/interceptor/TokenHeaderExtractor.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
springframework http 패키지의 `HttpHeaders.AUTHORIZATION` 를 사용해도 좋을 것 같네요~~!

2023-08-14 07:27 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/ui/AuthController.java
> +            tokenInfo.getRefreshToken());
저번에 아코와 이야기 했을 때 쿠키에 대한 정보를 service 에서 아는 게 맞는가? 에 대해서 이야기 했었어요. 비즈니스 로직 상으로 쿠키는 관련이 없기 때문에 (클라이언트에서 정보를 어떻게 저장하는지에 대한 문제니까요!) 쿠키는 컨트롤러에서 만들자! 라고 결론 났던 것 같아요.

GPT 선생님의 답변도 첨부합니다.

```markdown
Cookie는 HTTP 프로토콜의 일부이므로, 이와 관련된 동작은 주로 컨트롤러 레이어에서 처리하는 것이 적절합니다.
컨트롤러는 사용자의 요청을 받아 응답을 반환하는 역할을 하는데, 이때 HTTP 헤더와 바디를 조작하는 것은 컨트롤러의 주요 책임 중 하나입니다.
서비스 레이어는 비즈니스 로직에 집중하도록 설계되었기 때문에, HTTP와 관련된 로직을 포함시키는 것은 관심사 분리 원칙에 위배될 수 있습니다.
```

2023-08-14 07:27 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/ui/TokenController.java
> +    @GetMapping("/token")
저는 `/reissue` 라는 url 로 구성하는 것이 바람직하다고 생각합니다. `/token` 이라는 url 이 무엇을 의미하는지 명확하지 않기 때문입니다! (무슨 token 을 의미하는 것인지 등)

결론적으로는 `/reissue` 라는 url 이 더 직관적인 것 같아요

2023-08-14 07:27 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/application/dto/GoogleAccessTokenRequest.java
> +package shook.shook.auth.application.dto;
변경된 패키지 구조 좋은 것 같습니다!
jwt와 oauth 모두 auth 에 포함된 세부 기능이기도 하고, 이후에 oauth 를 사용하는 다른 로그인 방식이 필요해지면 그 때 패키지를 나누면 될 것 같아요

2023-08-14 07:27 UTC, Cyma-s commented on backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
> +        final Optional<Member> result = memberService.findById(savedMember.getId());
💬 여기서 바로 `.get()`을 해도 될 것 같아요! 아래 then 절에서 반복적인 get() 을 줄일 수 있지 않을까요?! 😁

2023-08-14 08:32 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/exception/TokenException.java
> +    public static class TokenNotFoundException extends TokenException {
아 이미 생성된것이 있었군요 아무래도 authroizationException과 TokenException이 분리가 되어 있어서 헷갈리는 것 같아요 이를 하나의 파일로 관리하면 이와 같은 실수가 안 발생할 것 같아요!

2023-08-14 08:50 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/TokenController.java
> +        }
1. 디폴트 값을 부여해서 처리하고자 했던 이유는 에러를 명확하게 처리하기 위해서 입니다. 기본적으로 쿠키가 존재하지 않을 경우 기본적으로 `java.lang.IllegalStateException: Missing cookie value '쿠키이름' of type java.lang.String` 발생한다고 합니다. 이 보다는 예외 상황을 명확하게 처리하고 싶어 default 값을 부여해서 처리했습니다.
2. 이 부분은 쿠키가 있는지 없는지를 식별하는 것이어서 이는 service가 아닌 controller에서 예외를 처리했습니다.

2023-08-14 08:52 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/interceptor/TokenHeaderExtractor.java
> +        if (Objects.isNull(authorizationHeader) || authorizationHeader.isBlank()) {
깜빡했네요 스플릿의 StringChecker를 이용해서 처리해야겠네요!

2023-08-14 08:54 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/AuthService.java
> +            .orElseThrow(NotExistMemberException::new);
넵 감사합니다☺️

2023-08-14 09:16 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/interceptor/TokenHeaderExtractor.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
이 부분이 더 가독성이 좋은 것 같습니다👍👍

2023-08-14 09:18 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/TokenController.java
> +    @GetMapping("/token")
저도 `/reissue`로 하는 것이 더 명확할 것 같습니다. 그렇게 수정하겠습니다!

2023-08-14 09:52 UTC, splitCoding reviewed
아코 고생많았어요!!👍

다음에 한번 전체적으로 강연한번 해주시죠오~~

(MemberRegisterRequest 가 사용되지 않는데 존재하고 있어요!! )

2023-08-14 09:52 UTC, splitCoding commented on backend/src/main/java/shook/shook/auth/application/AuthService.java
> +            .orElseThrow(NotExistMemberException::new);
MemberNotExistException 은 안되나요

2023-08-14 09:52 UTC, splitCoding commented on backend/src/main/java/shook/shook/auth/application/GoogleInfoProvider.java
52 ~ 53 번 라인 이렇게 변경되어야 할 것 같아요!! ( 아래 처럼 바뀌어야할 부분 여러군데 있어요~ )
```java
final GoogleMemberInfoResponse responseEntity = restTemplate.exchange(
      GOOGLE_MEMBER_INFO_URL,
      HttpMethod.GET,
      request,
      GoogleMemberInfoResponse.class
  ).getBody();
```

아래 부분도 팀끼리 한번 얘기해야 할 것 같아요~~
```java
if (!Objects.requireNonNull(responseEntity).isVerifiedEmail()) {
    throw new OAuthException.InvalidEmailException();
}
```

2023-08-14 09:52 UTC, splitCoding commented on backend/src/main/java/shook/shook/auth/application/TokenProvider.java
49번 째 줄 final 키워드 붙여주세요오~

2023-08-14 09:52 UTC, splitCoding commented on backend/src/main/java/shook/shook/auth/application/TokenProvider.java
> +        } catch (MalformedJwtException | SignatureException e) {
이 두개의 Exception이 서로 어떻게 다른지 궁금합니다!!

2023-08-14 09:52 UTC, splitCoding commented on backend/src/main/java/shook/shook/auth/config/OAuthConfig.java
RestTemplate 에 대해서 그 때 같이 얘기했었는데 Bean 으로 등록하기로 정한 이유가 궁금합니다!! 😁

2023-08-14 09:52 UTC, splitCoding commented on backend/src/main/java/shook/shook/auth/ui/interceptor/TokenHeaderExtractor.java
> +    private static String[] validateAuthorizationHeader(final String authorizationHeader) {
이 부분에서 공백을 기준으로 파싱해서 String[] 를 반환하는 로직이 validate 인것보다 validate 롸 파싱 메서드를 분리해서 토큰값만 반환하는건 어떨까요??

2023-08-14 09:52 UTC, splitCoding commented on backend/src/main/java/shook/shook/member/exception/MemberException.java
> +        public NotExistMemberException() {
MemberNotExistException() 어떤신가요오??

2023-08-14 09:52 UTC, splitCoding commented on backend/src/test/java/shook/shook/auth/ui/AuthControllerTest.java
> +    @DisplayName("회원이 로그인을 하면 요청결과 200을 반환한다.")
DisplayName이 조금더 자세하면 좋을 것 같아요!!

2023-08-14 09:52 UTC, splitCoding commented on backend/src/test/java/shook/shook/auth/ui/TokenControllerTest.java
> +    @DisplayName("올바른 refreshToken을 요청하면 accessToken과 상태코드 200을 반환한다.")
```suggestion
    @DisplayName("올바른 refreshToken를 통해 accessToken 재발급을 요청하면 accessToken과 상태코드 200을 반환한다.")
```

2023-08-14 11:14 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/AuthService.java
> +            .orElseThrow(NotExistMemberException::new);
다른 예외처리 명칭도 스플릿이 말한 형식으로 되어 있는데 그 부분 수정하겠습니다:)

2023-08-14 11:17 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/interceptor/TokenHeaderExtractor.java
> +        if (tokenElement.length != 2 || !tokenElement[0].equals(TOKEN_PREFIX)) {
token_format_size라는 명칭으로 했는데 괜찮나요?

2023-08-14 11:21 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
> +        final Optional<Member> result = memberService.findById(savedMember.getId());
좋습니다👍👍

2023-08-14 11:47 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/GoogleInfoProvider.java
넵 아래 부분은 이야기를 해봐야 할 것 같습니다.
위의 부분은 수정했습니다.

2023-08-14 11:49 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/TokenProvider.java
<img width="388" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/70303795/42714e99-db78-4981-930d-981f23a846ce">
50번째 줄을 의미하는 것이 맞을 까요?

2023-08-14 11:50 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/TokenProvider.java
> +        } catch (MalformedJwtException | SignatureException e) {
왼쪽은 jwt 토큰의 형태가 아닌 것에서 오류를 잡아주고 오른쪽은 올바른 jwt 토큰의 형태를 가지고 있는 상황에서 암호화된 secretKey가 다른 경우에 오류 잡아줍니다

2023-08-14 11:57 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/TokenProvider.java
> +        } catch (MalformedJwtException | SignatureException e) {
jwt의 올바른 형식이 아니라는 것은 .의 개수가 다르다던가 혹은 각 요소 header, payload, signature가 Base64로 인코딩된 각 부분이 올바르지 않은 것을 의미합니다.

2023-08-14 12:32 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/config/OAuthConfig.java
일단 다시 더 찾아보았을 때 공식문서에서는 threadSafe하다고 나와있어서 빈으로 등록을 하고 처리를 했습니다. https://spring.io/blog/2009/03/27/rest-in-spring-3-resttemplate

2023-08-14 12:33 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/member/exception/MemberException.java
> +        public NotExistMemberException() {
넵 다른 예외 이름 형식도 스플릿이 리뷰준 것과 같아서 이와 같이 수정하겠습니다.

2023-08-14 12:34 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/auth/ui/TokenControllerTest.java
> +    @DisplayName("올바른 refreshToken을 요청하면 accessToken과 상태코드 200을 반환한다.")
자세하게 수정하겠습니다.

2023-08-14 12:34 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/auth/ui/AuthControllerTest.java
> +    @DisplayName("회원이 로그인을 하면 요청결과 200을 반환한다.")
넵 자세하게 수정하겠습니다!

2023-08-14 12:53 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/TokenController.java
> +            throw new TokenException.TokenNotFoundException();
이러면 일단 이 부분 TokenNotFoundException을 AccessTokenNotFoundException과 RefreshTokenNotFoundException으로 분리 했습니다!

2023-08-14 12:57 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/exception/TokenException.java
> +    public static class TokenNotFoundException extends TokenException {
TokenException에는 토큰의 기간 예외와 발급 예외만 처리하고 나머지 토큰의 존재 여부는 AuthroizationException에서 처리하는 방식으로 수정했습니다.

2023-08-14 13:22 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/TokenController.java
> +            throw new TokenException.TokenNotFoundException();
꼼꼼한 리뷰 감사합니다:)

2023-08-16 05:21 UTC, Cyma-s approved these changes
service 에서 예외 처리 해주는 부분만 추가하면 더 좋을 것 같아요!
수고하셨습니다 ~ 👏👏👏👏

2023-08-16 05:21 UTC, Cyma-s commented on backend/src/main/java/shook/shook/member/application/MemberService.java
> +        return memberRepository.findById(id);
```suggestion
        return memberRepository.findById(id)
.orElseThrow(MemberNotExsistException::new);
```

예외 처리는 서비스가 해주는 게 맞는 것 같아요!

2023-08-16 05:21 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/ui/interceptor/TokenInterceptor.java
> +            .orElseThrow(MemberNotExsistException::new);
인터셉터에서 예외처리를 하기보다는 service 에서 예외 처리가 되는 게 더 좋아보여요!
지금은 인터셉터가 너무 많은 비즈니스 로직을 가지고 있는 것처럼 보이는데 어떻게 생각하시나요? 🤔

2023-08-16 05:21 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/KillingPartLikeController.java
> +        killingPartLikeService.updateLikeStatus(killingPartId, memberInfo.getMemberId(), request);
👍🏻 👍🏻 👍🏻 👍🏻

2023-08-16 05:28 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/argumentresolver/AuthArgumentResolver.java
> +        if (authContext.isAnonymous()) {
수정했습니다:)

2023-08-16 05:29 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/argumentresolver/Member.java
> +public @interface Member {
넵 그 부분 리뷰에 맞게 수정했습니다

2023-08-16 05:29 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/CookieProvider.java
> +        cookie.setSecure(true);
이 부분은 QA를 해보고 동작이 하지 않는 다면 수정하겠습니다.

2023-08-16 05:31 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/member/application/MemberService.java
> +        return memberRepository.findById(id);
넵 알겠습니다! 저도 memberService에서 예외를 처리하면 좋을 것 같습니다:)

2023-08-16 05:31 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/interceptor/TokenInterceptor.java
> +            .orElseThrow(MemberNotExsistException::new);
저도 그 방식이 좋을 것 같습니다:)

2023-08-16 06:00 UTC, merged

2023-08-17 07:54 UTC, somsom13 commented
#267