Feat/#249 bottomsheet 모달 적용하여 댓글리스트를 보여준다.
woowacourse-teams/2023-shook pull request #256
Opened 2023-08-12 08:14 UTC by ukkodeveloper

## 📝작업 내용
bottomsheet 모달 적용하여 댓글리스트를 보여준다.
![Aug-12-2023 17-08-33](https://github.com/woowacourse-teams/2023-shook/assets/109048739/c3958612-266e-4840-8fae-641cbad1e3c4)

## 💬리뷰 참고사항
- 이미 존재하고 있는 modal 코드를 토대로 만들었습니다.
  ( 성급하게 추상화하는 것보다 독자적인 컴포넌트로 존재해야한다고 생각해야했습니다.)
- 모달 내부에 padding을 모두 없앴습니다. 
  - 아래 댓글 입력 창에 border 을  bottom sheet 전체를 긋기 위해 
- 다소 CommentList 컴포넌트가 비대해졌습니다.
  - 이를 해결하려면 다수의 props를 드릴링해야 합니다. 이럴 때 컴포넌트를 분리해야할 지 의견이 궁금해요

## #️⃣연관된 이슈

close #249

2023-08-13 12:54 UTC, Creative-Lee requested changes
고생 많으셨습니다! 우코~!
PR 본문에 대한 질문과 의견을 말씀드릴게요~

>이미 존재하고 있는 modal 코드를 토대로 만들었습니다.

아주 좋습니다~

>모달 내부에 padding을 모두 없앴습니다.

이거는 정확히 상황이 무엇인지 몰라서 만나서 한번 설명해 주세요 ㅎㅎ

>다소 CommentList 컴포넌트가 비대해졌습니다.
>이를 해결하려면 다수의 props를 드릴링해야 합니다. 
>이럴 때 컴포넌트를 분리해야할 지 의견이 궁금해요

`공통 컴포넌트`인 바텀 시트를 내부적으로 사용하는
`코멘트 바텀 시트` 컴포넌트를 만들면 고민이 해결될 것 같아요.
내부에서 필요한 것을 props로 넘기도록 하면 될것 같구요.
`코멘트 바텀시트 관련 스타일링`도 분리되어 한결 가벼워 지겠네요!

```ts
const CommentsBottomSheet = ({...etc }) => {
  // 뉴코멘트 상태, 핸들러, 
   
  return (
    <BottomSheet>
      <내부 스타일링/>    
      <내부 스타일링/>
      <코멘트 폼/>
    </BottomSheet>
  )
}

```

현재 제가 작업한 부분에서는 코멘트 리스트 컴포넌트가 더이상 page 컴포넌트에 존재하지 않아요. 
우코 작업물을 제가 이어 붙여야 하니 이 부분은 한번 같이 코드 보고 이야기 해봅시다!
다시 요청주세요 ㅎㅎ

2023-08-13 12:54 UTC, Creative-Lee commented on frontend/src/features/comments/components/CommentList.tsx
> +import cancleIcon from '@/assets/icon/cancle.svg';
스펠링 확인해 주세요~~

2023-08-13 12:54 UTC, Creative-Lee commented on frontend/src/features/comments/components/CommentList.tsx
> +import type React from 'react';
요거 없어도 되지 않나요?

2023-08-13 12:54 UTC, Creative-Lee commented on frontend/src/features/comments/components/CommentList.tsx
> +import cancleIcon from '@/assets/icon/cancle.svg';
스펠링 한번 확인해 주세요~

2023-08-13 12:54 UTC, Creative-Lee commented on frontend/src/features/comments/components/CommentList.tsx
> +  padding: 0 16px;
flex 관련 속성이 빠진 것 같네요!


![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/8b4b6d08-7125-4d6f-bc4c-5677644089ff)


![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/8f3f806e-c34f-456f-9f06-781e3a4029e0)

2023-08-13 12:54 UTC, Creative-Lee commented on frontend/src/features/comments/components/CommentList.tsx
> +  margin-bottom: 100px;
코멘트 폼으로 인해 가려지는 컨텐츠를 다 보여주려는 의도였던 것 같은데요!
100px로 부족한 것 같습니다! 
아래 보이는 이미지처럼 마지막 댓글이 잘리네요~

![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/77714f2d-814e-4e4a-a6d0-9c5fde5ac0aa)

2023-08-13 12:54 UTC, Creative-Lee commented on frontend/src/features/comments/components/CommentList.tsx
> +  max-height: calc (100vh - 100px);
max-heitgh 속성은 적용되지 않고 있어요.
💬 필요했던 이유가 있나요?

2023-08-13 13:14 UTC, ukkodeveloper commented on frontend/src/features/comments/components/CommentList.tsx
> +import styled, { css } from 'styled-components';
웹스톰 이슈... 😢

2023-08-13 13:15 UTC, ukkodeveloper commented on frontend/src/features/comments/components/CommentList.tsx
> +import cancleIcon from '@/assets/icon/cancle.svg';
영단어 하나 더 외웠다! 감사요

2023-08-13 13:15 UTC, ukkodeveloper commented on frontend/src/features/comments/components/CommentList.tsx
> +import type React from 'react';
웹스톰 이슈... 😢2

2023-08-13 17:36 UTC, cruelladevil requested changes
댓글 리스트만 스크롤 되면 fixed가 전혀 필요 없을 것 같아요~

### 컴포넌트 구성

제목
댓글 리스트(overflow scroll)
댓글 입력 폼

![Kapture 2023-08-14 at 02 17 43](https://github.com/woowacourse-teams/2023-shook/assets/87710730/6ea6b466-8428-44d2-a65f-bc4e623e2346)

2023-08-13 17:36 UTC, cruelladevil commented on frontend/src/features/comments/components/CommentList.tsx
> +  ${buttonBase};
💬 어떤 것은 세미콜론(`;`)이 붙고 어떤 것은 안붙네용

2023-08-13 17:36 UTC, cruelladevil commented on frontend/src/features/comments/components/CommentList.tsx
> +  max-height: calc (100vh - 100px);
띄어쓰기 되어서 적용안됐네요

```suggestion
  max-height: calc(100vh - 100px);
```

2023-08-13 17:36 UTC, cruelladevil commented on frontend/src/features/comments/components/CommentList.tsx
> +  max-height: calc (100vh - 100px);
💬 값 계산 기준을 어떻게 적용시켰는지 잘 모르겠지만
제가 보여드린 예제에서는 `calc(100vh - 542px);`입니다.

2023-08-13 17:36 UTC, cruelladevil commented on frontend/src/features/comments/components/CommentList.tsx
> +  margin-bottom: 100px;
margin-bottom이 불필요할 것 같습니다

2023-08-13 17:36 UTC, cruelladevil commented on frontend/src/features/comments/components/CommentList.tsx
> +  position: fixed;
💬 fixed일 필요가 없을 것 같습니다

블럭을 굳이 레이어처럼 덮어서 쌓지 말고 그냥 쭉 나열해도 충분한 것 같아요

2023-08-13 17:36 UTC, cruelladevil commented on frontend/src/features/comments/components/CommentList.tsx
> +  bottom: 0;
💬 fixed가 필요없을 경우 마찬가지로 필요없을 것 같습니다.

2023-08-13 17:36 UTC, cruelladevil commented on frontend/src/shared/components/BottomSheet/BottomSheet.tsx
> +  overflow-y: scroll;
💬 BottomSheet 자체가 스크롤이 있기 보단 내부 컨텐츠가 스크롤을 갖는 것이 더 자연스러운 것 같아요.

2023-08-13 17:36 UTC, cruelladevil commented on frontend/src/shared/components/BottomSheet/BottomSheet.tsx
> +  max-height: 60svh;
💬 좋은 기능이기는 하나 다소 최근에 나온 스펙이네요

https://caniuse.com/viewport-unit-variants

2023-08-14 11:16 UTC, ukkodeveloper commented on frontend/src/shared/components/BottomSheet/BottomSheet.tsx
> +  animation: ${slideUpAnimation} 0.4s ease-in-out;
오 확실히 줄이니까 속이 시원한데요?

2023-08-14 12:17 UTC, ukkodeveloper reviewed
1. 댓글입력창 fixed 삭제. 
2. overflow 관리를 bottom sheet에서 삭제
3. row-gap 적용

2023-08-16 01:28 UTC, cruelladevil approved these changes

2023-08-16 02:19 UTC, Creative-Lee approved these changes
정말 고생많았습니다!
css 쉽지않았을텐데 남은 시간도 화이팅입니다!

2023-08-16 04:55 UTC, merged