Feat/#229 파트 수집 중인 노래 전체 조회, Swipe 용 API 추가
woowacourse-teams/2023-shook pull request #259
Opened 2023-08-13 04:36 UTC by Cyma-s

## 📝작업 내용

파트 수집 중인 노래를 전체 조회하는 API와 id를 입력 받아 id로 조회한 노래와 id 이전, 이후 노래들을 조회하는 API 를 구현했습니다.

## 💬리뷰 참고사항

- id가 작은 노래들을 가져올 때 쿼리 결과 값이 거꾸로 나오고 있기 때문에 `reverse` 를 해주고 있습니다.
- 현재 Swipe 용 API 에서 쿼리를 3번 정도 날리고 있는데, 쿼리를 줄이는 게 좋을까요?
- 전체 조회하는 API도 id로 정렬된 값이 내려가야 할까요? `findAll` 에서는 DB 벤더 사 정렬 기준에 따라 데이터를 가져오는데, id 로 확실하게 정렬해서 보내야 할 지 고민입니다.

## #️⃣연관된 이슈

closes #229

2023-08-13 06:39 UTC, seokhwan-an requested changes
먼저 빠르게 구현하신 것 고생했습니다.👍👍 코드는 전반적으로 깔끔해서 코드에 대한 리뷰는 크게 없고 베로가 참고사항에 적어준 내용을 기반으로 제 의견을 피드백 남겼습니다. ☺️

2023-08-13 06:39 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/support/AcceptanceTest.java
> +}
`@SpringBootTest`를 할 때마다 이 부분을 계속 작성해야했는데 하나의 파일로 분리 해주셨군요 감사합니다.☺️

2023-08-13 06:39 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/support/DataCleaner.java
> +                .executeUpdate();
테이블 id가 다시 1부터 시작하게 해주는 것 최곱니다.👍👍

2023-08-13 06:39 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/voting_song/ui/VotingSongControllerTest.java
> +    @DisplayName("특정 노래를 조회할 때, 이전 노래와 다음 노래의 정보를 담은 응답을 반환한다.")
service Test를 진행할 때에는 각각의 상황에 대해서 처리했는데 인수테스트에서는 하나의 case 그 중에서도 이전 노래만 있는 테스트만을 진행한 이유가 있을까요?

2023-08-13 06:39 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/voting_song/application/VotingSongService.java
> +        );
3개의 쿼리를 보내는 부분이 이 부분인거 같아요 VotIng Song의 경우 Song의 비해 데이터가 적기 때문에 findAll()로 전체를 불러오고 처리하는 방식이 성능면에서 좋을 수 있다고 생각이 되지만 저는 현재 베로가 작성한 부분이 가독성이 더 좋은 거 같아요. 그래서 모니터링을 통해 이 부분 요청이 자주 발생해서 병목이 되면 그 때 수정하는 방안으로 가도 좋을 것 같아요 ☺️

2023-08-14 04:54 UTC, splitCoding approved these changes
아주 좋아요오 👍 베로 나이스!!

2023-08-14 04:55 UTC, seokhwan-an approved these changes
코드 작성하시느라 고생하셨습니다!

2023-08-14 04:56 UTC, Cyma-s commented on backend/src/main/java/shook/shook/voting_song/domain/repository/VotingSongRepository.java
> +    List<VotingSong> findByIdGreaterThanOrderByIdAsc(final Long id, final Pageable page);
좋은 배워나감 좋네요

2023-08-14 04:59 UTC, Cyma-s commented on backend/src/main/java/shook/shook/voting_song/application/VotingSongService.java
> +    }
`findAll` 오름차순 정렬로 변경했습니다!

2023-08-14 05:01 UTC, somsom13 commented on backend/src/main/java/shook/shook/voting_song/application/VotingSongService.java
> +        Collections.reverse(beforeVotingSongs);
Pageable 내부 구현이 offset, limit, 그리고 정렬 조건으로 구성되어 있는 걸로 알고 있는데
저였다면 쿼리를 줄이는 방법으로 service 메서드 내에서 요청이 들어온 id를 기준으로 앞 4개, 뒤 4개를 계산해서 repository에 offset과 limit을 넘겨줬을 것 같아요!

그리고 `@Query` 어노테이션을 사용해서든, 혹은 JPA를 사용하든 정렬된 데이터 내에서 offset과 limit으로 하나의 쿼리에서 전체를 조회하도록 작성했을 것 같습니다 ㅎㅎ

하지만 VotingSong의 데이터가 많지 않은 상황에서는 지금의 로직도 충분한 것 같아요~!

2023-08-14 05:02 UTC, somsom13 approved these changes
깔끔하네용 👍 👍 👍 

스와이프 조회 API 관련해서 의견 하나 추가했습니다~ 고생하셨어요

2023-08-14 05:04 UTC, Cyma-s commented on backend/src/main/java/shook/shook/voting_song/application/VotingSongService.java
> +        Collections.reverse(beforeVotingSongs);
아무래도 쿼리가 한 번 더 나가다보니까 성능 상 차이가 존재할 것 같긴 합니다!!
성능 비교해보고 유의미한 차이가 나는 경우 하나의 쿼리로 처리하는 로직으로 변경하는 걸 고려해보겠습니다 👍

2023-08-14 05:10 UTC, somsom13 approved these changes

2023-08-14 05:14 UTC, merged