Feat/#226 Song 조회 기능 리팩터링, 좋아요 등록/취소 기능 구현
woowacourse-teams/2023-shook pull request #260
Opened 2023-08-13 16:05 UTC by somsom13

## 📝작업 내용

Song 조회 기능 리팩터링, 좋아요 등록/취소 기능을 구현했습니다.
- [x] (관리자용) 노래, 킬링파트 등록 API
- [x] 킬링파트 댓글 등록, 조회 API
- [x] 킬링파트 좋아요 등록, 취소 API
- [x] 좋아요 갯수에 따른 노래 목록 전체 조회, 상세 조회 API 구현 

## 💬리뷰 참고사항

- 좋아요 swipe API까지는 이번 스프린트 요구사항이 아니었던 것 같은데, 구현하다 보니 재미있어서 조금 구현해보다가 스프린트 기간이 끝나서 그만뒀습니다.. ㅎㅎ 혹시 이번 스프린트 요구사항이었는데, 제가 잘못 기억하는거라면 알려주세요
- Song과 KillingPart가 생성자에서 서로를 가지게 하면서 몇 가지 이슈가 있었습니다. 설명이 조금 길어서 보기 편하게 노션 첨부합니다! 
  - [KillingParts 초기화 이유, setSong 테스트 못한 이유, 관리자 controller 통합한 이유](https://somsom13.notion.site/KillingParts-Song-9ec4b08f3500413e8ed6bd325d140bba?pvs=4)
- 좋아요 기능을 구현하면서 likeCount를 도입했습니다. (LAZY Loading을 쓰면 프록시 객체로 size를 가져오는 줄 알았는데, 그냥 select 쿼리를 날리더라고요....) 
  - 전체 조회 시 좋아요 순으로 정렬
  - 스와이프 시 좋아요 순으로 조회
  - 상세 페이지 조회 시 좋아요 갯수 반환
  
  빈번하게 발생하는 3가지 상황에서 3개의 테이블을 매번 join하는 것 보다는 likeCount를 선택했습니다. 이 때 생기는 동시성 이슈에 대한 내용은 아래 글에서 확인해주시면 감사하겠습니다~! 
  - [likeCount 동시성 문제상황, 해결방안, join query 속도 측정](https://somsom13.notion.site/likeCount-55669c124e484e679e11b7c7d6fe069c?pvs=4)

## #️⃣연관된 이슈

closes #226

2023-08-14 05:09 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
> +@AllArgsConstructor
정적 팩토리 메소드가 있어서 이 부분은 private으로 접근제어자를 추가해주세요

2023-08-14 06:45 UTC, Cyma-s requested changes
진짜 할 거 많았네요...ㅋㅋㅋ큐ㅠㅠㅠ 테스트 보고 기절하는 줄 알았습니다 바론 진짜진짜 수고 많았어용~~

2023-08-14 06:45 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +        + "GROUP BY s.id")
배워갑니다 👏👏👏👏

2023-08-14 06:45 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/AdminSongController.java
> +        return ResponseEntity.created(URI.create("/" + savedSongId)).build();
엇 여기 `/songs` 안 붙어도 되나용?! 프론트엔드 기준인지 아니면 백엔드 API 기준인지 궁금합니다

2023-08-14 06:45 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/KillingPartCommentController.java
> +@RequestMapping("/songs/{song_id}/parts/{killing_part_id}/comments")
💬사실상 song_id 가 아래 메서드들에서 사용되지 않으니 `/parts/{killing_part_id}/comments` 로 줄여도 좋을 것 같아요!

2023-08-14 06:45 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/KillingPartLikeController.java
> +@RequestMapping("/songs/{song_id}/parts/{killing_part_id}/likes")
💬여기서도 마찬가지로 `song_id` 가 사용되지 않으니 `/parts/{killing_part_id}/likes` 로 변경하는 건 어떠신가요?!

2023-08-14 06:45 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/SongController.java
> +    public ResponseEntity<SongResponse> showSongById(@PathVariable(name = "song_id") Long songId) {
`final` 이 빠졌습니다!!! 😄

2023-08-14 06:45 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/application/killingpart/KillingPartCommentServiceTest.java
> +    private static final long UNSAVED_PART_ID = 10L;
가끔 id 가 10L 이 될 때도 있더라구요 🤔 id 가 무조건 1부터 시작한다는 보장이 없으니 아예 `Long.MAX_VALUE` 를 사용하는 건 어떨까요?

2023-08-14 06:45 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/application/killingpart/KillingPartLikeServiceTest.java
> +class KillingPartLikeServiceTest extends UsingJpaTest {
꼼꼼한 테스트 대단합니다 👍👍👍

2023-08-14 06:45 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
> +    private KillingPartLikes killingPartLikes = new KillingPartLikes();
이 부분도 final이 될 수 있을 것 같아요 😄

2023-08-14 06:45 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartsTest.java
> +    @ParameterizedTest
좋은데요??????!👏

2023-08-14 06:58 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
> +            .orElseThrow(MemberException::new);
앗 아코의 로그인 코드가 추가될 때 Member가 없다는 예외가 추가될 수도 있을 것 같아서 최대한 중복되는 예외 클래스를 줄이기 위해 임시적으로 넣었습니다 😃 

상세 예외 클래스 추가하겠습니당 ㅎㅎ 감사합니다~!

2023-08-14 07:00 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
> +            .orElseThrow(MemberException::new);
조아욥~~~~

2023-08-14 07:32 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
> +    public boolean doesNotBelongsToKillingPart(final KillingPart killingPart) {
good opinion 🧅 🧅

2023-08-14 07:33 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
> +@AllArgsConstructor
네

2023-08-14 07:35 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
> +
앗 백엔드 코드 컨벤션에 `@PrePersist 메서드는 getter 위에 작성한다.` 이라고 나와있길래 밑으로 내렸는데, createdAt과 묶어두기로 결정했었나용?.?

![image](https://github.com/woowacourse-teams/2023-shook/assets/70891072/ef904f3b-c37d-49b2-a2ed-7575f3a61ce0)

2023-08-14 07:42 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
> +
원래는 like과 deleteLike 메서드가 분리되어 있기 때문에, 각 메서드 "좋아요 상태를 무엇으로 변경하는가"를 명시적으로 보여주기 위해서였어요!

내부적으로 바뀌어 버리면 변경하는 입장에서 '지금 좋아요가 무엇으로 바뀌는가' 에 혼동이 올 수도 있다고 생각했습니다 ㅎㅎ

그런데 또 오히려 외부에서 직접 값을 설정해준다는 것이 위험할 수도 있겠네요 (Like 도메인이 안에 가지는 필드가 어떤 타입인지 밖으로 노출되는 것이기도 하니까요... ) 

이 부분은 조금 더 고민해보겠습니다! 감사합니다~~~

2023-08-14 07:43 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
> +        + "GROUP BY s.id")
👏👏👏👏 박수갈채

2023-08-14 07:44 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/AdminSongController.java
> +        return ResponseEntity.created(URI.create("/" + savedSongId)).build();
앗 저는 현재 요청이 들어온 API URL의 뒤에 붙는 값이라고 생각을 해서 저렇게 명시했는데, 생각해보니 또 프론트엔드 입장에서는 ip주소 뒤에 붙는 URL로 생각할 수도 있겠네요!! 

프론트엔드와 이야기 해보고 변경하겠습니당 🙇 🙇

2023-08-14 07:45 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/KillingPartCommentController.java
> +@RequestMapping("/songs/{song_id}/parts/{killing_part_id}/comments")
저도 똑같은 생각을 했었는데요 ㅎㅎㅎ 뭔가 예전에 계층을 따지면 songs > killingParts > comments 로 생각해서 URL을 결정했던 것 같아서 우선은 변경하지 않았습니다 😿 

이것도 프론트, 백에서 같이 이야기 해보고 결정해요!!

2023-08-14 07:45 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/KillingPartLikeController.java
> +@RequestMapping("/songs/{song_id}/parts/{killing_part_id}/likes")
위 코멘트와 동일합니다~

2023-08-14 07:45 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/SongController.java
> +    public ResponseEntity<SongResponse> showSongById(@PathVariable(name = "song_id") Long songId) {
이 악물고 신경썼는데 결국 놓친게 있었다니,, 감사합니다 눈썰미가 어마어마하네요 👍

2023-08-14 07:50 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/application/killingpart/KillingPartCommentServiceTest.java
> +    private static final long UNSAVED_PART_ID = 10L;
헉 drop table을 해도 이런 상황이 생길 수 있군요...! Long.MAX_VALUE 좋습니다 감사합니다 👍 👍

2023-08-14 07:51 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/application/killingpart/KillingPartLikeServiceTest.java
> +class KillingPartLikeServiceTest extends UsingJpaTest {
😊  부끄러워용 😊

2023-08-14 07:51 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartsTest.java
> +    @ParameterizedTest
😊 부끄러워용 😊

2023-08-14 07:53 UTC, seokhwan-an requested changes
일단 빠른시가내에 엄청난 코드량을 작성하신 바론 고생하셨습니다! 저는 의견과 궁금한 것과 형식 수정할 부분에 대해서 리뷰를 남겼습니다. 리뷰 확인해주세요☺️

2023-08-14 07:53 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/song/ui/HighLikedSongControllerTest.java
> +        );
이런 메소드를 지원하는 군요 처음 배워나갑니다 👍👍

2023-08-14 07:53 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/ui/KillingPartLikeController.java
> +@RequestMapping("/songs/{song_id}/parts/{killing_part_id}/likes")
저도 이 부분에 대해 동의합니다

2023-08-14 08:01 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
> +            .orElseThrow(MemberException::new);
지금 확인해보니 이미 소셜로그인 PR에 MemberNotExistException이 정의되어 있네용

이 부분은 TODO로 남겨두고 추후 merge 된 후에 변경하겠습니다!

2023-08-14 08:04 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
> +
💡 가독성을 위해 createdAt 밑에 두기로 결정했었다고 해서 변경했습니다!

2023-08-14 08:05 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
> +
ENUM 등을 사용해서 true, false 값을 명시적으로 포장하는게 아니라면 지금 상황에서는 베로가 이야기한 내부에서 바꾸는 방식이 더 좋을 것 같아요 ㅎㅎ 변경하겠습니다~

2023-08-14 08:06 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/AdminSongController.java
> +        return ResponseEntity.created(URI.create("/" + savedSongId)).build();
💡 해당 API는 관리자가 직접 노래를 등록하는 상황에서 사용되는 값이라 Location 헤더가 필요없다는 결론이 났습니다 🥲

2023-08-14 08:11 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
> +            .orElseThrow(MemberException::new);
좋습니다 👍 👍 👍

2023-08-14 08:12 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +
감사합니다 🤗

2023-08-14 08:14 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +    }
![image](https://github.com/woowacourse-teams/2023-shook/assets/70891072/6fa1a60a-78bd-4bdf-bd9c-b9adf81cffa5)

현재 저희 DB 상에 추가된 데이터가 총 40개여서 페이지네이션을 고려하지 않기 위해 40개 반환으로 고정했다고 생각했는데요, 혹시 데이터가 더 많은 상황에서도 40개로 제약을 두자는 의미였을까요?

2023-08-14 08:18 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/KillingPartLikeController.java
> +}
공백이 한 줄도 아니고 두 줄이나 들어갔네요 감사합니다 🤗

2023-08-14 08:19 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/SongController.java
> +    public ResponseEntity<SongResponse> showSongById(@PathVariable(name = "song_id") Long songId) {
추가 완료했습니다~~~~

2023-08-14 08:22 UTC, splitCoding reviewed
여러가지 생각을 많이 해야하는 기능에 대한 구현이였을 것 같아요!!😁

너무 고생많았어요 바론!!👍

좋아요 기능에서 정상적이지 않은 상황들을 예외로 처리하지 않고 의도하지 않은 상황은 무시하는 방법을 택한 이유에 대해서 한번 들어보고싶어요!!

2023-08-14 08:22 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/ui/AdminSongController.java
> +        return ResponseEntity.created(URI.create("/" + savedSongId)).build();
생성된 노래에 대한 정보 조회가 가능한 실제 URI를 넣으면 좋을 것 같습니다!!
(물론 없어도 저는 좋아요~)

2023-08-14 08:22 UTC, splitCoding commented on backend/src/test/java/shook/shook/song/application/killingpart/KillingPartLikeServiceTest.java
> +class KillingPartLikeServiceTest extends UsingJpaTest {
대단합니다!!👍

2023-08-14 08:28 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
> +    private boolean isDeleted;
저도 soft delete를 하면 쿼리할 때 마다 where 조건을 걸어주어야 하는게 번거로워서 delete / insert와 고민을 많이 했는데요,,!

1. 변동될 가능성이 큰 좋아요 데이터는 매번 삭제, 새롭게 추가하기 보다는 기존에 존재하는 데이터를 변경하는 간단한 쿼리만 보내는 것이 더 성능상 이점이 있을 것이라 생각했습니다. (update 쿼리가 delete 쿼리보다 마이크로초 단위로 더 빠르다고 하네용)
2. 이번 스프린트 기능을 정할 때 "수집한 파트 데이터, 수집한 투표 데이터 : 킬링파트 수집 이벤트 종료시 soft delete" 라는 사항을 정했었어요! 이처럼 사용자로부터 얻은 데이터는 soft delete를 하는 것이 맞다고 생각해서 soft delete를 사용했습니다 ㅎㅎ

2023-08-14 08:29 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/ui/HighLikedSongControllerTest.java
> +        );
지선생님 덕분입니다.

2023-08-14 08:34 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +    public long register(final SongWithKillingPartsRegisterRequest request) {
해당 메서드에서는 저장된 Song의 id를 반환하고 있어요!
Song 데이터가 등록된 후 성공적으로 저장이 되었다면, id가 nullable하지 않기 때문에 굳이 wrapper로 감쌀 필요가 없다고 생각했었는데요....

생각해보니 애초에 Song의 id 필드가 wrapper라서 primitive로 반환하는건 오히려 불필요한 언박싱이 일어나는거네요  wrapper로 수정하겠습니다 ㅎㅎ

2023-08-14 08:37 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/dto/SongWithKillingPartsRegisterRequest.java
> +    public Song toSong() {
정말 취향 차이의 영역이라고 생각하지만 `to` 라는 이름을 쓴건 Request를 엔티티로 변환한다 라는 의미를 드러내기 위해서였습니다!

해당 DTO 내에서 별도의 비즈니스 로직 없이 변환로직만 가지고 있으니 그런 의미가 더 잘 보이면 좋을 것 같았어요 ㅎㅎ

혹시 어떻게 생각하시나요?

2023-08-14 08:49 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
> +        if (killingPart.findLikeByMember(member).isPresent()) {
delete 메서드에서는 findLikeByMember 로 Optional<Like> 를 찾아온 후, 존재한다면 찾은 like를 like/unlike 하는 로직이라 Optional을 반환해야합니다! ㅎㅎ

저도 메서드 참조가 오히려 의미를 파악하기 더 어렵게 만드는 것 같아서 람다 형식으로 바꿨습니다~

2023-08-14 08:59 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLikes.java
> +
동의합니다~~ 
- 악의적인 사용자의 API 직접 요청
- 잘못된 API 호출

2023-08-14 09:34 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +    }
넵~~! 이제는 많은 노래 데이터가 생기게 될 시점이 온 것 같아서 많은 데이터가 있을 때에도 어떻게 처리를 해야할 지 고려해보면 좋을 것 같네요 이 부분은 내일 모여서 이야기 나눠보면 좋을 것 같아요!

2023-08-14 09:35 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
> +
이 부분이 persist가 되지 않은 상황에서 getCreateAt을 하는 경우에 npe가 발생해서 필드초기화를 해주었네요. 이 리뷰는 무시해도 될 것 같습니다!

2023-08-14 10:18 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/KillingPartCommentController.java
> +}
이 부분은 API URL이 확정되는대로 반영하겠습니다~! 🙇

2023-08-15 03:02 UTC, Cyma-s approved these changes
2700줄의 변경사항... 바론 폼 미쳤네요
더 추가할 부분은 없는 거 같아용 approve 하겠습니다 👍🏻

2023-08-15 03:06 UTC, seokhwan-an approved these changes
바론 리뷰 반영하신거 확인했습니다 고생 많으셨습니다:)

2023-08-15 03:37 UTC, splitCoding approved these changes
수고많앗어요 바론!! 😊

2023-08-15 03:40 UTC, merged