Feat/#382 EditProfilePage 구현 및 회원 탈퇴 기능 추가
woowacourse-teams/2023-shook pull request #392
Opened 2023-09-10 13:51 UTC by ukkodeveloper

## 📝작업 내용
![editprofilepage](https://github.com/woowacourse-teams/2023-shook/assets/109048739/48970f73-338a-4703-ba0f-a643418ae580)

1. 회원탈퇴 기능을 위해, 프로필 편집 페이지를 구현했습니다. 현재 프로필 닉네임이나 소개의 경우 변경할 수 없기 때문에, disabled 처리 했습니다.
2. 회원 탈퇴 모달을 구현했습니다. 회원 탈퇴의 경우 취소를 primary 색으로 하긴 했는데, 이렇게 해도 괜찮은 지 의견을 듣고 싶습니다.
3. 회원 탈퇴 시에 delete 요청을 보낸 다음, localstorage 에 accessToken을 비우고 전역 상태를 초기화해주었습니다.

## #️⃣연관된 이슈

close #382

2023-09-10 16:22 UTC, Creative-Lee requested changes
고생 많으셨어요 우코 짱코!😀
이미 만들어진 페이지에 코드 스타일 맞춰가며 기능을 얹는 거라 더 힘들었을텐데 정말 감사합니다~
코멘트 확인해주시고 재요청주세요~

2023-09-10 16:22 UTC, Creative-Lee commented on frontend/src/pages/EditProfilePage.tsx
> +      <TextArea value={''} disabled maxLength={100} />
![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/9e4052b7-5ed2-4bc1-a9c0-0031ca89ab5e)

textArea 리사이징을 못하도록 막아주면 좋을 것 같네요~

2023-09-10 16:22 UTC, Creative-Lee commented on frontend/src/pages/EditProfilePage.tsx
> +  font-size: 28px;
💬 모바일기기에서 직접 봐보니, 전체적으로 font가 큰것 같아요. 
사용된 text 사이즈가 28, 20px 이던데 PC에서는 괜찮지만, 모바일에서는 다소 큰 font size 같아요!
전체적으로 사이즈를 조정하면 어떨까요?

2023-09-10 16:22 UTC, Creative-Lee commented on frontend/src/pages/EditProfilePage.tsx
> +const SubTitle = styled.h3`
`닉네임`, `소개`는 input의 label 역할인 것 같아요. h3보다 label태그를 사용해보면 어떨까요?
접근성에도 좋을 것 같습니다~

2023-09-10 16:22 UTC, Creative-Lee commented on frontend/src/pages/MyPage.tsx
> +import ROUTE_PATH from '@/shared/constants/path';
여기도 만든 경로 상수 사용하면 되겠어요!

2023-09-10 16:22 UTC, Creative-Lee commented on frontend/src/pages/MyPage.tsx
> +  const editProfileRedirect = () => {
버튼을 눌러 단순히 페이지 이동을 하는거라면, redirect 라고 부르기에는 다소 어색한것 같아요.
ex) goXXXPage, 같은 단순한 네이밍도 괜찮겠네요!

💬 Link 태그를 사용하지 않고 함수를 만들어 Button에 바인딩하신 이유가 있나요~?
페이지 이동 외에 추가적인 작업이 없다면 Link 태그를 사용해도 될것 같아요~

2023-09-10 16:22 UTC, Creative-Lee commented on frontend/src/router.tsx
> +        path: `${ROUTE_PATH.EDIT_PROFILE}`,
👍

2023-09-10 16:22 UTC, Creative-Lee commented on frontend/src/shared/constants/path.ts
> +  EDIT_PROFILE: 'my-page/edit',
👍 굿

2023-09-10 16:22 UTC, Creative-Lee commented on frontend/src/features/profile/components/WithdrawalModal.tsx
> +  color: #b5b3bc;
💬💬💬 저희 컬러칩에 비슷한 색상 없던가요? ㅋㅋㅋㅋㅋㅋ 색이 많아져서 큰일이네요 🤣🤣🤣

2023-09-11 01:08 UTC, ukkodeveloper commented on frontend/src/pages/MyPage.tsx
> +  const editProfileRedirect = () => {
아 그렇긴하네요. 우선 핸들러 함수명을 editProfileRedirect에서 redirectEditPage로 변경했습니다. 

1. 버튼 태그를 이용한 이유 : 코드를 보면 프로필 편집과 로그아웃 버튼이 있습니다.  도밥이 말씀하신것처럼 페이지 이동 외에 추가적인 작이 없으면 Link태그를 쓰는게 좋다는 의견에 완전 동의합니다. 이미 로그아웃 버튼 스타일링이 구현되어 있는데, 굳이 Link태그(a태그)로 변경하면 그만큼 스타일링에 시간을 사용해야 합니다. a태그와 button태그를 구분하는 일이 그만큼 가치있는 일은 아니라고 생각합니다. 
2. redirect도 좋고 go도 좋습니다. 하지만, 이미 logoutRedirect라고 함수명이 지어져있는데, 굳이 go라고 해야할 필요를 못 느꼈습니다. go나 redirect나 의미 전달에 큰 차이가 없다고 생각하고, 기존에 구현되어 있는 방식을 따르는 게 오히려 통일성을 주는 것이라 판단했습니다.

2023-09-11 01:08 UTC, ukkodeveloper commented on frontend/src/pages/EditProfilePage.tsx
> +      <TextArea value={''} disabled maxLength={100} />
아주 좋구요!

2023-09-11 04:59 UTC, ukkodeveloper commented on frontend/src/pages/MyPage.tsx
> +  const editProfileRedirect = () => {
goXXPage 좋은 것 같아요! 해당 함수명으로 변경했고요. 저도 uri 이동 외에 다른 일을 하지 않아 Link가 더 적절하다곤 생각하지만, 그렇다고 반드시 구분해야 할 정도인 지는 모르겠습니다. 따라서 해당 프로필 편집 UI가 로그아웃 버튼과 동일하기 때문에 재사용하는 게 더 낫다고 판단했습니다.

2023-09-11 06:00 UTC, Creative-Lee approved these changes
코멘트 반영 확인했습니다~ 고생 많으셨습니다~

2023-09-12 18:35 UTC, merged