Feat/#431 노래 상세 페이지에 스와이프 코치 마크를 구현한다
woowacourse-teams/2023-shook pull request #432
Opened 2023-09-19 11:57 UTC by cruelladevil

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명(이미지 첨부 가능)

<img width="304" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/cac17af6-95a0-4be6-ba62-78a80d2182c8">

## 💬리뷰 참고사항

> 원활한 리뷰를 위해 전달하고 싶은 맥락(특정 파일, 디렉터리 등등)  
> 리뷰어가 특별히 봐주었으면 하는 부분

CoachMark 컴포넌트의 경우 기존 Modal 컴포넌트와 거의 동일합니다.

- backdrop에 onClick 이벤트로 있던 closeModal을 지웠습니다.
- Container의 backbround-color와 border를 삭제하였습니다.

이 2가지 차이밖에 없기 때문에 Modal 컴포넌트를 조금 수정한다면 재사용 가능할 듯 합니다.
일단 코치 마크에 대한 피드백을 받기위해 프로토타입을 빠르게 올려봅니다!
스와이프 설명에 대해서 이정도면 충분할지 검토 부탁드립니다~

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #431

2023-09-20 00:40 UTC, Creative-Lee requested changes
너무 좋습니다~ 
설명 충분한것 같고, 백드랍이 조금 더 어두워도 좋을 것 같아요~
완성 지어서 다시 올려주세요~~ 기대가 됩니다😀

2023-09-20 00:40 UTC, Creative-Lee commented on frontend/src/shared/components/CoachMark.tsx
> +  children: ReactElement | ReactElement[];
💬 children type을 재정의한 이유가 있나요~?

2023-09-20 12:22 UTC, ukkodeveloper approved these changes
코난 고생쓰 많았어요!! 지금도 충분히 잘 만드신 것 같아서 approve하겠습니다. 커멘트만 확인해주세용. 그리고 해당 코치마크를 언제까지 보여줄 지 함께 정해보아요. (매번 보여줄 순 없으니까요)
예를 들면, 비로그인 유저에게만 보여주고, 첫 번째 노래를 들을 때에만 딱 한번 보여주도록 하는 거죠. sessionStorage나 자바스크립트 변수에 flag를 저장할 수도 있을 것 같네요.

2023-09-20 12:22 UTC, ukkodeveloper commented on frontend/src/shared/components/CoachMark.tsx
> +  background-color: rgba(0, 0, 0, 0.5);
뒷배경만 더 어둡게하면 될 것 같습니다 코난!

2023-09-20 12:22 UTC, ukkodeveloper commented on frontend/src/pages/SongDetailListPage.tsx
> +        <div style={{ fontSize: '18px' }}>위 아래로 스와이프하여 노래를 탐색해보세요!</div>
인라인으로부터 해방시켜 주세요! 😢

2023-09-21 10:25 UTC, cruelladevil commented on frontend/src/shared/components/CoachMark.tsx
> +  children: ReactElement | ReactElement[];
Modal 특성상 children이 null이 아니어야되고,
ReactElement만 들어오도록 하는 것이 좋을 것 같아
해당 타입으로 지정하게 되었는데 더 좋은 생각이 있다면 공유해주세요!

2023-09-21 10:38 UTC, cruelladevil commented
CoachMark 컴포넌트를 Modal 컴포넌트로 대체하였습니다.
Modal 컴포넌트로 대체하면서 Modal 컴포넌트의 변경사항이 있습니다. ([6b2c168](https://github.com/woowacourse-teams/2023-shook/pull/432/commits/6b2c168534e0a4957d55a34affc1ebd7e2b8c783))

1. 백드랍이 조금 더 어두었으면 좋겠다는 의견을 반영하여 알파값을 `0.5`에서 `0.7`로 수정하였습니다.
2. css prop을 받도록하여 Container에 추가적인 css를 적용할 수 있도록 하였습니다.

이를 통해 코치마크를 보여주는 Modal에는 background-color를 transparent로 주었습니다.
또한 localStorage의 onboarding 키로 처음 접속할 때만 코치마크가 보이도록 하였습니다!

2023-09-21 11:45 UTC, merged

2023-10-01 14:56 UTC, Creative-Lee commented on frontend/src/pages/SongDetailListPage.tsx
> +  const [onboarding, setOnboarding] = useLocalStorage<boolean>('onboarding', true);
💬 순수하게 storage의 value만 필요할 때에는 새로운 로직을 만들어야할 것 같아요.
storage 유틸을 만들고, useOnboarding과 같은 hook으로 분리하는 방법도 있을 것 같네용