Feat/#425 카카오 소셜 로그인을 구현한다.
woowacourse-teams/2023-shook pull request #434
Opened 2023-09-20 04:20 UTC by seokhwan-an

## 📝작업 내용

이번에 카카오 소셜 로그인을 구현하고 기존의 구글 소셜 로그인과 추상화하는 작업을 진행했습니다. 그리고 카카오 소셜 로그인과 구글 소셜 로그인이 공존하면서 발생했던 문제점이 하나 있었습니다. 이 부분에 대해서 스플릿과 이야기를 나누었는데 베로와 바론의 의견도 듣고 싶어서 상황설명을 하겠습니다.
1. 현재 구글 소셜 로그인을 통해 email을 받아왔고 이를 통해 사용자를 식별하는 것으로 이용했습니다.
2. 카카오 소셜 로그인은 email이 사용자 동의에 의해서만 email을 받아올 수 있습니다.
   - email을 가져오는 것을 필수로 하려면 검수를 받아야합니다.
3. 그래서 카카오는 플랫폼 id를 통해서 사용자를 식별하는 것으로 했습니다.
   - 카카오 닉네임으로 사용자를 식별할까 했는데 닉네임은 다른 사용자와 같을 수 있는 경우도 있고 사용자가 카카오 닉네임을 변경할 수 있는 어려움이 있었습니다.
4. 그래서 현재 테이블의 member의 email 열을 구글 소셜 로그인은 email을  카카오 소셜 로그인은 플랫폼 id를 저장하고 회원가입시 사용자를 식별하고 이용하는 방식으로 하고자 했습니다. 혹시 email 열의 이름을 무엇으로 바꾸면 좋은지와 혹시 이 방법 외에도 더 좋은 방안이 있다면 이야기 해주세요!

## 💬리뷰 참고사항

- 소셜 로그인 추상화를 해보았는데 그 부분을 집중적으로 확인 부탁드립니다!

## #️⃣연관된 이슈

- close #425

2023-09-20 07:04 UTC, somsom13 requested changes
고생하셨습니다 아코쨩!^^ 소셜로그인의 달인이 되셨군요.
몇 가지 질문과 피드백 남겼습니다! 

그리고 OAuthProvider 추상화는 아코가 고민하시는 걸 옆에서 봤고, 지금 제 지식으로는 더 좋은 방법이 떠오르지 않아서 피드백 남기지 않았습니다. (✿◠‿◠)

2023-09-20 07:04 UTC, somsom13 commented on backend/src/main/java/shook/shook/member/application/MemberService.java
> +        return savedMember;
여기서 updateNickname을 기본 닉네임 + 고유 id 로 연결된 문자열 (ex. shook1203) 으로 구성되는 것이 맞나용?? 고유 id를 붙이는 이유가 사용자들의 닉네임이 중복되지 않게 하기 위한 것인가요?.?

2023-09-20 07:04 UTC, somsom13 commented on backend/src/test/java/shook/shook/auth/application/OAuthTypeTest.java
> +    private static Stream<Arguments> requestOauthTypeAndResult() {
👍

2023-09-20 07:20 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/ui/AuthController.java
> +//    }
이 부분 지웠어야 했는데 실수를 범했네요.. 몹시 부끄럽네요😥

2023-09-20 07:37 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/AuthService.java
> +    private final OAuthExecutionFinder oauthExecutionFinder;
바론이 말해준 네이밍이 더 와닿는 것 같습니다. 저는 실행기를 찾는다에 집중해서 Execution이라는 네이밍을 이용했었습니다. 네이밍은 항상 어렵네요..😥

2023-09-20 07:48 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/AuthService.java
> +        final String memberInfo = oAuthInfoProvider.getMemberInfo(accessTokenResponse);
일단 이 `accessToken을 가져오는 것`과 `memberInfo를 가져오는 것`을 분리한 이유는 일단 두 기능 모두 Oauth에서 핵심이라고 생각을 해서 분리를 했습니다. 그리고 `accessToken을 가져오는 것`에 대한 메소드를 public으로 둔 이유는 AuthService에서 이 흐름을 명시해주어서 oauth의 흐름이 더 쉽게 파악할 수 있을 것 같다는 생각을 했었습니다. 또한 각각 기능 모두 핵심이다보니 테스트를 진행하기 위해서 Public으로 두고 테스트를 진행했던 이유도 있습니다.(물론 현재는 RestTemplate을 mock으로 두고 예외테스트만 진행하고 있습니다.)

2023-09-20 08:05 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/GoogleInfoProvider.java
>          }
그 부분까지 고려하지 못했었네요. 일단 여기는 외부 api를 이용해서 요청을 보내고 응답을 받는 과정이기 때문에 null이 넘어오는 상황이 없다고 생각을 했습니다. 즉, null이 넘어온다는 것은 이미 서버 error가 발생한다라고 생각을 했고 이는 이미 try catch를 통해서 처리를 하고 있어서 이 부분을 고려하지 않았었네요  null `requireNonNull`을 이용한 만큼 이 부분도 예외처리를 추가하겠습니다!

2023-09-20 08:50 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/KakaoInfoProvider.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
현재 이 부분은 `googlelnfoProvider`와 `kakaoInfoProvider` 에서 모두 공통으로 이용되고 있는데 이 둘을 추상화한 OAuthInfoProvider에서 이용할 수 있게 하려면 public으로 두어야 하는 상황인데 이 부분에 대해서는 어떻게 처리하면 좋을까요?

2023-09-20 14:30 UTC, Cyma-s approved these changes
크게 변경점은 없어서 어프루브했습니다!
email 관련된 부분은 `providerId` 같은 컬럼으로 두고, 플랫폼을 저장하는 `provider` 열을 추가하는 건 어떨까요?

2023-09-20 14:30 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/application/KakaoInfoProvider.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
해당 상수는 HttpHeaders 에 정의되어 있는 상수인데, 재정의하지 않고 해당 상수를 쓰는 것에 대해서는 어떻게 생각하시나요??

2023-09-20 14:30 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/application/KakaoInfoProvider.java
> +            headers.set(HttpHeaders.CONTENT_TYPE, "application/x-www-form-urlencoded;charset=utf-8");
이 부분도 상수를 사용해서 변경해볼 수 있을 것 같은데 어떤가요??

2023-09-20 14:30 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/application/dto/KakaoMemberInfoResponse.java
> +    private Long id;
필요한 필드가 스네이크 케이스로 되어 있지 않더라도 JsonProperty 를 붙여주어야 하나요?

2023-09-20 14:30 UTC, Cyma-s commented on backend/src/main/java/shook/shook/member/application/MemberService.java
> +        return savedMember;
중복 닉네임을 막기 위해서라면 UUID 를 사용하면 되지 않을까요?!

2023-09-21 07:59 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/KakaoInfoProvider.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
AUTHORIZATION 헤더는 HttpHeaders에 정의된 상수를 이용했습니다 혹시 `Bearer`과 `authorization_code` 도 정의 되어 있는 것인지 궁금합니다. 저는 찾아도 안나타나네요.

2023-09-21 08:01 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/KakaoInfoProvider.java
> +            headers.set(HttpHeaders.CONTENT_TYPE, "application/x-www-form-urlencoded;charset=utf-8");
이 부분도 상수로 빼겠습니다!

2023-09-21 08:38 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/member/application/MemberService.java
> +        return savedMember;
현재는 db의 i로 하는 것이 중복되는 가능성이 없어서 했는데 더 고민해볼께요

2023-09-21 08:39 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/application/dto/KakaoMemberInfoResponse.java
> +    private Long id;
불필요한 JsonProperty 제거하겠습니다!

2023-09-21 09:38 UTC, merged