Feat/#429 장르 카테고리 조회 API 구현
woowacourse-teams/2023-shook pull request #439
Opened 2023-09-20 13:38 UTC by Cyma-s

## 📝작업 내용

장르 카테고리 조회 API 구현

## 💬리뷰 참고사항
- TOP COUNT 는 100에서 10으로 변경했습니다.
- 모든 장르 카테고리 조회 기능들은 InMemorySongs 에서 조회합니다. 
- 모든 좋아요 스와이프 조회 API 들은 `/songs/high-liked/` prefix 로 조회할 수 있게 했습니다.

## #️⃣연관된 이슈

close #429

2023-09-20 15:00 UTC, somsom13 reviewed
베로~~~~~ 짧은 시간 내에 엄청나게 많은 양의 구현을 하셨군요... 고생하셨어요!!
역시 슉 답게 개발 속도도 슉이네요 ☆⌒(*＾-゜)v

코드를 보다보니 뭔가 전체적인 API 설계, 구조에 대한 코멘트가 많아진 것 같아요 ㅋㅋㅋ 
그런데 현재 코드가 지금 당장 서비스가 흘러가는데는 문제가 없고, 저도 코드로 직접 작성했을 때는 생각한대로 구현이 될지 모르겠음 + 더 깔끔한 코드가 될거라는 자신이 없어서.. 
이런 코멘트들은 우선은 '그냥 이런 생각이 들었어요~' 정도로만 넘기면 좋을 것 같아요 ㅎㅎ 제가 직접 두들겨보고 다시 제안드리러 오겠습니다 ^___^

수정 요청보다는 질문 + 고민이 더 많아서 애매한 Comment로 남기겠습니다 ㅎㅎ

고생많으셨어요~!~!! 
( •_•)>⌐■-■ 
ヾ(⌐■_■)ノ♪

2023-09-20 16:44 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/ui/SongSwipeController.java
> +    public ResponseEntity<SongSwipeResponse> showSongsWithGenreForSwipe(
저도 바론의 리뷰를 보고 고민을 해보았는데요 `@RequestParam`의 속성인 `required`를 false를 두고 service단에서 requestParam의 값이 없는 경우에는 전체 노래에 대해서 처리하고 requestParam이 존재하는 경우에는 그 장르에 대해서 처리를 하면 될 것 같다는 생각이 듭니다!

2023-09-20 16:48 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +    private static final int BEFORE_GENRE_SONGS_COUNT = 10;
저는 이 둘은 화면 구성에 따라 보여지는 노래의 개수가 달라질 수 있는 상황이 있다고 생각해서 분리해서 관리하는 것도 좋은 방안이라고 생각합니다.

2023-09-20 17:25 UTC, seokhwan-an requested changes
베로 빠른시간에 필요한 기능을 구현하신 것 좋습니다!👍
빠른 구현 능력이 부럽네요
앞서서 바론이 리뷰를 야무지게 해주어서 저는 소소한 리뷰에 대해 남겨보았습니다

2023-09-20 17:25 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/Genre.java
> +
노래 데이터가 많아지고 분류가 어려운 노래같은 경우 ETC로 분리되는 상황도 있을 것 같습니다!

2023-09-20 17:34 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +        final List<Song> top10Songs = songs.subList(0, Math.min(GENRE_SONG_COUNT, songs.size()));
제 기억상으로도 스와이프 노래를 가져올 때 inMemorySongs에 개수를 주어지고 내부적으로 sublist로 구현된 것으로 알고 있습니다!

2023-09-20 17:41 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +    public SongSwipeResponse findSongsByGenreForSwipe(
앞서서 Controller에서 말한 것과 같이 requestParameter를 required 속성을 false로 하여  genreName의 값이 존재하는지로 파악하여 분기 처리하면 한 메소드로도 관리가 될 수 있다고 생각합니다.

2023-09-20 17:45 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +    public SongSwipeResponse findSongsByGenreForSwipe(
requestParam의 required 속성이 false이고 값이 안들어오게 되면 그 부분은 null로 된다고 하네요.. null로 들어온 것을 하위에서 처리하는 것이 좋은 방안이 될지는 고민이 됩니다.

2023-09-21 06:35 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +    private static final int BEFORE_GENRE_SONGS_COUNT = 10;
딱히 생각은 안 하고 분리했는데 합치는 게 낫겠네요 👍

2023-09-21 06:35 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/SongService.java
> +        final List<Song> top10Songs = songs.subList(0, Math.min(GENRE_SONG_COUNT, songs.size()));
데이터베이스에 Pageable 을 전달하는 것처럼 생각한다면 InMemorySongs 에서 처리하는 게 맞는 것 같아 모든 subList 로직은 InMemorySongs 로 옮겨두었습니다.

2023-09-21 06:35 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/dto/KillingPartResponse.java
> +    public boolean getLikeStatus() {
레거시 코드였네요 바로 삭제했습니다 👍🏻

2023-09-21 06:35 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/Genre.java
> +
저도 분류가 어려운 노래의 경우에는 ETC가 존재해도 나쁘지 않을 것 같아요. 일단은 남겨두는 쪽으로 진행할게요 :)

2023-09-21 06:35 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +            .toList());
`toList` 로 만들어지는 리스트는 `unmodifiableList` 이기 때문에 새롭게 만들어주지 않으면 정렬이 안 되더라고요 😂 그래서 새롭게 `new ArrayList` 를 해주었는데 혹시 바꿀 방법이 있으려나요 🤔

2023-09-21 06:35 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/HighLikedSongController.java
> +    @GetMapping(params = "genre")
ㅋㅋㅋㅋㅋㅋ 바론이잖아요 ^^

2023-09-21 06:35 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/HighLikedSongController.java
> +            songService.findSongsByGenre(genre);
매의 눈이네요 🦅 예전에 설정이 잘못되어 있어서 개행됐나봐요 
바로 변경했습니다!

2023-09-21 06:35 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/SongSwipeController.java
> +    public ResponseEntity<SongSwipeResponse> showSongsWithGenreForSwipe(
아코가 말씀해주신 내용도 좋긴 한데, requestParam 이 추후 추가되는 경우 if 문이 증식할 것 같더라고요. 쿼리 파라미터를 좀 더 깔끔하게 처리할 수 있는 방법을 저도 좀 더 고민해보겠습니다.

2023-09-21 06:35 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/ui/openapi/SongSwipeApi.java
> +@Tag(name = "Song", description = "노래 조회 API")
어떻게 찾으셨죠 ㄷㄷ 🦅

2023-09-21 06:35 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartRepositoryTest.java
> +            new Song("제목", "비디오ID는 11글자", "이미지URL", "가수", 30, Genre.findByName("DANCE"), KILLING_PARTS));
아 이거 from 을 삭제했던 적이 있었는데 아직 남았었네요;;; 다시 돌려놓겠습니다!!!!

2023-09-21 08:22 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/ui/HighLikedSongController.java
> +            songService.findSongsByGenre(genre);
Eagle Eye

2023-09-21 08:25 UTC, seokhwan-an approved these changes
전체적으로 크게 수정할 부분은 없어서 어프로브 드립니다 고생하셨습니다!

2023-09-21 08:25 UTC, splitCoding approved these changes
👍

2023-09-21 09:06 UTC, merged