Feat/#472 스와이프시 url이 변경되도록 한다.
woowacourse-teams/2023-shook pull request #485
Opened 2023-09-29 08:25 UTC by cruelladevil

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명(이미지 첨부 가능)

![Kapture 2023-09-29 at 17 09 50](https://github.com/woowacourse-teams/2023-shook/assets/87710730/ffc1ac2b-7374-4d43-b0db-81b90d54b594)

## 💬리뷰 참고사항

> 원활한 리뷰를 위해 전달하고 싶은 맥락(특정 파일, 디렉터리 등등)  
> 리뷰어가 특별히 봐주었으면 하는 부분

d0fffbb2b0d0d075f73c784e8db8d915d3ad942e - 이 커밋에 기록한 사항인데, Youtube 컴포넌트의 [createPlayerOnObserve](https://github.com/woowacourse-teams/2023-shook/blob/main/frontend/src/features/youtube/components/Youtube.tsx#L17)가 페이지를 빠져나갈때 컴포넌트 갯수만큼 실행됩니다.
처음에 해당 함수와 함께 url을 바꾸는 것으로 진행하다가 알게된 사실인데 원인은 분석하지 못했습니다.
이후 Youtube 컴포넌트가 PartCollectingPage에서도 사용됨을 인식하고 SongDetailItem에서 div 태그를 하나 만들어서 거기에 ref를 주어서 구현하였습니다. (https://github.com/woowacourse-teams/2023-shook/commit/16c1219ae20dfe6a125d34089674458468fcb36e)

![Kapture 2023-09-29 at 17 18 06](https://github.com/woowacourse-teams/2023-shook/assets/87710730/558103b4-e19b-4265-8e6d-3aee2ce404be)

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #472

2023-09-29 15:15 UTC, ukkodeveloper approved these changes
dev 서버에서 잘 동작하는 거 확인했습니다. 스와이프 하면서 observer을 많이 사용하게 되긴 하네요 😢 고생 많으셨어요! 특히 navigate 옵션 너무 잘 적용해주신 것 같아요!

2023-09-29 15:15 UTC, ukkodeveloper commented on frontend/src/features/songs/components/SongDetailItem.tsx
> +          preventScrollReset: true,
미쳤네요 ㅋㅋㅋㅋㅋㅋ 이런 것도 있다니 대단합니다!

2023-09-29 19:24 UTC, Creative-Lee requested changes
좋은 방향으로 해결해 주셨네요!
고생많으셨습니다 코난! 리뷰 확인해주시고 재요청주세요!

2023-09-29 19:24 UTC, Creative-Lee commented on frontend/src/features/songs/components/SongDetailItem.tsx
> +        <div ref={navigateToCurrentSongId}>
![코난 uri 먹튀](https://github.com/woowacourse-teams/2023-shook/assets/77152650/2f0e6c8b-2388-49f2-9f85-d524c91d0b02)

요거 observer target의 범위가 페이지 단위라, 사용자가 스와이프 내리려다가 다시 돌아오면 url만 바뀌어있어요!
observer target의 범위를 줄이면 좋을 것 같네요.

💬 추천 KillingPartInterface의 jsx 시작부에 있는 옵져버에 콜백으로 같이 넣는거 어때요?
스와이프 시 노래 멈추게 하는 옵저버인데, Dom의 위치가 모바일 기준 딱 화면 정 가운데라 먹튀 당할일이 거의 없습니다!
마침 해당 컴포넌트에도 songId가 있답니다.

제가 추천한 DOM으로 변경하신다면, 리팩토링이 조금 필요할거에요...ㅎ

![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/e9a1c7ab-5bfb-4485-b857-de06680776e1)

2023-09-30 14:11 UTC, cruelladevil commented on frontend/src/features/songs/components/SongDetailItem.tsx
> +    const { genre } = useParams();
<img width="513" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/33ea8534-7183-4488-96cc-7bfef42ab1c3">

사용하신 예제를 봤는데 어떤 타입을 추론해준다는 건가용?

2023-09-30 14:14 UTC, cruelladevil commented on frontend/src/features/youtube/components/Youtube.tsx
> +  videoId: string;
default value가 있는 값을 앞으로 빼내려고 자리를 바꿨습니다!
타입에서는 안바꿔도 됐을려나요😭

2023-09-30 14:14 UTC, cruelladevil commented on frontend/src/features/youtube/components/Youtube.tsx
> +const Youtube = ({ start = 0, videoId }: YoutubeProps) => {
> default value가 있는 값을 앞으로 빼내려고 자리를 바꿨습니다!

2023-09-30 14:33 UTC, cruelladevil commented on frontend/src/features/songs/components/SongDetailItem.tsx
> +        <div ref={navigateToCurrentSongId}>
> 💬 추천 KillingPartInterface의 jsx 시작부에 있는 옵져버에 콜백으로 같이 넣는거 어때요?

해당 위치도 테스트 해본 결과 스와이프를 아래로 내리다가 올리면 씹히는 경우가 생기더라구요.
그래서 최대한 하단쪽에 배치하면 넘어갔을때 변경된다고 생각하여 하단에 배치하였습니다.
이전으로 되돌리려다 다시 돌아와도 url 정상 변경 되구요.

✍️ 수정 커밋 - [52880d3](https://github.com/woowacourse-teams/2023-shook/pull/485/commits/52880d38a31d4fa9de0d3cc84962b62e9072d731)

2023-09-30 14:50 UTC, cruelladevil commented on frontend/src/features/songs/components/SongDetailItem.tsx
> +          preventScrollReset: true,
replace는 뒤로가기 했을때 이전 곡이 아닌 메인페이지에 가는게 사용성이 더 좋다고 생각했습니다.
preventScrollReset은 스크롤이 최상단으로 올라가는 것을 방지하는 속성인데
[ScrollRestoration](https://reactrouter.com/en/main/components/scroll-restoration) 컴포넌트를 사용할 때 해당되는 것 같아서 삭제하였습니다.

✍️ 수정 커밋 - [5f78e15](https://github.com/woowacourse-teams/2023-shook/pull/485/commits/5f78e150bd424fc583a9eeac34326130fcf68c1f)

2023-10-01 12:25 UTC, Creative-Lee commented on frontend/src/features/songs/components/SongDetailItem.tsx
> +    const { genre } = useParams();
설명으로 혼동을 드렸네용...

내부적으로
없는 param에 접근했을 때의 에러 처리 및 null을 걸러준 string 타입만 추론해준다는 말이었습니다.
외부에서 null 처리를 안해줘도되어용

2023-10-01 12:26 UTC, Creative-Lee commented on frontend/src/features/youtube/components/Youtube.tsx
> +  videoId: string;
아뇨오 ㅎㅎ 좋아요 잘 바꿔 주셨습니다~
그만한 이유가 있을 줄 당연히 알았어요ㅎㅎ

고냥 웃자고 짤올려봤슴다 ㅎ

2023-10-01 12:41 UTC, Creative-Lee commented on frontend/src/features/songs/components/SongDetailItem.tsx
> +        <div ref={navigateToCurrentSongId}>
개선 확인했습니다! 👍

2023-10-01 12:41 UTC, Creative-Lee approved these changes
개선사항 다 확인했습니다! 
ValidParams 훅 관련한 코멘트만 읽어주시면 됩니다~ 
고생하셨습니다!

2023-10-02 00:39 UTC, merged