Feat/#492 가수 검색 기능을 구현한다.
woowacourse-teams/2023-shook pull request #503
Opened 2023-10-12 07:23 UTC by Creative-Lee

## 📝작업 내용

### 서치 바 구현

기존 회의에서 정한 정책대로, Header에 고정적으로 표시될 서치 바를 구현했습니다.
**완성도를 위해 반응형 디자인, 애니메이션을 구현했어요.**
또한 정책 내에서 **사용자 편의성을 위한 몇가지 기능을 구현하였습니다.**

**디바이스에 따른 세부 동작에 대한 설명은 분기가 많아 commit msg로 정리해 두었습니다.**
이 [Commit](https://github.com/woowacourse-teams/2023-shook/commit/378e250918aa018c752396ad6ef0c879eefa0067)과  스토리북을 참고해 주세요.
msw에서 fixture 데이터를 응답하는 검색 키워드는 '악동', '악동뮤지션', '뮤지션' 입니다.
스토리북 확인하실 때 참고해주세요

## 💬리뷰 참고사항

- 전역적으로 사용하는 useFetch, Mutation에서 여러 Context를 사용하면서, 거의 모든 스토리가 동작하지 않고 있었어요.
또한 Router를 사용하는 컴포넌트에서는 추가 설정도 필요했습니다.
근본적인 해결은 로직을 변경해야 하는 부분이라 그대로 두고, 관련 설정만 다시 해 두었습니다.
빠른 시일 내에 개선해봐야겠네요.

**설정을 위해 `storybook-addon-react-router-v6`, `msw-storybook-addon` 를 설치했으니, 
본 PR 머지 후 작업하실 때 `npm ci` 해주시길 바랍니다.**

- 아래 코드 코멘트에 자세한 설명을 해 놓았으니, 꼭 읽어주시면 감사하겠습니다.

## #️⃣연관된 이슈

close #492

2023-10-12 07:24 UTC, Creative-Lee commented on frontend/.storybook/main.ts
> +  staticDirs: ['../public'],
msw worker.js 파일 경로 설정입니다.

2023-10-12 07:24 UTC, Creative-Lee commented on frontend/.storybook/preview.tsx
> +const customViewport = {
프로젝트 내부 breakpoint 스팩대로 viewport 추가하였습니다.

2023-10-12 07:24 UTC, Creative-Lee commented on frontend/.storybook/preview.tsx
> +initialize();
msw 실행 메서드에요

2023-10-12 07:27 UTC, Creative-Lee commented on frontend/src/features/auth/components/AuthProvider.tsx
> +const AuthProvider = ({ children }: PropsWithChildren) => {
provider 의 type이 `[]`로제한되어 있어서,
단일 children에 에러를 뱉었어요.
스토리북 decorators 설정시 상당히 불편했어서, 기본 타입으로 수정했습니다. 

💬 혹시 type으로 단일 children을 제한한 이유가 있을까요? 


``` ts
//  type error!
<AuthProvider>
  <One>
</AuthProvider>
```

2023-10-12 07:29 UTC, Creative-Lee commented on frontend/src/features/auth/hooks/LoginPopUpContext.tsx
> +  if (contextValue === null) throw new Error('LoginPopUpContext에 값이 제공되지 않았습니다.');
동일한 형식의 코드를 복붙할 때는 꼭 확인 부탁드립니다~!
잘못된 error message로 혼동이 와서 시간을 쫌 많이 썼어요 ㅠ

2023-10-12 07:34 UTC, Creative-Lee commented on frontend/src/features/search/components/ResultSheet.tsx
> +              onMouseDown={() => navigate(`${ROUTE_PATH.SINGER_DETAIL}/${id}`)}
onClick 이벤트로 구현하다가 onMouseDown 이벤트로 수정했어요.

상위 input의 blur 이벤트가 우선순위가 높아 먼저 적용 되어 onClick 이벤트가 실행되지 않았기에 가수 상세 페이지로 이동이 불가능 했었습니다.

PC 환경에서는 마우스를 드래그하여 취소하는 행동이 불가능 해졌지만,
모바일 환경에서 엄지를 가져다 댄대고 실행되지는 않는 것을 확인했어요.

이에대해 고민을 해보았고, input blur로 얻을 수 있는 사용성의 이점이 더 크다고 판단해서 onMouseDown으로 타협했습니다.

💬 나름의 트레이드 오프라고 생각했는데, 다른 의견이 있다면 말씀해 주세요

2023-10-12 07:34 UTC, Creative-Lee commented on frontend/src/features/search/components/ResultSheet.tsx
> +            <GoToDetail
접근성을 위해 li 하위에 버튼을 두었습니다.

2023-10-12 07:35 UTC, Creative-Lee commented on frontend/src/features/search/components/ResultSheet.tsx
> +const SheetTitle = styled(Flex)`
검색결과가 많을 경우에도 상단 타이틀은 고정되는 사용성을 위해 추가했습니다.

2023-10-12 07:38 UTC, Creative-Lee commented on frontend/src/features/search/components/SearchBar.tsx
> +const searchButtonStyles = css`
61번 라인부터 css 코드를 보실때는 [이 commit](https://github.com/woowacourse-teams/2023-shook/pull/503/commits/378e250918aa018c752396ad6ef0c879eefa0067)을 참고해 주세요.

디바이스에 따른 분기를 다 적어 놓았습니다.

2023-10-12 07:40 UTC, Creative-Lee commented on frontend/src/features/search/hooks/useSearchBar.ts
> +  useEffect(() => {
[feat: isSearching true 상태일 때 input focus 하는 effect 추가](https://github.com/woowacourse-teams/2023-shook/pull/503/commits/71d35a0eb443e927dc0a3c9389e72ebe27724b54) 커밋 참고해 주세요

2023-10-12 07:41 UTC, Creative-Lee commented on frontend/src/features/search/components/SearchBar.tsx
> +    visibility: ${({ $isSearching }) => !$isSearching && 'hidden'};
visivilty 속성에 대한 설명은 [이 commit](https://github.com/woowacourse-teams/2023-shook/pull/503/commits/0991a57fc49fa971f9ff5fefd71d91c8b32377f9) 과 [이 commit](https://github.com/woowacourse-teams/2023-shook/pull/503/commits/71d35a0eb443e927dc0a3c9389e72ebe27724b54)참고해 주세요

2023-10-12 07:45 UTC, Creative-Lee commented on frontend/src/features/search/remotes/search.ts
> +  const encodedQuery = encodeURIComponent(query);
검색 쿼리문에 &, = 등이 포함되면 올바르게 전달되지 않을 수 있다고 해요.


가수 이름에 `&` 포함되는 경우도 충분히 있기에  별도로 적용했습니다.

[참고](https://androman.tistory.com/27)

``` js
// ex
https://javascript.com?name=co&ding 

파라메터로 들어가는 name의 value에 &이 들어가므로
encodeURIComponent를 사용하여 인코딩 해줘야 한다.
```

2023-10-12 07:49 UTC, Creative-Lee commented on frontend/src/pages/SearchResultPage.tsx
작업 인계를 위한 구현1

2023-10-12 07:49 UTC, Creative-Lee commented on frontend/src/pages/SingerDetailPage.tsx
작업 인계를 위한 구현2

2023-10-12 07:50 UTC, Creative-Lee commented on frontend/src/shared/hooks/useValidSearchParams.ts
> +const useValidSearchParams = (...params: string[]) => {
기존에 설명드린 useValidParams와 비슷한 맥락으로 구현한 hook이에요

이번엔 **searchParams**를 편하게 사용하기 위해 구현했습니다.

2023-10-14 13:56 UTC, cruelladevil requested changes
검색 기능 구현하느라 고생하셨습니다 도밥!
스토리북에 자잘한 것까지 신경 써주셔서 한결 나아졌네요! 👍
검색창이 expanded 되었을때 로고가 살짝 튀어나오는건 어쩔 수 없는 건가용? 😭

2023-10-14 13:56 UTC, cruelladevil commented on frontend/package.json
> +    "storybook-addon-react-router-v6": "^2.0.7",
💬 storybook에서 react router가 필요한 이유가 있나요? 🤔
페이지를 넘나드는 단위의 스토리북은 작성하지 않기로 했었던 것 같은데,
필요하다고 생각드신다면 의견 이야기 해주세요! 😊

2023-10-14 13:56 UTC, cruelladevil commented on frontend/src/features/search/hooks/useSearchBar.ts
> +    ({ relatedTarget }) => {
👍 relatedTarget을 통해 검색 결과에 자동완성에 탭이 움직일 수 있도록 해주셨네요!!

2023-10-14 13:56 UTC, cruelladevil commented on frontend/src/features/search/components/SearchBar.tsx
> +      <SearchButton type="submit" $isSearching={isSearching} />
💬 이 버튼 저만 작동 안하나요..?

![Kapture 2023-10-14 at 22 50 32](https://github.com/woowacourse-teams/2023-shook/assets/87710730/0ad1b088-b263-470d-8308-deb6a49f344f)

2023-10-14 13:56 UTC, cruelladevil commented on frontend/src/features/search/components/SearchBar.tsx
> +const SearchBarExpendButton = styled.button<{ $isSearching: boolean }>`
expend -> expand

2023-10-15 06:22 UTC, Creative-Lee commented on frontend/package.json
> +    "storybook-addon-react-router-v6": "^2.0.7",
맞아요. '넘나들기 위해서' 라기 보다는 컴포넌트를 보여주기 위해서 사용했습니다. 
searchBar 컴포넌트 자체가 라우터를 사용하고 있는 컴포넌트기 때문에, 사용해야 했습니다.

2023-10-15 06:35 UTC, Creative-Lee commented on frontend/src/features/search/hooks/useSearchBar.ts
> +  );
오 생각해보니 페이지 이동을 아예못하게 하는게 자연스럽겠네요! 반영하겠습니다!

2023-10-15 06:37 UTC, Creative-Lee commented on frontend/src/features/search/remotes/search.ts
> +  return await fetcher(`/singers?name=${encodedQuery}&search=singer,song`, 'GET');
제가 작성해둔 type을 보시면 더 이해가 쉬울것 같아요!
해당 api는 쿼리에 해당하는 가수의 정보 + 노래 3개를 반환합니다!

2023-10-15 06:40 UTC, Creative-Lee commented on frontend/package.json
> +    "storybook-addon-react-router-v6": "^2.0.7",
확인이 끝나고 추후에 삭제...를 해야할까요 ? ㅋㅋㅋㅋㅋ

2023-10-15 06:48 UTC, ukkodeveloper requested changes
안녕하세요 도밥! 코난이 이미 언급한 부분 제외하고 의견 남겼습니다! 여러모로 복잡할 로직이었을 텐데 대체로 잘 해주신 것 같아요! 특히 훅 분리, 스토리북이나 msw 신경써주신 점 보면서 많이 배웠습니다! 항상 도밥의 꼼꼼함에 놀라요 ㅎㅎ

이번 PR 핵심에 대해선 세 개의 의견이 있습니다.

1. onBlur 이벤트로 모달을 제거하는 방식
저는 input에 포커스를 잃었을 때 모달을 제거하는 건 사용자 경험상 좋지 않다고 생각해요. 만약 사용자가 모달의 빈 부분을 클릭한다면 모달이 닫힐 거예요. 아마 아티스트 목록 사이에 빈곳을 눌렀다면, 사용자는 오작동났다고 느낄 수도 있을 것 같네요.

2. 데스크탑 환경에서 작은 모달로 띄워줄 필요가 있을까요?
사용하던 페이지 컨텍스트와 검색 컨텍스트는 별개라고 생각해요. 즉, 검색 도중에 뒷편에 있는 내용을 참고할 일이 없을 것 같아요. (도밥이 구현한 것도 뒷편이 스크롤되지 않는 걸로 보아 비슷한 생각이지 않을까 감히 생각해봅니다.) 만약 데스크탑 환경에서 모달로 띄워주신 이유가 있다면 의견 알려주세요!

3. 검색 절차
현재 "검색 -> 가수 목록 -> 가수와 가수의 노래 목록 -> 가수별 노래 페이지" 플로우인 것 같아요. 중간 절차인 "가수 목록"이 필요했던 이유에 대해서 궁금해요. 사실 우리 서비스에서 가수에 대해 가지고 있는 정보도 없어서  가수 목록만 보여주기엔 ui가 좀 휑한 것 같아요... 

이번에 검색 스쿼드에서 피드백을 진행하지 않아서 2번하고 3번에 대해 미리 의견을 공유하지 못한 점이 아쉽네요! 2번과 3번 같은 경우는 기획적인 부분도 포함되어 있는 사항이고 이미 구현을 해주셨기 때문에 당장은 무시하셔도 괜찮....을수도???  그래도 제 생각을 이야기 해야할 것 같아서 남겼습니다.


추가로
애매한 뷰포트의 width에서 해당 부분이 의도된 것인지 확인해주세요!
<img width="430" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/109048739/c8c6316f-1470-42c1-af5b-74549a4aca5b">

2023-10-15 06:48 UTC, ukkodeveloper commented on frontend/src/features/search/hooks/useSearchBar.ts
> +  useDebounceEffect(fetchSingerSearchPreview, searchQuery, 300);
이부분은 수정될 것 같아요! 저번에 말씀드린 것처럼 deps로 여러 개가 올 수 있는 경우가 있어서요! 이 부분은 아마 제 PR과 충돌 날텐데 제가 고쳐놓겠습니다

2023-10-15 06:48 UTC, ukkodeveloper commented on frontend/src/features/search/components/SearchBar.tsx
> +  background-size: contain;
오 이렇게 background로 svg를 넣을 수도 있군요! 역시 고수 도우밥~

2023-10-15 06:48 UTC, ukkodeveloper commented on frontend/src/features/search/components/ResultSheet.tsx
> +  position: sticky;
와 sticky 센스 멋지당!

2023-10-15 06:48 UTC, ukkodeveloper commented on frontend/src/features/search/components/ResultSheet.tsx
> +  letter-spacing: 2px;
letter-spacing 보다는 weight와 size로만 소제목 구성하는 게 좋을 것 같아요

2023-10-15 06:48 UTC, ukkodeveloper commented on frontend/src/features/search/hooks/useSearchBar.ts
> +const useSearchBar = () => {
복잡한 로직이었을텐데 잘 짜신 것 같아요! 훅으로 빼신점도 최고! 👍

2023-10-15 06:48 UTC, ukkodeveloper commented on frontend/src/features/search/components/ResultSheet.tsx
> +import { useNavigate } from 'react-router-dom';
해당 파일 이름도 Search라는 단어가 들어가면 더 파악하기 쉬울 것 같아요

2023-10-15 06:48 UTC, ukkodeveloper commented on frontend/src/shared/hooks/useValidSearchParams.ts
> +const useValidSearchParams = (...params: string[]) => {
와우~ 첨엔 이해가 잘 안되었는데 null 을 조기에 검사한 부분 너무 좋은것 같아요!

2023-10-15 07:04 UTC, Creative-Lee commented on frontend/src/features/search/components/SearchBar.tsx
> +      <SearchButton type="submit" $isSearching={isSearching} />
후우 엄청난 발견 감사합니다!
플로우가 워낙 많다보니... 수작업 검사하면서 놓쳤네요

2023-10-15 07:12 UTC, Creative-Lee commented on frontend/src/features/search/components/SearchBar.tsx
> +const SearchBarExpendButton = styled.button<{ $isSearching: boolean }>`
반영완료우

2023-10-15 07:40 UTC, Creative-Lee commented on frontend/src/features/search/components/SearchBar.tsx
> +    padding: ${({ $isSearching }) => ($isSearching ? '0 40px 0 28px' : 0)};
반영 완료했습니다.

2023-10-15 08:22 UTC, Creative-Lee commented on frontend/src/features/search/components/SearchBar.tsx
> +  @media (max-width: ${({ theme }) => theme.breakPoints.md}) {
프로젝트 전반적으로 모든 반응형 사이즈가 max-width로 되어있어서, 지금 모두 되돌리기에는 다소 리소스가 들 것 같아요.
우코 말씀대로 사실 처음부터 모바일만 pc로 지원범위를 늘려갈때는 min-width가 좋은 선택이였을거에요 ㅋㅋㅋ
(첫 반응형 코드를 넣은게 저일텐데... min으로 시작했어야 하는데 ㅠㅠ죄송합니다 익숙한대로 해버렸어요.)

다만, 이제 pc 모바일 관련없이 모두 지원하고 있으니 그대로 두어도 괜찮다고 생각합니다!

2023-10-15 08:24 UTC, Creative-Lee commented on frontend/src/features/search/components/ResultSheet.tsx
> +      <PreviewItemList as="ul" $direction="column" $gap={16}>
좋은 생각이네요! 안그래도 flex 관련 props를 맨앞으로 빼서 식별하게 해줘야하나 생각하고 있었어요

2023-10-15 08:32 UTC, Creative-Lee commented on frontend/src/features/search/components/ResultSheet.tsx
> +  box-shadow: 0px 0px 10px #ffffff49;
초기에 뒷 배경와 검색창의 색상 차이가 거의 없어서 조금 강조시키기 위해 적용했었어요 ㅋㅋㅋ
흐음 이미 바깥 배경 스크롤이 안되도록 구현한 김에 백드랍을 넣는것도 괜찮겠네요.
반영하겠습니다 ㅎ

2023-10-15 08:35 UTC, Creative-Lee commented on frontend/src/features/search/components/ResultSheet.tsx
> +  letter-spacing: 2px;
제목이 너무 다닥다닥 붙어있는것 같아서 letter-spacing을 넣었는데, 지금보니깐 또 괜찮은것도 같네요 ㅋㅋㅋ
반영하겠습니다~

2023-10-15 08:36 UTC, Creative-Lee commented on frontend/src/features/search/components/ResultSheet.tsx
> +    right: 0%;
반영 완!

2023-10-15 08:42 UTC, Creative-Lee commented on frontend/src/features/search/components/ResultSheet.tsx
> +  box-shadow: 0px 0px 10px #ffffff49;
![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/b4732eac-6d2d-419c-98ce-6c65e2735401)
![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/95e185c9-077a-4216-bbfd-2e74835e82fb)

위에가 쉐도우 있는거! 아래가 없는거에요!
어떤게 더 나은가요~? 저는 우코가 고른걸로 가겠습니다 ㅋㅋㅋㅋㅋ

2023-10-15 09:48 UTC, Creative-Lee commented on frontend/src/features/search/components/ResultSheet.tsx
> +import { useNavigate } from 'react-router-dom';
오우 감사합니다. 
곧 생길 결과 페이지와 혼동을 고려하고, 내부적으로 이름을 통일하려고 `SearchPreviewSheet` 로 변경했습니다~

2023-10-15 12:29 UTC, cruelladevil commented on frontend/src/features/search/remotes/search.ts
> +  return await fetcher(`/singers?name=${encodedQuery}&search=singer,song`, 'GET');
💬 `singer,song` 이런 형태도 가능한건지 궁금해요 `,`를 `%2C`로 안바꿔도 되는가용?

2023-10-15 12:30 UTC, cruelladevil commented on frontend/package.json
> +    "storybook-addon-react-router-v6": "^2.0.7",
음 일단 제 작업에서 스토리북 수정하면서 useNavigate를 사용한다고 에러가 떴었는데,
BrowserRouter만 감싸줘도 동작이 되었는데요.
해당 라이브러리가 필요한지는 검토해봐야 알 것 같아요

2023-10-16 17:40 UTC, Creative-Lee commented on frontend/package.json
> +    "storybook-addon-react-router-v6": "^2.0.7",
아하.. 알겠습니당

2023-10-16 17:58 UTC, Creative-Lee commented on frontend/src/features/search/remotes/search.ts
> +  return await fetcher(`/singers?name=${encodedQuery}&search=singer,song`, 'GET');
바로 물어봐야겠군요.

2023-10-16 18:09 UTC, cruelladevil approved these changes
반영사항 모두 확인했습니다 👍👍

빈공간으로 길게 채웠을 때를 허용할지(naver) 허용하지 않을지(melon) 정하면 얼추 마무리 될 것 같네요!

<img width="573" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/fccdbee6-3199-4ee3-a9b6-db4d78d5a84f">

2023-10-17 07:38 UTC, ukkodeveloper approved these changes

2023-10-17 07:41 UTC, merged