Feat/#506 마이파트를 등록하는 기능을 추가한다
woowacourse-teams/2023-shook pull request #507
Opened 2023-10-15 11:05 UTC by cruelladevil

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명(이미지 첨부 가능)

### 마이파트 미등록 시

<img width="371" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/a322cd33-3e47-419c-9b0c-23542eb2c7c6">
<img width="369" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/fa0daaa2-5dcf-4b19-98f9-0578d44d9c26">

### 마이파트가 등록되어 있을 시

<img width="372" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/f80257d1-2a49-466e-971c-9a4af7ebfd8a">
<img width="369" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/e66237b7-ec85-427c-8b95-835e972cb7bb">

### 마이페이지에서 마이파트 조회

<img width="371" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/2071c572-2ec4-471f-bda1-e18569474744">

## 💬리뷰 참고사항

> 원활한 리뷰를 위해 전달하고 싶은 맥락(특정 파일, 디렉터리 등등)  
> 리뷰어가 특별히 봐주었으면 하는 부분

현재 백엔드가 완성되지 않아 위 이미지는 msw입니다.
**마이파트 삭제시 정상 삭제되고 바로 컴포넌트에 반영되는지는 백엔드를 붙여봐야 알 것 같습니다.**
useMutation 훅 사용이 익숙치 않아서 현재 컴포넌트 분리에서 get을 어떻게 할지 모르겠네요.. 도밥의 도움이 필요합니다 😊

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #506

2023-10-15 11:49 UTC, cruelladevil commented
도밥이 얘기한 fetch 로직 분리가 [fetch 로직 분리 커밋](https://github.com/woowacourse-teams/2023-shook/pull/507/commits/9a2b2e7d8e72ca3ff55c0d1a134f7684730f8332)을 의미하는게 맞나요?!
맞다면 다른 컴포넌트들에도 분리 안된 것들이 있는데 작업하면 좋을 것 같네요!

2023-10-16 12:22 UTC, ukkodeveloper requested changes
내 파트 등록하는 부분과 마이 페이지에 리스트 적용하신 거 잘 확인했습니다. 깔끔하게 코드 잘 작성해주신 것 같아요! ui도 별도로 피드백 드릴 건 없는 것 같습니다. 몇 가지 변경사항이나, 궁금한 점을 커멘트로 남겼으니 확인 부탁드릴게요! 👍 👍 👍

2023-10-16 12:22 UTC, ukkodeveloper commented on frontend/src/features/songs/components/KillingPartTrackList.tsx
> +      />
현재 서버로부터 401 응답을 받으면, 로그인 하라는 모달이 뜨게끔 되어 있어요. 그래서 이제 별도로 로그인 모달을 만들지 않아도 될 것 같아요. (하지만 axios 도입하고 나서 어떻게 변경될지는 모르겠어요! )

2023-10-16 12:22 UTC, ukkodeveloper commented on frontend/src/features/member/components/MyPartList.tsx
> +
❓ 단순 질문입니다. 이런 데이터 구조를 사용하면 어떤 이점이 있나요???? 종종 식별 태그 (현재는 `tab`과 같은)를 사용하는 것을 본 적이 있는데, 어떤 장점이 있는지 궁금해요.

2023-10-16 15:59 UTC, Creative-Lee commented on frontend/src/assets/icon/trash.svg
처음보네요 이런 형식 ㅋㅋ

2023-10-16 17:34 UTC, Creative-Lee requested changes
이것 저것 분리하랴 삭제하랴 추가하랴 
작업이 되게 많았고 힘들었겟네요. 고생하셨습니다.

리뷰를 남기다보니 짜잘한것도, 몇개 중요한것도 있어요. 
입맛대로 반영해 주세요.

---

>useMutation 훅 사용이 익숙치 않아서 현재 컴포넌트 분리에서 get을 어떻게 할지 모르겠네요.. 도밥의 도움이 필요합니다 😊

이거는 바로 상황 설명 부탁드립니다!

2023-10-16 17:34 UTC, Creative-Lee commented on frontend/src/features/member/constants/introductions.ts
> +];
💬 read only 하게 해주면 더 좋을 것 같아요

2023-10-16 17:34 UTC, Creative-Lee commented on frontend/src/features/member/constants/introductions.ts
> +  '난 내가 말야, 스무살쯤엔 요절할 천재일줄만 알고',
분리 굿이용~ 
그런데 가끔 2줄이 되는 노랫말이 있네요. 그래서 테스트를 한번 해봤습니당

![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/bbb19124-9f3c-46db-a7bd-1aea7ee72c59)

---

+++ 로그인 했다고 가정하고 html로 직접 돔을 추가해서 위에 닉네임이 뜨도록 해봤는데용
코난의 탭 선택시, 스무스 스크롤 148 이동시키는게 살짝 의도와 달라지네요 

---

**닉네임 없을때:** 스무스 하게 딱 탭 경계선에 걸쳐져서, 스크롤 하면 탭고정 상태로 바로 내려감

![스크롤 정상](https://github.com/woowacourse-teams/2023-shook/assets/77152650/e1b2230c-8c06-4ac2-899d-5acbc621142d)


---

**닉네임 두고 테스트 해봤을 때:** 스무스하게 탭 경계선 **살짝 위로 더 올라감**
다시 스크롤 하면 **탭이 살짝 내려가고** 다시 내려감

![스크롤](https://github.com/woowacourse-teams/2023-shook/assets/77152650/1c33d256-bcb1-4a14-a2da-959237bd56d2)


---


말로하면 이해가 안될듯해서 영상 남깁니다.

2023-10-16 17:34 UTC, Creative-Lee commented on frontend/src/features/member/remotes/myPage.ts
> +export const getLikeParts = () => fetcher('/my-page/like-parts', 'get');
💬 `GET` 이게 아마 대문자가? 되어야 했었나요?

2023-10-16 17:34 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.stories.tsx
> +// FIXME: 재생시 `YT is not defined` 에러 발생
스토리에서는 현 index.tsx 에서 읽는 유튜브 api가 안읽혀서 그런가봐요 ㄷㄷ

2023-10-16 17:34 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +    showToast('내 파트가 삭제되었습니다.');
💬 (수퍼수퍼 마이너) 
'My ~' 는 어떤가요?

2023-10-16 17:34 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +            <ButtonIcon src={trashIcon} />
alt='' 를 추가하면 좋을 것 같아용

2023-10-16 17:34 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +          <DeleteButton type="button" onClick={openMyPartModal}>
버튼에는 aria-label 한사바리 하시죠! 
aria-label="마이파트 삭제하기?"

2023-10-16 17:34 UTC, Creative-Lee commented on frontend/src/features/songs/constants/genres.ts
> -`  `;
감사합니다.

2023-10-16 17:34 UTC, Creative-Lee commented on frontend/src/mocks/handlers/memberHandlers.ts
>        ctx.json([
요거랑 아래 request fixture로 분리해주시면 좋을 것 같아요!

2023-10-17 08:44 UTC, cruelladevil commented on frontend/src/assets/icon/trash.svg
저도 svg가 깔끔한걸 처음봤어요ㅋㅋ

2023-10-17 11:18 UTC, cruelladevil commented on frontend/src/features/member/components/MyPartList.tsx
> +  color: ${({ $isActive, theme: { color } }) => ($isActive ? color.white : color.disabled)};
✍️ 수정 커밋 - dea67f752c343072f90e29971ce6bb9af50955d7

### 변경 전

`color.disabled`

<img width="360" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/68db5bc5-2ba8-41f3-9d07-b26cee78ac98">

### 변경 후

`color.disabledBackground`

<img width="356" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/cc13f351-70e9-4340-b7a1-2c3bcd789e26">

2023-10-17 11:19 UTC, cruelladevil commented on frontend/src/features/member/components/PartList.tsx
> +            />
👍👍 좋아요

✍️ 수정 커밋 - 7933937a1052538aaad8a63ff85c25939bb07170

2023-10-17 11:35 UTC, cruelladevil commented on frontend/src/features/member/components/MyPartList.tsx
> +  top: ${({ theme }) => theme.headerHeight.desktop};
💬 fixed라는데 고쳐야되나용? 저는 일단 개발자 도구의 device toolbar를 켰을 때만 일어나는 것 같아요.
혹시 실사용하면서 해당 버그가 발생하는가용?

https://bugs.chromium.org/p/chromium/issues/detail?id=1076036

2023-10-17 11:46 UTC, cruelladevil commented on frontend/src/features/member/remotes/myPage.ts
> +export const getLikeParts = () => fetcher('/my-page/like-parts', 'get');
👍 get 같은 경우 대소문자가 상관 없기는 한데 대문자가 기본이니 대문자로 수정하도록 할게요!

https://developer.mozilla.org/ko/docs/Web/API/fetch#method

2023-10-17 12:42 UTC, cruelladevil commented on frontend/src/features/member/constants/introductions.ts
> +  '난 내가 말야, 스무살쯤엔 요절할 천재일줄만 알고',
커밋된 내용의 `ProfileFlex` 컴포넌트의 높이를 일정하게 유지시켜서
scrollTop을 고정적으로 운용할 수 있도록 스타일을 수정했습니다!
높이의 기준은 [자기 소개 3줄](https://github.com/woowacourse-teams/2023-shook/pull/507/commits/6a19f5dafa6302eeb15b9b11cf8deefe8067a566) 기준입니다.

✍️ 수정 커밋 - 0534145b929a788194ec08477c1e7e10580349c7

2023-10-17 12:52 UTC, cruelladevil commented on frontend/src/features/member/components/PartList.tsx
> +const Li = styled.li`
PartItem이 단일 아이템 view로서 재사용 가능하다는 판단하에 li로 만들지 않았었는데요.
재사용 가능성이 적기도 하고 굳이 li가 아닐 필요가 없다고 판단하여 해당 li 태그 부분을 PartItem으로 옮기게 되었습니다.

✍️ 수정 커밋 - 2538e6db80145870672595e62442a012c3519a52

2023-10-17 12:56 UTC, cruelladevil commented on frontend/src/features/member/components/MyPartList.tsx
> +  const partList: { tab: 'Like' | 'MyKillingPart'; parts: LikeKillingPart[] }[] = [
넵 재사용되는 점을 생각해서 타입 분리하도록 하겠습니당

✍️ 수정 커밋 - dabb0e2768429e4946b7a75d2ba1fd72948d58b0

2023-10-17 13:18 UTC, cruelladevil commented on frontend/src/features/member/components/PartItem.tsx
> +  font-weight: 800;
이전 코드 그대로 가져온 것이라 수정하지 못했네요 😭

✍️ 수정 커밋 - 4be4363882906204d1feb95eb9ba6163ce2dffc4

2023-10-17 13:21 UTC, cruelladevil commented on frontend/src/features/member/components/PartList.tsx
> +const PopularSongList = styled.ol`
이전 코드 그대로 가져온 것이라 수정하지 못했네요 😭 222

https://github.com/woowacourse-teams/2023-shook/pull/507#discussion_r1362064215 와 함께 수정 되었습니다.

2023-10-17 13:22 UTC, cruelladevil commented on frontend/src/features/member/constants/introductions.ts
> +];
✍️ 수정 커밋 - bc88c8b61993bc3688059383aa382bffcae8b270

2023-10-17 13:24 UTC, cruelladevil commented on frontend/src/features/member/components/PartItem.tsx
> +  const goToListenSong = () => {
✍️ 수정 커밋 - https://github.com/woowacourse-teams/2023-shook/pull/507/commits/1eb6d7807fbfe17e01006615ed0fdcd5aa6e5cde

2023-10-17 13:25 UTC, cruelladevil commented on frontend/src/features/member/components/PartItem.tsx
> +    <Grid onClick={goToListenSong}>
https://github.com/woowacourse-teams/2023-shook/pull/507#discussion_r1362108797 와 함께 수정되었습니다

2023-10-17 13:30 UTC, cruelladevil commented on frontend/src/features/member/components/PartItem.tsx
> +  rank: number;
이전 코드 그대로 가져온 것이라 수정하지 못했네요 😭

✍️ 수정 커밋 - f9b85f100f74a0b9da0ba062c79e3b443039edce

2023-10-17 13:42 UTC, cruelladevil commented on frontend/src/features/member/components/MyPartList.tsx
> +
[탭과 보여줄 컨텐츠를 동적으로 추가](https://github.com/woowacourse-teams/2023-shook/pull/507/commits/c907719c6695625f59d8f5750a56cb88223c1e6a)할 수 있도록 배열로 관리하면 편할 것 같아요~

2023-10-17 13:47 UTC, cruelladevil commented on frontend/src/features/member/components/MyPartList.tsx
> +  const [selectedParts] = partList.filter((p) => p.tab === tab);
👍 [탭과 보여줄 컨텐츠를 동적으로 추가](https://github.com/woowacourse-teams/2023-shook/pull/507/commits/c907719c6695625f59d8f5750a56cb88223c1e6a)하도록 수정하면서 변경했습니다

2023-10-17 13:54 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +            <ButtonIcon src={trashIcon} />
웹 접근성 향상 시켰습니다

✍️ 수정 커밋 - 59c967d6f00fca635f32ec6e66d3384a51734cfc

2023-10-17 13:55 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartTrack.tsx
> +          <DeleteButton type="button" onClick={openMyPartModal}>
https://github.com/woowacourse-teams/2023-shook/pull/507#discussion_r1361014339 와 함께 수정되었습니다

2023-10-18 05:32 UTC, cruelladevil commented on frontend/src/mocks/handlers/memberHandlers.ts
>        ctx.json([
✍️ 수정 커밋 - [9b35f7d](https://github.com/woowacourse-teams/2023-shook/pull/507/commits/9b35f7d05ca29a56508fa4a7fb3b5a2da0d8cb15)

2023-10-19 02:36 UTC, Creative-Lee commented on frontend/src/features/member/components/MyPartList.tsx
> +  top: ${({ theme }) => theme.headerHeight.desktop};
모바일 개발자 도구에서 확인되는 문제였던걸로! 대화를 통해 해결!

2023-10-19 02:44 UTC, Creative-Lee commented on frontend/src/features/songs/components/KillingPartInterface.tsx
> +  const [nowPlayingTrack, setNowPlayingTrack] = useState(DEFAULT_PART_ID);
추후에 -1 1 2 3 4 까지해서 객체 상수화 + type 화 되면 좋겠네용

2023-10-19 02:46 UTC, Creative-Lee approved these changes
리뷰 반영 확인했습니다.
고생하셨어요~

2023-10-19 03:02 UTC, cruelladevil commented on frontend/src/features/songs/components/KillingPartInterface.tsx
> +  const [nowPlayingTrack, setNowPlayingTrack] = useState(DEFAULT_PART_ID);
네 기존에 KillingPart의 id로 구분하다가 현재 myPart도 추가가 되면서 중복 id 때문에 라벨을 제대로 찾지 못하는 현상을
순서를 통해 구분하게 되었는데 컴포넌트 구조상 상태나 상수가 꼬인 감이 없지 않아 있습니다.
추후 이 구조를 리팩토링 하면서 해당 부분 반영하겠습니다!

2023-10-19 03:02 UTC, merged