Feat/#499 등록 ui 개선 및 등록 페이지 리팩터링
woowacourse-teams/2023-shook pull request #508
Opened 2023-10-15 16:29 UTC by ukkodeveloper

## 📝작업 내용
작업 내용이 좀 많습니다. 기존 제 PR에서 기본적인 것들을 지키지 않은 것 같아서, 이번에 좀 하나씩 확인해보면서 적용해봤습니다. 
작업 내용은 크게 두 가지입니다.
### WaveScrubber
- 전체 듣기 시 ui
<img width="300" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/109048739/0c96d09f-1895-43bd-9826-68483b24c03b">

- 구간 듣기 시 ui
<img width="300" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/109048739/db450bec-b54c-4234-89db-4a1a8939eb87">

구간의 길이, 구간 시작점, 전체 듣기 등 모든 제어에 다시 시작점으로 이동합니다. 

### 페이지 리팩터링
이 작업을 시작한 계기는 이번에 구현을 하면서 스타일링을 변경하는 게 쉽지 않았었는데요. 
페이지 코드 단에서 구조가 한 눈에 보이지 않더라고요.
아래는 등록 페이지 JSX 코드인데요. 파란색과 보라색 컴포넌트는 서로 동일한 계층에 존재합니다.
<img width="768" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/109048739/0e4b2077-9c52-460b-82c8-3c3bd6ef6c10">
하지만 실제 렌더링된 UI를 보면 그렇지 않죠. 
<img width="365" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/109048739/868edab0-b3f4-483e-b80e-acac3ff43370">
즉, 계층별로 컴포넌트의 추상화 레벨이 맞지 않기 때문에 머릿 속에 구조가 잘 들어오지도 않습니다.

이에 더해서 VoteInterface는 여러 UI가 복합적으로 뭉쳐져있기 때문에 외우고 있지 않는 한 어떤 ui가 담겨져 있는 지 알 수 없습니다. 해당 컴포넌트 파일을 봐야만 어떤 ui가 있는 지 알 수 있는 것입니다.

JSX 구조를 보여준다는 점뿐만 아니라 실제로 CSS flex를 통해 반응형을 구현하는 과정에서 flex를 새로 감싸는 작업에서도 힘든 상황이 있었습니다. 각 컴포넌트 구분이 명확하지 않다보니, 내가 추가한 flex 속성이 어느 ui에 영향을 미치는 건지 확인하는 것도 쉽지 않았습니다. 매번 질서가 잡히지 않은 중첩된 컴포넌트를 왔다갔다 하면서 CSS 속성을 확인해야 했습니다.

개선 후에는 JSX코드가 이렇게 됩니다.
<img width="849" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/109048739/64d4e76c-5efd-4139-a550-b6a7aae091b9">
계층을 잘 나누려고 노력을 했는데요. 이렇게 구조를 변경하니 페이지가 어떻게 구성되어 있는 지 쉽게 예측할 수 있을 뿐만 아니라 관심사 분리도 어부지리로 되었다는 느낌도 받았습니다. 만약 youtube 조작 ui를 변경하고 싶다면 해당 코드만 보고도 바로 VideoController에서 변경해야겠다는 판단이 들 것입니다.

이 작업을 통해 "실(loss)"이 존재합니다. context provider을 필요한 부분에만 적용하지 않고 전체를 감쌌다는 것인데요. 저는 실보다는 득이 훨씬 크다고 생각해서 변경했습니다. 다른 분들의 의견도 궁금하네요. 

이것 외에는 commit 참고 부탁드립니당.

## 💬리뷰 참고사항
### 같이 고민했으면 좋겠는 부분
Context를 사용해서 모든 하위 컴포넌트에서 context를 사용해서 상태관리를 하고 있습니다. 그러다보니 비디오를 조작하는 모든 ui가 재사용이 불가능한데요. 일단, 재사용할 일이 없을 것 같아서 context를 주입했는데, 이 부분에 대해서 props로 받는 게 나을 지 여러분의 의견이 궁금해요.

### 이름 변경
Vote 들어간 컴포넌트나 훅의 이름을 Collect로 변경했어요. 현재 기획 변경으로 "수집"이라는 단어도 사용하지 않지만, "collect"도 내 파트 등록을 어느정도 포괄할 수 있는 단어이기도 하고, 현재 페이지 경로 세그먼트도 'collect'로 되어 있어서 통일했습니다. ("vote"는 의미가 많이 다른 것 같아서요.)

### 기타
리팩터링에서 api 호출 관련해서는 굳이 개선하지 않았습니다. axios 도입되면 그때 추가로 개선해야할 것 같습니다.

### 🔴 QA 테스트 환경 🔴  
1. router.tsx에서 `PartCollectingPart`페이지를 감싸고 있는 `<AuthLayout>`를 제거한다.
2. /collect/1 로 직접 url 입력하여 접속한다.

스토리북을 사용할까 생각도 해봤는데, 어차피 페이지 단위 렌더링이 필요한 작업 + 이미 다른 PR에서 도밥이 작업한 것들을 중복으로 할...
대충 여러모로 시간이 꽤나 걸릴 것 같아서 스토리북은 조금 생략했습니다. 😢 이번만 양해 부탁드릴게요

## #️⃣연관된 이슈
close #499

2023-10-15 16:31 UTC, ukkodeveloper commented on frontend/src/features/songs/components/VideoIntervalStepper.tsx
> +  ${StepperElementStyle};
이거 자꾸 웹스톰에서 에러 표시 나서 `;` 붙였는데, vscode에서는 `;` 붙이나 안 붙이나 에러가 안나더라고요. 경고면 참고 하겠는데 에러여서 일단 붙였습니다.

2023-10-15 16:39 UTC, ukkodeveloper commented on frontend/src/features/killingParts/components/RegisterPart.tsx
> +  // 현재 비로그인 시에 등록을 누르면 두 개의 모달이 뜹니다.
현재 존재하는 버그입니다. 커멘트보다는 주석으로 남겨놓는 게 좋을 것 같아서 주석처리했어요.

2023-10-15 16:39 UTC, ukkodeveloper commented on frontend/src/features/youtube/components/VideoBadges.tsx
> +  const video = useVideoPlayerContext();
훅으로 제공되는 메서드가 pause, start 이렇게 간략하게 되어 있더라고요. 코드에 주체를 적으면 이해하는 데 좋을 것 같아서 객체 분해할당하지 않고 video 로 이름 지었어요.

2023-10-15 16:39 UTC, ukkodeveloper commented on frontend/src/features/youtube/components/WaveScrubber.tsx
> +  z-index: 3;
모든 영역에서 스크롤 가능하게 만들기 위해 ProgressFrame 보다 z-index가 높습니다.

2023-10-15 16:39 UTC, ukkodeveloper commented on frontend/src/shared/styles/theme.ts
> +    magenta100: '#fff0f6',
슉 메인색인데 색이 너무 없는게 답답해서 ant design에서 제공하는 팔레트 가져왔습니다.

2023-10-15 16:39 UTC, ukkodeveloper commented on frontend/src/shared/styles/GlobalStyles.ts
> +    background-color: black;
페이지 끝단에서 흰색 배경이 보이길래 black으로 변경

2023-10-16 05:58 UTC, Creative-Lee requested changes
우코 정말 고생 많았습니다.
리팩토링이 쉽지않은걸 알기에 감사함이 큽니다.
디자인 관련 수정 + 코멘트 반영해서 다시 요청주시면 감사할게요!

---

### 사용성 관련 피드백

1. 스크러버로 구간 변경시, 대략 1초정도 뒤에 progressFill이 채워진다.
2. 유튜브 seekTo 사용시에 `1tick 버퍼링 상태 취급` 때문에 자주 발생하는 ui 변경
  a. pause / play 버튼 깜빡임(처럼 보임)
  b. 전체 반복 웨이브 깜빡임(처럼 보임)

위 부분은 한번 시도해봐주시면 감사할게요!

### 디자인 관련 체크리스트!
같이 대화했던 부분입니다 ㅎㅎ 리스트 있으면 좋을것 같아서 남겨놔요!

- [x] 테블릿 이하 사이즈에서 짤림
![768 하위 짤림](https://github.com/woowacourse-teams/2023-shook/assets/77152650/7e980bc8-f9dd-456d-8b25-9a2b74735d67)

- [x] 인터페이스 크기
![pc 반응형 스와이프 페이지와 맞추는건 어떤지 스크러버 인터페이스가 영상에 비해 크다고 생각한다](https://github.com/woowacourse-teams/2023-shook/assets/77152650/8736f724-11f7-4de1-9870-815a7ce31cc1)

- [ ] 좌우 패딩 차이
![pc 좌우 패딩 차이 유튜브 박스에만 패딩 더 들어가 있음](https://github.com/woowacourse-teams/2023-shook/assets/77152650/6e185bea-b535-48f3-8f3a-a7ce132a0ec3)

---

### 제안(진지함)

추후에 killingPart 듣기 페이지의 컴포넌트를 feature/ 하위로 분리해야 할 것을 대비해서,
현재 분리한 부분을 feature/ 하위에 `collect` 의 의미를 담아 **다시 네이밍 해보면 어떨까요?**
killingPart 듣기 페이지의 컴포넌트가 killingPart 디렉터리를 차지하게 되지 않을까? 해서 제안해봅니다!

![디렉터리명 콜랙팅이 어떤지](https://github.com/woowacourse-teams/2023-shook/assets/77152650/e142bb63-a2e6-471d-9411-ca8330b3f62f)

2023-10-16 05:58 UTC, Creative-Lee commented on frontend/src/pages/PartCollectingPage.tsx
> +          </PageFlex>
직관적으로 보기 편해졌어요!

2023-10-16 05:58 UTC, Creative-Lee commented on frontend/src/features/youtube/components/WaveScrubber.tsx
> +      </WaveWrapper>
flex에 대한 의미를 어떻게 주려했는지 대화를 통해 확인했습니다!
post /pre fix 에 대한 부분 잘 정해봅시다

2023-10-16 05:58 UTC, Creative-Lee commented on frontend/src/features/youtube/components/VideoBadges.tsx
> +  };
💬 이거 플레이랑 / 플레이 + 씩투 조건이 정확하게 뭔지 따로 한버만 설명 부탁드립니다~

2023-10-16 05:58 UTC, Creative-Lee commented on frontend/src/features/songs/components/CollectingPartProvider.tsx
> +  };
증가시킬때는 max 검사만, 감소시킬때는 min 검사만 해도 될 것 같아요!

💬 함수형 업데이트를 사용한 이유가 있으신가요~?
원시타입 state라 아래와 같이 사용해도 괜찮을 것 같아요
💬 plus, minus 대신 increse/ decrese는 어떤가용? ㅋㅋㅋ
더하기 빼기 / 증가 감소  느낌차이가 조금 있다고 생각해서 남겨봐요 ~

``` js
  const plusPartInterval = () => {
    if (interval === MAX_PART_INTERVAL) return;

    setInterval(interval + 1);
  };

  const minusPartInterval = () => {
    if (interval === MIN_PART_INTERVAL) return;

    setInterval(interval - 1);
  };
```

2023-10-16 13:47 UTC, ukkodeveloper reviewed
> 추후에 killingPart 듣기 페이지의 컴포넌트를 feature/ 하위로 분리해야 할 것을 대비해서,현재 분리한 부분을 feature/ 하위에 collect 의 의미를 담아 다시 네이밍 해보면 어떨까요?
killingPart 듣기 페이지의 컴포넌트가 killingPart 디렉터리를 차지하게 되지 않을까? 해서 제안해봅니다!
> 

collect 자체가 사실, 데이터 기준으로 보면 killing part를 post하기 위해 존재하는 ui입니다. 그러면 killing part에 있어야 한다고 저는 생각합니다.

그리고 언급해주셨던 것처럼 video에 있는 컴포넌트(stepper나 controller)의 경우도 killing part 를 등록하기 위해 context를 의존하고 있기 때문에 killing part로 이동시켰습니다.

💬  도밥이 다음과 같이 의견을 낸 이유가 "killing part"에 너무 많은 모듈이 들어올 것 같아서 인지, 아니면 "데이터"가 아닌 "페이지"단위로 디렉터리 구분을 하고 싶으신 건지 궁금합니다.

2023-10-16 13:47 UTC, ukkodeveloper commented on frontend/src/shared/components/Layout/Layout.tsx
> +  }
아이폰에서 100vh 적용을 위한 코드입니다! 로그인 페이지에서 코난이 잘 구현해주셔서 잘 사용했습니다.

2023-10-16 13:47 UTC, ukkodeveloper commented on frontend/src/features/youtube/components/WaveScrubber.tsx
> +  );
와우 추론!

2023-10-16 13:47 UTC, ukkodeveloper commented on frontend/src/features/youtube/components/VideoController.tsx
> +import VideoIntervalStepper from '@/features/songs/components/VideoIntervalStepper';
killing part 등록이면 killing part 에 들어가야하지 않을까 생각해서 killingpart 하위 폴더로 넣었어요!

2023-10-16 13:47 UTC, ukkodeveloper commented on frontend/src/features/youtube/components/VideoBadges.tsx
> +  };
전체 듣기 시에는 구간의 첫구간으로 이동하지 않고 비디오 플레이만 시키려고 한 부분입니다~

2023-10-16 13:47 UTC, ukkodeveloper commented on frontend/src/features/songs/components/CollectingPartProvider.tsx
> +  };
아주 좋은 아이디어입니다 바로 적용~ 굳밥~

2023-10-16 15:36 UTC, Creative-Lee requested changes
현재까지 수정된 사항 반영 확인 했습니다!

>collect 자체가 사실, 데이터 기준으로 보면 killing part를 post하기 위해 존재하는 ui입니다. 그러면 killing part에 있어야 한다고 저는 생각합니다.

오우 이건 제가 착각했어요. 마이파트 등록이라는걸 망각하고, 예전 킬링파트 직접 등록하던 시절을 생각했습니다. 우코의 생각에 동의합니다!

---

### pc 환경에서 마우스 드래그

PC 환경에서 사용할 수 없는 상태라 드래그 기능이 추가되어야 할 것 같아요.

### 반응형 사이즈 max-width로 통일

요건 조금 귀찮으시겠지만, 반대로 돌려서 속성 바꿔주시면 감사하겠습니다.

### 파트 등록 후, 해당 노래 킬링파트 페이지로 이동 버튼 제공?

이제 마이파트 등록 후 
파트 공유보다는 다시 킬링파트 등록 페이지로 이동하게 해주는 기능을 제공하면 어떨까요?
킬링파트 페이지에서 등록하러 본 페이지에 왔으니, 
등록이 완료되었으면 **다시 돌아가서 듣을 수 있으면 자연스러울 것 같아요!** 

![이제 마이 파트로 이동 시켜주는 버튼을 제공하는 것은 어떤지](https://github.com/woowacourse-teams/2023-shook/assets/77152650/8983799e-1d9f-471a-9b49-1d0775a32f51)

### 추가 코멘트 

몇개 남겼으니 확인해 주세요!

2023-10-16 19:23 UTC, cruelladevil requested changes
재밌는 UI가 생겨 사용자들이 좋아할 것 같네요!
기존 슬라이더보다 사용성도 더욱 좋은 것 같구요👍👍

2023-10-16 19:23 UTC, cruelladevil commented on frontend/src/features/killingParts/components/VideoBadges.tsx
> +  min-width: 40px;
style lint가 적용 안되었네용

2023-10-16 19:23 UTC, cruelladevil commented on frontend/src/features/killingParts/components/VideoIntervalStepper.tsx
> +  font-weight: 700;
💬 아쉽게도 큰 차이는 없을 거에요
현재 Regular (400)만 asset에 추가되어 있어서 weight 별 차이를 잘 못느낄겁니다.
추가하자는 의견이 있으면 100부터 전부 다 넣거나 필요한 부분만 넣어도 될 것 같네용

### 현재 프로젝트 내부

<img width="783" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/2cdfcf9d-dfac-4ae9-b48f-c9f314e6015e">

### 실제 차이

<img width="803" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/87710730/37540230-e324-447a-a7df-604c085b2dc2">

2023-10-16 19:23 UTC, cruelladevil commented on frontend/src/features/killingParts/components/WaveScrubber.tsx
> +const WaveWrapper = styled(Flex)`
```suggestion
export default WaveScrubber;

const WaveWrapper = styled(Flex)`
```

2023-10-19 04:23 UTC, ukkodeveloper commented on frontend/src/features/killingParts/components/WaveScrubber.tsx
> +const WaveWrapper = styled(Flex)`
적용 완료했습니다!

2023-10-19 04:23 UTC, ukkodeveloper commented on frontend/src/features/killingParts/components/VideoIntervalStepper.tsx
> +  font-weight: 700;
일단 weight 뺐습니다. 나중에 추가해보죵

2023-10-19 04:23 UTC, ukkodeveloper commented on frontend/src/features/killingParts/components/VideoBadges.tsx
> +  min-width: 40px;
적용 완료했습니다!

2023-10-19 04:24 UTC, ukkodeveloper commented on frontend/src/features/killingParts/components/SoundWave.tsx
> +};
return 사이에 로직이 추가되어서 return 키워드를 그대로 사용했습니다. 좋은 지적 감사합니다.

2023-10-19 04:25 UTC, ukkodeveloper commented on frontend/src/features/killingParts/components/RegisterPart.tsx
> +      <RegisterButton type="submit" onClick={submitKillingPart}>
`submit the form to the server.` form을 서버에 보내줄 때 사용하는 것이었군요! 제거했습니다.

2023-10-19 05:42 UTC, Creative-Lee approved these changes
어려운 구현이였을 텐데 너무 고생많았습니다.
너무 이뻐지고 편해졌네요~ 감사합니다 ㅎㅎ
반영은 천천히 하셔도 됩니다~

2023-10-19 05:42 UTC, Creative-Lee commented on frontend/src/features/killingParts/components/SoundWave.tsx
> +        if (boxRef.current?.scrollLeft) {
💬 제약되는 상황이 아니라면 얼리리턴으로 댑스를 줄여도 좋겠네요!

2023-10-19 05:42 UTC, Creative-Lee commented on frontend/src/features/killingParts/components/WaveScrubber.tsx
> +        ref={waveScrubberRef}
💬 ref는 중요한 정보라고 생각해서 앞으로 빼는 편이에요
맨앞이 아니더라도 event ,스타일 속성, 기타 속성들을 한곳에 모아두는게 더 읽기 편할 것 같아요. 
지금은 event 사이에 스타일 속성 ref가 있어서 정돈된 느낌이 덜한것 같네요

2023-10-19 05:42 UTC, Creative-Lee commented on frontend/src/features/killingParts/hooks/usePin.ts
> +  };
💬 나중에 set함수 분리 해주세요~

2023-10-19 05:42 UTC, Creative-Lee commented on frontend/src/features/killingParts/components/RegisterPart.tsx
> +    navigate(-1);
장르는 ALL 때릴생각을 하고 이야기했었는데, 우코의 생각이 더 좋은것 같아요! ㅎㅎ
대화를 통해 해결했습니다~

2023-10-19 07:40 UTC, ukkodeveloper commented on frontend/src/features/killingParts/components/RegisterPart.tsx
> +    navigate(-1);
[대화 정리] 
- 특정 장르에서 노래를 듣다가 내 파트 등록 페이지로 갑니다.
- 등록 완료 후에는 이전에 사용하던 맥락으로 돌아가야하기 때문에 history 기록을 pop합니다.

2023-10-19 07:40 UTC, ukkodeveloper commented on frontend/src/features/killingParts/components/RegisterPart.tsx
> +      <RegisterButton type="submit" onClick={openModal}>
반영완료!

2023-10-19 07:41 UTC, ukkodeveloper commented on frontend/src/features/killingParts/components/SoundWave.tsx
> +// eslint-disable-next-line react/display-name
`SoundWave.displayName = 'SoundWave';` 적용완료

2023-10-19 07:42 UTC, ukkodeveloper commented on frontend/src/features/killingParts/components/WaveScrubber.tsx
> +        ref={waveScrubberRef}
props가 많아서 정리해서 보여주니 훨씬 읽기 좋아진 것 같아요

2023-10-19 07:43 UTC, ukkodeveloper commented on frontend/src/features/killingParts/hooks/usePin.ts
> +  };
추후에 어떻게 분리해야할 지 고민해봐야겠네요. 훅 정리하면서 시멘틱하게 이름 지어야할 것 같아요. 현재 usePin에 선언되어있는 함수가 많아서 고민입니다. 리팩터링할 때 적용해볼게요

2023-10-19 13:17 UTC, merged