Feat/#543 로컬 캐시에 좋아요 데이터가 실시간으로 반영되도록 수정
woowacourse-teams/2023-shook pull request #549
Opened 2023-10-31 07:36 UTC by Cyma-s

## 📝작업 내용

로컬 캐시에 좋아요 데이터가 실시간으로 반영되도록 수정한다.

## 💬리뷰 참고사항

- `InMemorySongs` 에 노래 id 만 정렬하는 List 와 노래 id 를 key 로 갖고 노래 엔티티를 value 로 갖는 `Map` 이 존재합니다.
- 정렬은 노래 id List 만 수행합니다. 
- 좋아요 등록 / 취소가 발생하는 경우 '삽입 정렬' 로 노래 id 를 재정렬합니다. (삽입 정렬은 거의 정렬되어 있는 데이터에 가장 효과적인 알고리즘)

자세한 내용은 아래를 참고하시면 좋습니다.

- [로컬 캐시 개선기 - 자세한 이유](https://vero.wiki/inmemory-cache-develop-reason/)
- [로컬 캐시 개선기 - 테스트 결과](https://vero.wiki/inmemory-cache-develop/)

## #️⃣연관된 이슈

closes #543

(close) #이슈번호

2023-11-01 07:17 UTC, somsom13 requested changes
안녕하세요 베로~~!! 고생하신 흔적이 엄청 많이 보이는 코드네요 👍 👍 
특히 삽입정렬 코드 멋지네요 😮 

궁금한 부분들이 몇 가지 있어서 코멘트 남겨두었습니다~~~ 고생하셨어요!!!

2023-11-01 07:17 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
>              this.likeCount++;
AtomicInteger가 아닌 일반 likeCount에는 동시성이 보장되지 않을 것 같은데 맞나요??
맞다면 이건 어떻게 해결할 수 있을지 생각해봐야겠네용 (response로 반환되는 likeCount는 일반 likeCount인 것 같네용)

2023-11-01 07:17 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLikes.java
> +    private Set<KillingPartLike> likes = new HashSet<>();
👍

2023-11-01 07:17 UTC, somsom13 commented on backend/src/test/java/shook/shook/song/application/killingpart/KillingPartLikeConcurrencyTest.java
> +                                    transactionTemplate.execute((status -> {
개행이.. 개행이... 저랑 설정이 다른 것 같은데 저의 설정이 이상하게 된걸가요..?

2023-11-01 07:17 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    private final EntityManager entityManager;
`InMemorySongs`가 `EntityManager`를 가지고 있는게 조금 어색하게 느껴지는 것 같아요!
`em`은 `recreate` 메서드에서만 쓰이고, `recreate`는 `InMemorySongScheduler`에서만 쓰이는 것 같은데 여기로 분리할 수 있지 않을까요?.

베로는 어떻게 생각하시나요?

2023-11-02 02:10 UTC, somsom13 commented on backend/src/main/java/shook/shook/auth/config/LocalAuthConfig.java
> +@Profile("local")
그리고 `LocalAuthConfig`에도 토큰 검증이 필요한 경로와 아닌 경로를 명시해주는게 좋을 것 같습니당
로컬에서 swgger를 확인하러 들어갔는데 interceptor에서 토큰 파싱에 대해 NPE가 터지더라구요

![image](https://github.com/woowacourse-teams/2023-shook/assets/70891072/ebb7e656-b5b7-4f32-b34e-ea54e3346bf5)

2023-11-02 06:01 UTC, Cyma-s commented on backend/src/main/java/shook/shook/auth/config/LocalAuthConfig.java
> +@Profile("local")
Bearer 형식으로 지정하지 않았던 이유는 Local 에서 테스트할 때 필요한 오버헤드를 최대한 줄이고 싶어서입니다! 지금까지는 로컬에서 테스트 할 때도 항상 토큰을 만들어야 해서 너무 불편했는데, 이런 구조의 `LocalInterceptor` 를 사용하게 되면 테스트가 훨씬 원활해질 거라 생각해서 만들었습니다 :)

2023-11-02 06:01 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
> +            inMemorySongs.like(killingPart, likeOnKillingPart);
DB 좋아요 개수 증감 로직을 안 짰네요... Scheduler 로 좋아요를 batch update 하는 로직도 만들어 보겠습니다! 좋은 지적 감사합니다 역시 바론이네요 ^^

2023-11-02 06:03 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +            .peek(entityManager::detach)
맞아요 `Song`, `KillingPart`, `KillingPartLike` 를 모두 detach 하기 위해 해당 로직이 필요합니다. 
제가 `KillingPart` 의 `likeCount` 값에 1 더하는 로직을 추가해뒀는데도 더티 체킹이 동작하지 않나요? 이전에 제가 테스트 했을 때는 더티 체킹이 동작해서 자꾸 값이 들어갔던 것 같아서요! 추가적으로 확인이 필요할 것 같습니다...

2023-11-02 06:10 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    private final EntityManager entityManager;
좋은데요? `InMemorySongScheduler` 가 `EntityManager` 를 갖는 게 더 자연스러운 거 같습니다

2023-11-02 06:11 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    public void reorder(final Song updatedSong) {
🦅

2023-11-02 06:11 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +        final Song song = songsSortedInLikeCountById.get(killingPart.getSong().getId());
ㅋ.ㅋ.ㅋ.ㅋ.ㅋ.ㅋ.ㅋ..ㅋ..ㅋ.ㅋ.. 나중엔 도메인 이벤트도 적용해보죠 저희 도메인이 좀 이상한 거 같아요

2023-11-02 06:12 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +        final KillingPart killingPartById = findKillingPart(killingPart, song);
복잡하다보니 놓쳤네요 😢

2023-11-02 06:12 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +                                   songsSortedInLikeCountById.get(sortedIds.get(currentSongIndex - 1)))) {
Perfect~

2023-11-02 10:40 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/auth/config/AuthConfig.java
> +@Profile("!local")
LocalAuthConfig가 생기면서 product와 local를 분리할 때 "!"연산자를 이용해 분리한 것 처음 배워갑니다!

2023-11-02 10:54 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
> +    private transient AtomicInteger atomicLikeCount;
직렬화 되지 않게 transient 붙여준 것 좋네요!👍👍

2023-11-02 11:23 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
>              this.likeCount++;
좋은 방법인지 모르겠지만 아래와 같이 수정할 수 있을 것 같아요
this.likeCount++;
atomicLikeCount.incrementAndGet();
을
this.likeCount = atomicLikeCount.incrementAndGet();
로 변경하면 되지 않을까 싶습니다!

2023-11-02 11:26 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
> +    private transient AtomicInteger atomicLikeCount;
혹시 likeCount 자체를 AtomicInteger로 수정하지 않고 따로 필드로 만들어서 관리하는 이유가 있을까요?

2023-11-02 13:09 UTC, seokhwan-an requested changes

2023-11-02 13:09 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    }
현재 분기 처리 되어있는 if의 내용들이 이미 `moveLeft`와 `moveRight` 내부 while문에서 처리가 되어서 분기처리 없어도 동작할 것 같습니다.
```java
public void reorder(final Song updatedSong) {
    int currentSongIndex = sortedIds.indexOf(updatedSong.getId());

    if (currentSongIndex == -1) {
        return;
    }
    moveLeft(updatedSong, currentSongIndex)       
    moveRight(updatedSong, currentSongIndex)
}
```

2023-11-02 13:09 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +        final boolean hasLargerTotalLikeCountThanPrevSong = song.getTotalLikeCount() > prevSong.getTotalLikeCount();
변수명의 경우 `hasLargerTotalLikeCountThanPrevSong` 보다 `hasManylikesThanPrevSong`이 더 와닿을 것 같습니다. 변수명 짓는 것이 어렵다면 이 부분은 굳이 변수 명으로 분리해야할 만큼 로직이 복잡하지 않아 변수 없이 return에 바로 처리해도 괜찮을 것 같습니다!☺️

2023-11-02 13:09 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +
여기도 위와 같은 리뷰입니다!

2023-11-02 13:09 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    private static KillingPart findKillingPart(final KillingPart killingPart, final Song song) {
이 부분 static은 제거해도 될 것 같습니다!☺️

2023-11-02 13:09 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
>  }
unlike도 like와 같이 Song과 killingPart로 KillingPart를 찾아올 필요는 없을 것 같습니다!☺️

2023-11-02 13:11 UTC, seokhwan-an requested changes
베로 먼저 cache를 고도화 해주시느라 고생 많으셨어요😀
코드 리뷰를 하면서 많은 것을 배울 수 있었답니다!
리뷰에 대해 남겼는데 이해가 안되는 것 있으면 편하게 질문해주세요!

2023-11-03 05:48 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
> +    private transient AtomicInteger atomicLikeCount;
JPA 가 AtomicInteger 를 변환 못하더라고요 ㅠㅠ 그래서 추가했습니다!

2023-11-04 07:32 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +            .peek(entityManager::detach)
추가로 알아보고 나서 자답합니다! readonly 일 때는 더티 체킹이 동작하지 않는다고 합니다. 그렇지만 좋아요를 하는 로직은 readonly 를 걸어줄 수 없어서 더티 체킹이 발생합니다. 그래서 detach 가 필수적일 것 같아요!

2023-11-04 07:35 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
>          songsSortedInLikeCountById = getSortedSong(songs);
메서드 이름은 `refreshSongs`, 필드 이름은 `songs` 로 바꿔봤습니다 :)

2023-11-04 07:38 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
>      public List<Song> getSongs() {
`getSortedSongs` 삭제하고, 로직을 refreshSongs 에 넣었습니다!

2023-11-04 07:41 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +            swap(currentSongIndex, currentSongIndex + 1);
아니오 생깁니다 ㅋㅋ... 사실 동시성 까지 해결하고 내려고 했었는데 너무 길어질 것 같아서 일단 여기까지만 하고 냈어요. 동시성 부분은 좀 더 고민할 부분이 많을 거 같습니다 🥲

2023-11-04 07:48 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
>              this.likeCount++;
일반 likeCount 를 삭제하고, AttributeConverter 를 사용해서 필드로 `AtomicInteger` likeCount 를 갖도록 변경했습니다!

2023-11-04 07:50 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/application/killingpart/KillingPartLikeConcurrencyTest.java
> +                                    transactionTemplate.execute((status -> {
저도 모르겠어요... ㅋㅋㅋㅋㅋㅋ 한 번 스타일 맞추는 시간 다시 가지죠...

2023-11-04 07:50 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
> +    private transient AtomicInteger atomicLikeCount;
Converter 를 사용하면 된다고 해서 likeCount 의 타입을 AtomicInteger 로 변경했습니다!

2023-11-04 07:50 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
> +            atomicLikeCount.decrementAndGet();
ditto 입니다

2023-11-04 07:52 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/repository/dto/SongWithKillingPartsAndLikes.java
> +public interface SongWithKillingPartsAndLikes {
바로 삭제했습니다 👍🏻

2023-11-04 07:55 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +        final KillingPart killingPartById = findKillingPart(killingPart, song);
검증을 위한 것이 아닌 'detach' 된 `KillingPart` 을 가져오기 위해서 찾는 것입니다! 따라서 외부 `killingPart` 를 변경하는 것이 아닌, detach 된 `KillingPart` 를 변경하기 위해서 2번 과정이 필요합니다!

2023-11-04 08:01 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    }
헉 굉장하시네요 바로 그렇게 바꿨습니다! 그리고 여기서의 상수는 뜻을 가지는 게 아니라 단순히 범위가 넘었는지 확인하는 거라 따로 상수화는 안 했습니다 😄

2023-11-04 08:02 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +
파라미터 명칭을 바꾸고 현재 있는 currentSongIndex 를 제거하면 파라미터의 final 이 깨질 것 같아서 분리했었습니다! 혹시 부자연스럽나요?

2023-11-04 08:02 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    private void moveLeft(final Song changedSong, final int songIndex) {
네이밍이 어려워서...ㅋㅋㅋㅋ 더 좋네요 감사합니다 👍🏻

2023-11-04 08:03 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    }
짱입니다 진짜 꼼꼼히 보셨네요 중복 if 검증은 제거하겠습니다!

2023-11-04 08:04 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +            .peek(entityManager::detach)
앗 베로 답변에 질문이 있는걸 놓쳤어요.. 😱 찾아봐주셔서 감사합니다 납득완이에용 🫡

2023-11-29 06:29 UTC, somsom13 requested changes
안녕하세요 VERO~~~ 리뷰를 이렇게 늦게 다는 저를 매우 욕하세요.... 😢 😢 
설계랑 구현 모두 혼자 다 한 당신에게 박수를 보냅니다 👏 👏  어떻게 이렇게 짜셨죠? 
`inMemorySongs`에서 `update` 하는 부분과 `killingPartLikeService`에서 좋아요를 누르고 취소할 때 좋아요 상태가 바뀌는 부분에 대한 코멘트가 대부분이고, 나머지는 뭐 따봉! 이런 내용입니다.

질문이 좀 많아서 우선은 RC인데, 편하게 확인해주십쇼 ㅎ.ㅎ
고생하셨어요 💋

2023-11-29 06:29 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
> +                likeRepository.cancelLike(likeOnKillingPart.getId());
좋네용~ 그런데 좋아요 취소할 때는 `likeRepository.cancelLike`을 호출하지만 좋아요를 누를 때는 `pressLike`를 호출하지 않는 이유가 있을까요?.?


```java
// create 메서드 일부
if (likeOnKillingPart.isDeleted()) {
    inMemorySongs.like(killingPart, likeOnKillingPart);
    likeRepository.pressLike(likeOnKillingPart.getId());
}
```

2023-11-29 06:29 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    private static KillingPart findKillingPart(final KillingPart killingPart, final Song song) {
따봉!

2023-11-29 06:29 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +        while (canSwapWithNextSong(changedSong, currentSongIndex)) {
멋져!

2023-11-29 06:29 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
> +    @Convert(converter = LikeCountConverter.class)
Amazing 이래서 컨버터를 쓰는거군용 ㅋㅋㅋㅋㅋ 짱이다..

2023-11-29 06:29 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/InMemorySongsScheduler.java
> +    public void updateCachedSong() {
일정 주기마다 캐싱된 노래 데이터와 DB 싱크를 맞춰주는 코드 같아요!
준영속 되어있던 킬링파트를 영속화 시키면 해당 데이터가 영속성 컨텍스트에 들어가면서 데이터베이스에 변경사항이 반영되는 흐름이 맞을까요?.?

1. 이 부분에서 킬링파트만 영속화 시켜서 좋아요 **개수만 싱크를 맞추는 이유**가 궁금해요! (좋아요 상태는 DB에 실시간으로 반영하기 위함인가요??) 
2. 아직 prod 환경에서의 update-cron은 설정되어 있지 않은 것 같은데, 주기가 어떻게 되는지도 궁금합니다~!

2023-11-29 06:29 UTC, somsom13 commented on backend/src/main/java/shook/shook/song/application/InMemorySongsScheduler.java
> +        killingParts.forEach(entityManager::merge);
그리구 한 번 merge 한 다음에 다시 KillingPart를 detach 해주는 작업도 필요할 것 같은데 이건 따로 작성하지 않아도 되는건가용?.? (몰라서 하는 질문임니닷)

2023-11-29 06:32 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +        while (canSwapWithNextSong(changedSong, currentSongIndex)) {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ왜 갈수록 번역기가 되냐구요

2023-11-29 08:53 UTC, seokhwan-an reviewed
안녕하세요 베로!
오늘 아침부터 재귀 알고리즘 문제를 푸는데 쉽게 해결이 되지 않네요..
나중에 재귀 알고리즘도 강의 한번 부탁드립니다..(시간이 된다면 dp도 다시한번..)
저도 바론처럼 궁금한 부분에 대해서 질문을 많이 남겼습니다!
jpa 준영속에 대한 개념이 부족하다보니 바보같은 질문도 있을 수도 있습니다.
꼼꼼하게 구현하느라 고생했습니다!👍
저는 코드 수정보다는 질문이 많아서 comment로 리뷰 남겼습니다!

2023-11-29 08:53 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/song/application/InMemorySongsSchedulerTest.java
> +    }
베로 혹시 이 부분 테스트할 때 쿼리가 잘 나오나요?
저는 확인했을 때 쿼리가 하나도 나타나지 않네요.. 🥲

2023-11-29 08:53 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/song/application/InMemorySongsSchedulerTest.java
> +    }
바론이 알려줬는데 application-test.yml에 sql: debug를 추가하면 잘 나타납니다
```yaml
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    sql: debug
```

2023-11-29 08:53 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/song/application/killingpart/KillingPartLikeServiceTest.java
> +        @Disabled()
`@Disabled` 에는 괄호는 지워도 될 것 같습니다!😄

2023-11-29 08:53 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/InMemorySongsScheduler.java
> +        killingParts.forEach(entityManager::merge);
저도 이 부분이 궁금하네요! 따로 다시 detach를 안해도 괜찮은지 궁금합니다.
트랜잭션이 끝나면 영속성 컨텍스트도 같이 종료되니까 따로 안해도 괜찮을 것 같기도 하네요 (저도 이 부분을 잘 모르겠습니다.)

2023-11-29 08:53 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/application/InMemorySongsScheduler.java
> +        killingParts.forEach(entityManager::merge);
저 궁금한 것이 있는데 updateCachedSong이 동작하는 중간에 killingPart에 좋아요가 발생하는 상황은 따로 고려하지 않아도 되는 것인지도 궁금합니다. (updateCachedSong의 경우 영속성 컨텍스트로 정보를 merge하기에 이 때 좋아요가 발생해도 문제가 없는 것인지 궁금했습니다.)
제가 detach에 대한 개념이 부족해서 이상한 질문일 수도 있습니다..

2023-11-29 08:53 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    }
unlike 메소드 위치가 findKillingPart() 메소드와 reorder() 메소드 위에 있는 것이 더 가독성이 좋을 것 같습니다!😄

2023-12-15 06:47 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
> +                likeRepository.cancelLike(likeOnKillingPart.getId());
이 부분은 제 실수인 것 같아요 호출하는 코드로 바꿔두었습니다 👍🏻

2023-12-15 07:12 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/InMemorySongsScheduler.java
> +    public void updateCachedSong() {
1. 빈번하게 조회되는 데이터인 좋아요 개수만 싱크를 맞추도록 했습니다. 좋아요 상태도 한 번에 반영하면 어떨까 생각하기도 했는데 아무래도 마이페이지에 들어갔을 때 좋아요 취소한 파트가 있으면 이상할 것 같더라고요. 그래서 개수만 싱크를 맞추는 것으로 최종 선택했습니다. 어떤가요?
2. 설정해두었는데 security 싱크가 안 맞고 있는 것 같아요. 이번에 맞춰두었습니다!

2023-12-15 07:13 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/InMemorySongsScheduler.java
> +        killingParts.forEach(entityManager::merge);
동시성 관련된 부분은 당시 코드에서 고려되지 않았기 때문에 아코가 말씀하셨던 것처럼 updateCacheSong 이 동작하는 중간에 killingPart 에 좋아요가 발생하면 좋아요가 유실될 가능성이 있습니다. synchronized 키워드로 동시성을 보장하도록 코드를 작성했습니다!

2023-12-15 07:20 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/InMemorySongsScheduler.java
> +        killingParts.forEach(entityManager::merge);
그리고 원래라면 detach 를 해야 하지만, 위에서 말씀드린 것처럼 좋아요 데이터의 deleted 여부는 실시간으로 DB 에 반영되어야 할 것 같아서 하지 않았습니다...!

2023-12-15 07:21 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +                                                 .toList());
이게 방어적 복사 용도는 아니고 `toList` 로 하게 되면 리스트가 불변으로 만들어지는데 현재 코드에서는 정렬하면서 중간 데이터들이 변경되어야 하기 때문에 불변이 아닌 리스트로 만들기 위해 `new ArrayList` 를 해주었습니다.

2023-12-15 07:21 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +    }
넵 맞습니다! `InmemorySongs` 에 있는 detach 된 킬링파트를 찾기 위함입니다.

2023-12-17 07:03 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
> +                                                 .toList());
아! 답변 감사합니다 이해 완료입니다!👍

2023-12-17 08:12 UTC, seokhwan-an reviewed
베로 먼저 리뷰 반영하느라 고생 많으셨습니다!👍🙇‍♂️
리뷰를 반영 시 동시성 처리에 집중해서 코드를 수정하신 것 같아요!
동시성 처리를 한 것에 대한 제 의견을 간단하게 남겼습니다 이 부분 확인 부탁드립니다!

2024-01-16 22:29 UTC, seokhwan-an approved these changes
베로 캐싱을 고도화하느라 고생많았습니다!👍👍
어제 회의에서 다 같이 확인했기에 approve합니다!

2024-01-17 02:58 UTC, merged