Feat/#29: 노래 등록 조회, 파트 등록, 킬링파트 조회 기능 구현
woowacourse-teams/2023-shook pull request #56
Opened 2023-07-15 13:42 UTC by splitCoding

## 📝작업 내용

- [x] 노래 등록 기능 구현
- [x] 노래 조회 기능 구현
    - [x] ID 로 조회
    - [x] 제목으로 조회
- [x] 노래에 파트 등록 기능 구현
    - [x] 존재하지 않는 파트일 시 등록 후 기본 투표 1개 적용
    - [x] 존재하는 파트일 시 등록하지 않고 투표 1개 적용
- [x] TOP 킬링파트 조회 기능 구현
    - [x] 파트가 없어서 킬링파트가 없는 경우를 고려하여 KillingPartResponse 에 exist 프로퍼티 추가
- [x] 킬링파트 목록 조회 기능 구현
    - [x] 최대 3개 조회

## 💬리뷰 참고사항

### 동등성 비교를 통한 테스트가 반드시 필요한 객체에 한하여 ID를 포함한 정적 펙토리 메서드를 만들었습니다.
- 코드 상에서 실수로 ID 를 가진 엔티티를 생성하여 저장할 경우 기존 데이터가 덮어씌워지는 문제가 발생할 수 있기에 Id를 포함한 생성자는 private으로 감추고 메서드명에 의미를 노출했습니다.
    - notPersisted : 영속화, 저장 전
    - persisted : 영속화, 저장 후
    
### JPA를 사용하는 테스트
- 실제 DB에 반영이 되었는지 정확한 테스트를 위하여 필요한 시기에 entityManger를 flush, clear 한 뒤 실제 DB의 데이터를 통하여 테스트하는 방식을 택했습니다.

## #️⃣연관된 이슈
- #27 
- #29 
- #30 
- #31 

closed #29 
closed #30 
closed #31

2023-07-16 08:37 UTC, somsom13 requested changes
하루 동안 이만큼이나 짰다는게 믿기지 않아요 🥲 🥲 

코드 리뷰 이렇게 본격적으로 하는건 처음이라서 리뷰에 담을만한 내용이 아닌 코멘트도 많을 것.. 같아요 😿 

변경 사항보다는 다같이 이야기 해보고 싶은 부분들 위주로 코멘트 남겼습니당 ㅎ.ㅎ

너무 고생하셨습니다 👍 👍

2023-07-16 08:37 UTC, somsom13 commented on backend/src/main/java/shook/shook/part/domain/Parts.java
> +    }
💬 질문이 있습니다!!!
정렬 `sort()` 가 모든 메서드에서 사용되는 것 같은데, 처음에 Parts를 만들 때 정렬한 상태로 저장하는 등의 방법 말고 `sorted` 라는 필드를 따로 둔 이유가 궁금해요~~!!

2023-07-16 08:37 UTC, somsom13 commented on backend/src/main/java/shook/shook/part/domain/repository/PartRepository.java
> +public interface PartRepository extends JpaRepository<Part, Long> {
💬 이 코드 보면서 `@Repository` 어노테이션이 없어도 잘 동작한다는 걸 이번에 처음 알았는데요....ㅎㅎ 
JpaRepository를 상속받는 Repository 인터페이스에 어노테이션을 붙일지, 붙이지 않을지도 정하면 좋을 것 같아요!!

2023-07-16 08:37 UTC, somsom13 commented on backend/src/main/java/shook/shook/part/domain/Parts.java
> +        if (parts.size() <= 3) {
요런 매직 넘버들을 상수로 분리하면 의미가 더 잘 보일 것 같은데 어떤가요??

2023-07-16 08:37 UTC, somsom13 commented on backend/src/test/java/shook/shook/part/application/PartServiceTest.java
> +        @DisplayName("이미 등록된 파트일 때")
💬 이건 정말 저의 취향이지만... 저는 테스트의 디스플레이네임은 자세하게 쓸 수록 더 이 테스트가 의미하는 바가 잘 보이는 것 같더라구요!!

예를 들면, 이 테스트에서는 "이미 등록된 파트일 때, 파트를 등록하면 투표수가 1 증가한다." 이런 느낌으로요..!

이것도 다같이 이야기해보면 좋을 것 같습니당 ㅎㅎ

2023-07-16 08:37 UTC, somsom13 commented on backend/src/test/java/shook/shook/part/application/PartServiceTest.java
> +            final Part fourthPart = Part.notPersisted(4, PartLength.SHORT, SAVED_SONG);
어마어마하네요 
고생 많으셨습니다.. 🥲🥲

2023-07-16 08:37 UTC, somsom13 commented on backend/src/test/java/shook/shook/part/domain/PartLengthTest.java
> +    @CsvSource(value = {"5:SHORT", "10:STANDARD", "15:LONG"}, delimiter = ':')
👍 👍 👍 여기도 어마어마.....

2023-07-16 09:12 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/application/dto/SongRegisterRequest.java
> +    @NotBlank
Integer의 경우에는 `@NotBlank` 를 쓸 수 없습니당 🥺
`@NotBlank`는 String에서만 쓸 수 있다고 알고 있어요.
`@NotNull` 이나 `@Range`를 사용하는 것이 좋을 것 같아요 👍

2023-07-16 09:15 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/Singer.java
> +@EqualsAndHashCode
💬 Singer가 값 객체라서 `@EqualsAndHashCode`를 작성하신건가요? (단순히 의도가 궁금합니다 🫡)

2023-07-16 09:16 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/Song.java
> +    private final Set<Part> parts = new HashSet<>();
💬 오호 parts가 불변하게 되어 final을 달아두셨군여 👍

2023-07-16 09:17 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/Song.java
> +    }
여기서 생성자를 `private` 으로 막지 않은 이유는 무엇인가요? 🤔
다른 코드에서는 `persisted`, `notPersisted` 가 있었던 것 같은데, 어떤 차이점이 있는지 궁금합니다!

2023-07-16 09:19 UTC, Cyma-s commented on backend/src/main/java/shook/shook/part/domain/Part.java
> +    }
💬 사용되는 부분이 언제나 !으로 사용되던데, `Vote`의 경우처럼 `isBelongToOtherSong()` 처럼 네이밍을 바꿔보는 것에 대해 어떻게 생각하시나요? 😉

2023-07-16 09:20 UTC, Cyma-s commented on backend/src/main/java/shook/shook/song/domain/Song.java
> +    public Optional<Part> getSameLengthPartStartAt(final int start, final PartLength length) {
💬 `Optional` 사용 굿입니다 👍

2023-07-16 09:22 UTC, Cyma-s commented on backend/src/test/java/shook/shook/part/application/PartServiceTest.java
> +    class Register {
💬 앞으로 이런 경우에 `@Nested` 를 사용할 건지 이야기 나눠보면 좋을 거 같네용

2023-07-16 09:25 UTC, Cyma-s commented on backend/src/test/java/shook/shook/part/application/PartServiceTest.java
> +            final PartRegisterRequest request = new PartRegisterRequest(1, 10, 0L);
💬 `0L`을 따로 변수로 분리하는 건 어떨까요? 
`0L`에 이름이 생기면 좀 더 보기 편할 것 같다는 생각이 드네용 🤔

2023-07-16 09:28 UTC, Cyma-s commented on backend/src/test/java/shook/shook/part/application/PartServiceTest.java
> +        @DisplayName("킬링파트가 충분하지 않을 때 ( 2개일 떄 )")
이번엔 `떄` 처리 잠시 잊으셨나보군여 ㅋㅋㅋ 
`exist_notEnough_one()` 부분에도 오타가 존재하네요 😂 수정 부탁드립니다 😎

2023-07-16 09:30 UTC, Cyma-s commented on backend/src/test/java/shook/shook/part/domain/PartLengthTest.java
> +    @ParameterizedTest(name = "초가 {0}일 때 {1}를 반환한다.")
💬 `@ParameterizedTest` 처리랑 표시되는 부분도 꼼꼼하게 처리해주셨군요 👍

2023-07-16 09:32 UTC, Cyma-s commented on backend/src/test/java/shook/shook/part/domain/PartTest.java
> +    @DisplayName("파트에 한번 투표한다.")
💬 진짜 사소한 거긴 한데 "파트에 투표한다" 가 좀 더 어울릴 것 같아요
아래 쪽에 "한 번 투표한다", "여러 번 투표한다" 라는 `@DisplayName` 이 있어서 제안해봅니다.

2023-07-16 09:33 UTC, Cyma-s commented on backend/src/test/java/shook/shook/part/domain/PartTest.java
> +        @DisplayName("Id 가 같은 두 개의 투표를 통해 투표했을 때")
💬 오 이런 테스트까지 ㄷㄷ 👍

2023-07-16 09:35 UTC, Cyma-s commented on backend/src/test/java/shook/shook/part/domain/PartsTest.java
> +        final Optional<Part> bestKillingPart = parts.getTopKillingPart();
💬 변수와 메서드의 네이밍이 통일되면 좋을 것 같아요! 
변수 이름을 `topKillingPart` 로 사용하거나, 아니면 메서드의 이름을 `getBestKillingPart`로 하는 건 어떨까요? 👀

2023-07-16 09:38 UTC, Cyma-s commented on backend/src/test/java/shook/shook/part/domain/repository/PartRepositoryTest.java
> +        assertThat(part.getCreatedAt()).isAfter(prev).isBefore(after);
💬 이런 코드는 어떠신가용 😊
```suggestion
                assertThat(part.getCreatedAt()).isBetween(prev, after);
```

2023-07-16 09:39 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/application/SongServiceTest.java
> +        Assertions.assertAll(
💬 이 부분은 static import 를 안 하신 이유가 궁금해요 🤔

2023-07-16 09:42 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/domain/SongVideoUrlTest.java
> +    }
아직 이미지 URL 이라고 표현된 부분이 남아있는 것 같아요!
비디오 URL로 변경하면 좋을 것 같네요 👍

2023-07-16 09:43 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
> +    }
💬 이 부분 코드가 반복적으로 나타나는데 분리할 수 있는 방법은 없으려나요 🤔
분리하는 게 나을지 아닐지도 같이 이야기해보면 좋을 것 같아요

2023-07-16 09:45 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/application/SongServiceTest.java
> +        Assertions.assertAll(
💬 `assertAll`을 쓴 부분과 안 쓴 부분의 차이점은 무엇인가요? 이 부분에만 `assertAll`이 있는 것 같아서 궁금합니당

2023-07-16 09:46 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
> +        assertThat(song.getCreatedAt()).isAfter(prev).isBefore(after);
💬 여기도 위에 작성한 리뷰와 동일합니다!

2023-07-16 09:47 UTC, Cyma-s commented on backend/src/test/java/shook/shook/song/domain/SongVideoUrlTest.java
> +class SongVideoUrlTest {
여기도 `@DisplayName`, 변수 이름이 이미지 URL 인 곳이 남아있어요! 🔊

2023-07-16 09:48 UTC, Cyma-s commented on backend/src/main/java/shook/shook/part/domain/repository/PartRepository.java
> +public interface PartRepository extends JpaRepository<Part, Long> {
헉 그렇네요 알아갑니다

2023-07-16 10:28 UTC, Creative-Lee commented
코드 리뷰 궁금해서 들어왔습니다
퀄리티 상당하네요...👍
빠이팅입니다👶

2023-07-16 13:43 UTC, seokhwan-an requested changes
로직 코드와 테스트 코드를 엄청 꼼꼼하게 작성하셨네요 👍👍 
몇가지 의문점이 있는 부분과 올바르게 동작하지 않는다고 생각하는 부분에 대해 리뷰를 남겼습니다!
내일 같이 이야기 나눠보아요!

2023-07-16 13:43 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/part/application/PartServiceTest.java
> +        void songNotExist() {
사소한 리뷰지만 `"등록하려는 노래가 없을 때"` 에서 `"등록하려는 파트의 노래가 없을 때"` 변경하는 것이 더 명확할거 같습니다.

2023-07-16 13:43 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/part/domain/PartsTest.java
> +    }
💬 이 테스트는 firstPart와 secondPart가 중복된 파트(같은 파트)가 아닌데 통과가 되고 있습니다. 혹시 이 테스트는 두 파트가 같은 아이디를 가지는 경우에 에러를 반환하는 것으로 설계하신 건가요?
```java
final Part firstPart = Part.persisted(1L, 5, PartLength.SHORT, song);
final Part secondPart = Part.persisted(2L, 5, PartLength.SHORT, song);
```
오히려 Id가 다르고 시작점과 파트 시간이 같은 경우에 에러가 발생하지 않습니다.

2023-07-16 13:43 UTC, seokhwan-an commented on backend/src/main/java/shook/shook/part/domain/Parts.java
> +    }
💬uniqueCount를 구하는 로직에서 distinct()가 동작할 때 part의 equals() & hashcode() 재정의에 영향을 받아서 part의 시작과 길이가 같은 것을 같은 part로 보는 것이 아니라 단순하게 id만 같은 경우에만 같은 파트로 보는 것 같습니다.

2023-07-16 13:43 UTC, seokhwan-an commented on backend/src/test/java/shook/shook/part/domain/PartTest.java
> +    }
partTest는 도메인 테스트여서 `@BeforeEach` 테스트 메소드를 실행할 때 마다 song 변수에 재할당을 하는 것 보다 song변수를 선언할 때 객체를 할당해주는 것 어떻게 생각하시나요?

2023-07-17 05:53 UTC, splitCoding commented on backend/src/main/java/shook/shook/part/domain/PartLength.java
> +    }
PartLength 에서 시작이 0보다 작으면 안된다는 비즈니스 상황을 몰라도 될 것 같다고 생각해요😄

2023-07-17 08:47 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/Singer.java
> +@EqualsAndHashCode
YES😁

2023-07-17 08:50 UTC, splitCoding commented on backend/src/main/java/shook/shook/song/domain/Song.java
> +    }
ID를 사용한 테스트가 필요없는 엔티티이고 ID를 포함한 생성자를 열어놓음으로 인한 문제 발생자체를 없애기 위해 이렇게 했습니다😎

2023-07-17 09:56 UTC, Cyma-s approved these changes
첫 백엔드 PR 머지~~ 🦐
수고 많으셨습니다 👾

2023-07-17 09:56 UTC, somsom13 approved these changes
고생하셨습니다~! 👍 👍 👍 👍

2023-07-17 09:56 UTC, seokhwan-an approved these changes
오늘 같이 코드리뷰를 하면서 스플릿의 생각을 들어볼 수 있어서 좋았습니다. 고생하셨습니다~

2023-07-17 09:57 UTC, splitCoding commented
😊

2023-07-17 09:57 UTC, merged