Feat/#58 IntervalInput 컴포넌트 (킬링파트 등록 시간 input) 구현
woowacourse-teams/2023-shook pull request #69
Opened 2023-07-17 11:40 UTC by ukkodeveloper

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명(이미지 첨부 가능)
- input 4개 구현했습니다.
- 시작 구간 입력 시에 자동으로 끝이 입력됩니다.
- interval (5초 / 10초/ 15초)를 정할 수 있기 때문에, 끝점은 입력이 불가능하도록 하였습니다.
- 사용자가 옳은 입력을 할 수 있도록 change, blur, focus 이벤트를 이용하여 에러 메세지를 띄워줍니다.

사진
<img width="260" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/109048739/b4620cad-9a7f-4f6d-a2d9-df7a45df3cf5">

## 💬리뷰 참고사항
> 원활한 리뷰를 위해 전달하고 싶은 맥락(특정 파일, 디렉터리 등등)  
> 리뷰어가 특별히 봐주었으면 하는 부분
- 컴포넌트를 더 분리할 필요가 있는 지 확인해주세요.
- 추가로 할 테스트가 있는 지, 필요 없는 테스트는 있는 지 확인해주세요.
- 사용자에게 더 좋은 사용 경험을 위해 개선할 점이 있으면 알려주세요.

## #️⃣연관된 이슈

close #58

2023-07-17 15:34 UTC, cruelladevil commented on frontend/src/components/IntervalInput/IntervalInput.test.tsx
> +    const [startMin, startSec, ,] = screen.getAllByRole<HTMLInputElement>('textbox');
안쓰는 콤마는 지우는 게 좋을 것 같아요

```suggestion
    const [startMin, startSec] = screen.getAllByRole<HTMLInputElement>('textbox');
```

2023-07-17 15:34 UTC, cruelladevil commented on frontend/src/components/IntervalInput/IntervalInput.test.tsx
> +  test('start(4:10)가 노래(3:30)보다 길면 에러메세지를 띄운다.', async () => {
async를 실수로 넣은 것 같네요😅

2023-07-17 15:34 UTC, cruelladevil commented on frontend/src/components/IntervalInput/IntervalInput.tsx
> +  } = useIntervalInput(songEnd);
분리 시도 좋아요 👍

2023-07-17 16:38 UTC, cruelladevil requested changes
- [x] 컴포넌트를 더 분리할 필요가 있는 지 확인해주세요.
- [x] 추가로 할 테스트가 있는 지, 필요 없는 테스트는 있는 지 확인해주세요.
- [ ] 사용자에게 더 좋은 사용 경험을 위해 개선할 점이 있으면 알려주세요.

노래 총 길이 1:35초 일때 초 단위에서 155를 입력하고 blur가 되면 에러 메세지가 남아있습니다.
이 경우 유효한데도 에러메세지를 계속 띄우고 있으니 문제가 될 것 같아요. (코멘트에 해당 상황 달아놓았습니다)

2023-07-17 16:38 UTC, cruelladevil commented on frontend/src/utils/convertTime.ts
> +};
> secondsToMinSec와 minSecToSeconds를 동시에 쓰는 일이 생기긴 했네요..

이 함수는 의도도 불명확하고 이해하기 불편한 함수라고 생각이 들어요.

```ts
const [endMinute, endSecond] = complyToMinSec(
  startMinute,
  startSecond,
  (origin: number) => origin + 10
);
```
를
```ts
const startSeconds = minSecToSeconds(startMinute, startSeconds);
const [endMinute, endSecond] = secondsToMinSec(startSeconds + 10);
```
라고 써도 충분할 것 같아요.

2023-07-17 16:38 UTC, cruelladevil commented on frontend/src/utils/validateTime.test.ts
> +  test('140초 + 10초는 192초보다 작으니 true를 반환한다.', () => {
💬 테스트 제목에 대해 함께 고민해보면 좋을 것 같아요

```ts
test(`140초 + 10초는 ${songEnd}초 내에 있다.`, () => {
...
```

2023-07-17 16:38 UTC, cruelladevil commented on frontend/src/components/IntervalInput/IntervalInput.stories.tsx
> +  title: 'Header',
title을 'Header'라고 잘못 쓴 것 같아요 😅

2023-07-17 16:38 UTC, cruelladevil commented on frontend/src/components/IntervalInput/IntervalInput.style.ts
> +  box-sizing: border-box;
box-sizing 속성은 블록 레벨 요소에 적용되는 속성이지 않나요?

2023-07-17 16:38 UTC, cruelladevil commented on frontend/src/utils/validateTime.test.ts
> +describe('isValidMinSec: 초/분 양식이 맞는지 확인하는 함수', () => {
👍 다양한 케이스에 대한 고민이 담긴 것 같아요. 대단합니다👍

2023-07-17 16:38 UTC, cruelladevil commented on frontend/src/utils/validateTime.test.ts
> +    expect(isTimeInSongRange({ timeSelected: 187, songEnd, interval: 5 })).toBe(true); //(input, interval, song)
💬 주석의 `//(input, interval, song)`는 어떤 의미인가요?

2023-07-18 04:43 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/IntervalInput.test.tsx
> +    const [startMin, startSec, ,] = screen.getAllByRole<HTMLInputElement>('textbox');
안쓰는 콤마 지울게요!

2023-07-18 04:45 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/IntervalInput.test.tsx
> +  test('start(4:10)가 노래(3:30)보다 길면 에러메세지를 띄운다.', async () => {
꼼꼼하지 못했네요! 바로 적용하겠습니다.

2023-07-18 04:46 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/IntervalInput.tsx
> +          $active={activeInput === 'minute'}
(이미 논의한 내용)
1. 실제 DOM attribute에 적용되지 않는다.
2. $를 붙이지 않은 경우 testing-library 사용 중에 에러를 발생시킨다.

2023-07-18 04:47 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/hooks/useIntervalInput.ts
> +  };
blur 시에 검증 후 이상 없으면 메세지를 없애는 코드를 추가했어요!

2023-07-18 04:57 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/index.ts
> +export { default as IntervalInput } from './IntervalInput';
1번이요! 2번의 경우 컴포넌트 명을 강제할 수가 없어요. 실수로 사용처에서 다른 이름으로 컴포넌트를 사용할 가능성을 막기 위해서 2번으로 했습니다. 
2번 오용 예시
`import Conan form '@/components/IntervalInput'`
이렇게 사용해도 린트에서 잡아주지 못합니다!

물론 1번의 경우에도 
`import { IntervalInput as Conan} from '@/components/IntervalInput';` 
으로 작성해도 린트에서 잡아주진 못 합니다. 그래도 다음과 같은 상황은 실수에 가깝고 as까지 타이핑하면서 실수할 일이 적기 때문에 named export로 적용했습니다. 

다만 개인적인 생각으로는 사소한 문제이고 팀원들끼리만 export 방식이 통일되면 그 방식으로 진행해도 괜찮을 것 같습니다.

2023-07-18 05:00 UTC, ukkodeveloper commented on frontend/src/utils/validateTime.ts
> +};
interval만큼 뺀 만큼 시작점을 잡아야 한다는 것을 쉽게 생각할 수 있도록 함수로 만들었습니다. 그런데 코난 의견대로 함수를 없애고 적용을 해보니 함수로 작성했을 때 보다 훨씬 의미가 명확한 것 같습니다. 좋은 의견 감사해요!

2023-07-18 05:54 UTC, ukkodeveloper reviewed
리뷰 반영했습니다. 말풍선 달아 놓은 것은 함께 의논하면 좋을 것 같아요

2023-07-18 05:54 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/IntervalInput.style.ts
> +`;
Flex라고 이름 지으면 너무 포괄적은 느낌이라 특정하기 위해 InputFlex로 두었어요. 하지만 접근 범위를 생각하면 Flex라고 이름 지어도 상관 없는 문제이긴 합니다.

2023-07-18 05:54 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/IntervalInput.style.ts
> +  box-sizing: border-box;
span(inline element)라도 flex 컨테이너 안에 있는 요소이기 때문에 `box-sizing` 속성은 제대로 적용됩니다. 


`width: 100px; padding: 20px;`를 주었고, box-sizing을 비교한 그림입니다.
<img width="326" alt="image" src="https://github.com/woowacourse-teams/2023-shook/assets/109048739/b9e3eabb-bbf7-4c20-a661-9e3de7eff515">

다만 해당 코드는  width를 따로 주지 않았기 때문에 삭제해도 무방한 코드입니다. 스타일링 과정에서 reset css가 되어있지 않았기 때문에 스타일 추가하기 전에 추가한 코드입니다.

2023-07-18 05:54 UTC, ukkodeveloper commented on frontend/src/utils/convertTime.ts
> +};
앞에 부분 저도 고민이었는데, 이렇게 짚어주니 튜플로 인자를 받는 게 역시 좋겠네요. 

💬

>  초에서 분초로 변환하고 분초를 더하고 초로 다시 변환하는 경우도 생길 것 같네요!

해당 경우에는 초에서 변환하고 분초로 변경하면 되지 않을까요???

2023-07-18 05:54 UTC, ukkodeveloper commented on frontend/src/utils/convertTime.ts
> +};
💬 
해당 함수의 목적은, 분/초로 되어 있는 데이터의 경우 연산이 불가능하다는 점에서 시작했습니다. 예를 들어 2분 55초에서 10초를 더하는 경우, 반드시 2분 55초를 초로 바꾼 다음 다시 분/초로 변경해야하죠. 
```ts
const startSeconds = minSecToSeconds(startMinute, startSeconds);
const [endMinute, endSecond] = secondsToMinSec(startSeconds + 10);
```
이렇게 사용하는 것보다 하나의 함수로 만드는 것이 낫겠다라는 판단하에 `complyToMinSec `라는 함수가 필요하다고 생각합니다. 다만, 해당 함수 네이밍이 모호한 것은 인정합니다. 그래서 `calculateMinSec`으로 변경했는데, 이부분 검토 부탁드려요

2023-07-18 05:54 UTC, ukkodeveloper commented on frontend/src/utils/validateTime.test.ts
> +    expect(isTimeInSongRange({ timeSelected: 187, songEnd, interval: 5 })).toBe(true); //(input, interval, song)
의미없는 주석이에요! 삭제했어요

2023-07-18 08:56 UTC, Creative-Lee requested changes
input 컴포넌트 정말 이것 저것 신경써야 할 부분 많았을텐데 고생 많으셨습니다!
코멘트 한번 확인해주시고 이해 안되면 꼭 저 찾아와주세요!
화이팅합시다아~~ ㅎㅎ

---

스토리북 상으로는 모바일 사이즈에서 input이 과도하게 작아지는 경우가 있는데 이 부분 확인하고 말해주세요~
![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/50cef1cf-fbb7-4d31-a2ee-8237fec7b0e3)

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/hooks/useIntervalInput.ts
> +const useIntervalInput = (songEnd: number) => {
`songEnd: number` 라는 인자와 타입만 보고서는 
`노래의 끝지점을 초 단위로 변환한 숫자` 라는 것을 알기는 힘든 것 같아요.
명확해지면 좋을 것 같아요!

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/hooks/useIntervalInput.ts
> +    if (timeSelected > songEnd - 10) {
이 부분에서 훅의 인자인 songEnd가 사용되는데요!

songEnd라는 네이밍에  `second(초)` 의 의미가 추가되면, 
뒤에있는 `-10`이라는 계산식의 숫자도 `second(초)`의 의미라고 파악하게되고 이해가 쉬워질 것 같아요.

코드를 읽는 사람은 timeSelecete가 초 단위인 것을 알고 있으니깐요!

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/hooks/useIntervalInput.ts
> +    const timeSelected = minSecToSeconds([startMinute, startSecond]);
마이너 하지만 selectedTime 이 조금더 올바른 표현같아요ㅎ...

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/hooks/useIntervalInput.ts
> +  const onBlurIntervalStart = () => {
개인적으로 이 함수 한번 설명해주세요 ㅎㅎ
이따가 찾아갑니다

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/IntervalInput.stories.tsx
> +  title: 'IntervalInput',
여기에 argTypes를 사용해보면 좋을 것 같아요!

(아래 이어짐...)

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/IntervalInput.stories.tsx
> +  args: {
위에서 argType을 작성하고
여기서 컴포넌트를 리턴하면서, 그 인자로 제공되는 arg를 사용하는 방식으로 바꿔보면 좋을 것 같아요!
스토리북에서 number 값을 입력하고 그에 대한 테스트를 해보고 싶었는데 불가능 했습니다!

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/IntervalInput.style.ts
> +  color: ${({ $active }) => ($active ? '#DE2F5F' : 'white')};
💬 컬러 코드 사용에 대한 부분도 컨벤션을 맞춰보면 좋겠네요! 

#fff
#ffffff
#FFF
#FFFFFFF
#white

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/IntervalInput.style.ts
> +  margin: 0 5px;
css에서 px은 짝수인게 좋다고해요!(4배수, 8배수)

저도 이유는 잘 몰라서 공부해봤는데,
`반응형 디자인을 할 때 불편한 요소가 될 수 있다` 라고만 알고있었는데,
요소가 깨지는 현상도 있다고 하네요!


[왜 8배수 디자인?](https://velog.io/@seb_bbi__/%EC%99%9C-8-Point-%EA%B7%B8%EB%A6%AC%EB%93%9C%EB%A5%BC-%EB%A7%9E%EC%B6%B0%EC%95%BC-%ED%95%98%EC%A3%A0)
[픽셀 디자인](https://www.remain.co.kr/page/designsystem/ratio-design.php)

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/IntervalInput.test.tsx
> +
이 부분 input들 n개가 들어있는 배열같은데요!

아래 테스트 케이스를 보고 이 배열 네이밍이 의문이라 돌아왔어요!
startMin이 맞나요?

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/IntervalInput.test.tsx
> +
1분 55초 -> 2분 5초 처럼 임계값에 대한 테스트가 하나 더 있으면 좋을 것 같아요!
분 단위 인풋도 잘 변하는지 알 수 있을 것 같습니다!

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/IntervalInput.test.tsx
> +});
1분 10초로 변경해도 테스트 케이스가 통과합니다!
확인이 필요해요😶

![image](https://github.com/woowacourse-teams/2023-shook/assets/77152650/9eb9dadb-a5b5-4cdd-8194-e460c322b715)

2023-07-18 08:56 UTC, Creative-Lee commented on frontend/src/components/IntervalInput/IntervalInput.tsx
> +        <InputEnd id="end-sec" value={endSecond} disabled />
이 컴포넌트의 id는 어디서 사용되나요?

2023-07-18 13:36 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/hooks/useIntervalInput.ts
> +  const onChangeIntervalStart: ChangeEventHandler<HTMLInputElement> = ({
💬 React 사용하면서 native 이벤트 헨들러와 함께 사용할 일이 있을까요? 이 부분에 대해서 혹시 참고자료가 있을까요?

2023-07-18 16:07 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/hooks/useIntervalInput.ts
> +    const timeSelected = minSecToSeconds([startMinute, startSecond]);
[개발자 글쓰기라는 책을 정리한 블로그](https://velog.io/@ayoung0073/%EA%B0%9C%EB%B0%9C%EC%9E%90%EC%9D%98-%EA%B8%80%EC%93%B0%EA%B8%B0-%EA%B0%9C%EB%B0%9C-%EC%8B%9C%EA%B0%84%EC%9D%84-%EC%A4%84%EC%97%AC%EC%A3%BC%EB%8A%94-%EC%9D%B4%EB%A6%84-%EC%A7%93%EA%B8%B0%EC%99%80-%EC%A3%BC%EC%84%9D-%EC%93%B0%EA%B8%B0#%EB%B3%B5%EC%88%98%ED%98%95%EC%9D%84-%EB%82%98%ED%83%80%EB%82%B4%EB%8A%94-s%EB%A5%BC-%EB%B6%99%EC%9D%BC%EA%B9%8C-%EB%A7%90%EA%B9%8C)에서 "중요 단어를 앞에 쓴다" 부분을 참고해서 다음과 같이 이름을 지었습니다. 물론, 해당 부분은 영문법 상 selectedTime으로도 많이 사용하는 것으로 알고 있어요.

2023-07-18 16:12 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/hooks/useIntervalInput.ts
> +    if (timeSelected > songEnd - 10) {
💬 모든 정보를 변수명에 나타내는 것이 과연 좋은 네이밍일까요?

2023-07-18 16:13 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/IntervalInput.stories.tsx
> +  args: {
이부분은 직접 도밥에게 배우고 싶군요!

2023-07-18 16:13 UTC, ukkodeveloper commented on frontend/src/components/IntervalInput/IntervalInput.style.ts
> +  color: ${({ $active }) => ($active ? '#DE2F5F' : 'white')};
좋아요!

2023-07-18 23:53 UTC, ukkodeveloper commented on frontend/src/utils/validateTime.test.ts
> +  test('140초 + 10초는 192초보다 작으니 true를 반환한다.', () => {
좋아요 같이 이야기 나누면 좋을 것 같아요!

2023-07-19 00:59 UTC, Creative-Lee commented on frontend/src/utils/convertTime.ts
> +};
좋습니다~!
그 외에 변수 선언에 대한 부분은 취향차이라고 생각해요.
다만 처음 코드를 보는 개발자는 함수의 역할이 정확히 파악되지 않아 다소 보기 힘들었다는 의견이었습니다~
`코드를 읽는 한 호흡이 길었다~` 라고 말하고 싶었어요.

2023-07-19 04:24 UTC, merged